export type UniversalObjectType="contact"|"company"|"address"|"document"|"activity"|"note"|"attachment"|"tag"|"property"|"lead"|"deal"|"task"|"calendar"|"agent"|"ai-memory";
export type UniversalObjectRef={id:string;type:UniversalObjectType;label:string};
export type AIExtension={summary?:string;recommendations:readonly string[];confidence?:number;insights:readonly string[];relationships:readonly UniversalObjectRef[];status:"placeholder"|"ready"};
export interface UniversalObjectBase{id:string;type:UniversalObjectType;displayName:string;status:string;tags:readonly string[];metadata:Readonly<Record<string,unknown>>;createdAt:string;updatedAt:string;ai:AIExtension}
export interface UniversalAddress extends UniversalObjectBase{type:"address";countryCode:string;state:string;city:string;postalCode:string;street:string;latitude?:number;longitude?:number;validated:boolean}
export interface UniversalContact extends UniversalObjectBase{type:"contact";firstName:string;lastName:string;company?:UniversalObjectRef;email:string;phone:string;alternatePhone?:string;whatsapp?:string;address?:UniversalAddress;language:string;timezone:string;notes:string;avatar?:string;relationships:readonly UniversalObjectRef[];activitySummary:string;relationshipCount:number}
export interface UniversalCompany extends UniversalObjectBase{type:"company";name:string;industry:string;organizationType:string;website?:string;taxInformation?:string;addresses:readonly UniversalAddress[];contacts:readonly UniversalObjectRef[];deals:readonly UniversalObjectRef[];properties:readonly UniversalObjectRef[];documents:readonly UniversalObjectRef[]}
export type DocumentVersion={id:string;version:number;fileName:string;size:number;createdAt:string;createdBy:string};
export interface UniversalDocument extends UniversalObjectBase{type:"document";category:string;mimeType:string;versions:readonly DocumentVersion[];sharedWith:readonly UniversalObjectRef[];linkedRecords:readonly UniversalObjectRef[];ocrStatus:"placeholder"|"unavailable"|"ready";extractionStatus:"placeholder"|"unavailable"|"ready"}
export interface UniversalActivity extends UniversalObjectBase{type:"activity";activityType:"lead"|"deal"|"calendar"|"email"|"whatsapp"|"call"|"task"|"note"|"document"|"ai";occurredAt:string;summary:string;actor?:UniversalObjectRef;linkedRecords:readonly UniversalObjectRef[]}
export interface UniversalNote extends UniversalObjectBase{type:"note";body:string;mentions:readonly UniversalObjectRef[];attachments:readonly UniversalObjectRef[];pinned:boolean;markdownReady:true}
export interface UniversalAttachment extends UniversalObjectBase{type:"attachment";fileName:string;mimeType:string;size:number;kind:"image"|"pdf"|"word"|"excel"|"video"|"audio"|"other";version:number;linkedObjects:readonly UniversalObjectRef[];localUrl?:string}
export interface UniversalTag extends UniversalObjectBase{type:"tag";name:string;color:string;category:string;usageCount:number;mergedInto?:string}
export interface UniversalRelationship{id:string;source:UniversalObjectRef;predicate:string;target:UniversalObjectRef;metadata:Readonly<Record<string,unknown>>;createdAt:string}
export type UniversalObject=UniversalContact|UniversalCompany|UniversalAddress|UniversalDocument|UniversalActivity|UniversalNote|UniversalAttachment|UniversalTag;
