import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { PlanRecord, SubscriptionRecord } from "../types";
export class SubscriptionRepository {
  constructor(private client: SupabaseClient, private organizationId: string, private workspaceId: string) {}
  async plans(): Promise<PlanRecord[]> { const { data, error } = await this.client.from("subscription_plans").select("id,code,name,description,monthly_price,currency,limits,features,active").eq("active", true).order("sort_order"); if (error) throw error; return (data ?? []).map((row) => ({ id: row.id, code: row.code, name: row.name, description: row.description, monthlyPrice: row.monthly_price === null ? null : Number(row.monthly_price), currency: row.currency, limits: row.limits ?? {}, features: row.features ?? [], active: row.active })); }
  async current(): Promise<SubscriptionRecord|null> { const { data, error } = await this.client.from("subscriptions").select("id,plan_id,status,trial_ends_at,current_period_ends_at,cancel_at_period_end,seat_quantity,version,provider_subscription_id,subscription_plans(code,name)").eq("organization_id", this.organizationId).eq("workspace_id", this.workspaceId).is("deleted_at", null).maybeSingle(); if (error) throw error; if (!data) return null; const plan=data.subscription_plans as unknown as {code:string;name:string}|null; return { id:data.id,planId:data.plan_id,planCode:plan?.code,planName:plan?.name,status:data.status,trialEndsAt:data.trial_ends_at??undefined,currentPeriodEndsAt:data.current_period_ends_at??undefined,cancelAtPeriodEnd:data.cancel_at_period_end,seatQuantity:data.seat_quantity,version:data.version,providerSubscriptionId:data.provider_subscription_id??undefined }; }
  async change(planCode:string,seats:number,version:number){const{error}=await this.client.rpc("change_subscription_plan",{p_workspace_id:this.workspaceId,p_plan_code:planCode,p_seat_quantity:seats,p_expected_version:version});if(error)throw error}
  async cancel(version:number){const{error}=await this.client.rpc("cancel_subscription",{p_workspace_id:this.workspaceId,p_expected_version:version});if(error)throw error}
  async reactivate(version:number){const{error}=await this.client.rpc("reactivate_subscription",{p_workspace_id:this.workspaceId,p_expected_version:version});if(error)throw error}
}
