"use client";
import { Check, Laptop, Moon, Sun } from "lucide-react";
import type { VdsThemeMode } from "./contracts";
import { useVdsTheme } from "./ThemeProvider";
const choices: readonly { mode: Extract<VdsThemeMode, "dark" | "light" | "system">; label: string; description: string; icon: typeof Moon }[] = [
  { mode: "dark", label: "Dark", description: "Vayon’s focused low-light appearance.", icon: Moon },
  { mode: "light", label: "Light", description: "A premium warm-neutral daytime palette.", icon: Sun },
  { mode: "system", label: "System", description: "Automatically follow this device.", icon: Laptop },
];
export function AppearanceSettings() { const { mode, resolved, setMode } = useVdsTheme(); return <div><div role="radiogroup" aria-label="Theme preference" className="grid gap-4 md:grid-cols-3">{choices.map(choice => { const Icon = choice.icon, selected = mode === choice.mode; return <button key={choice.mode} type="button" role="radio" aria-checked={selected} onClick={() => setMode(choice.mode)} className={`vds-focus vds-card-motion rounded-2xl border p-5 text-left ${selected ? "border-[var(--vds-color-primary)] bg-[color-mix(in_srgb,var(--vds-color-primary)_8%,transparent)]" : "border-[var(--vds-color-border)] bg-[var(--vds-color-surface)] hover:border-[var(--vds-color-border-strong)]"}`}><div className="flex items-center"><span className="grid size-10 place-items-center rounded-xl bg-[var(--vds-color-elevated)] text-[var(--vds-color-primary)]"><Icon className="size-5" aria-hidden="true"/></span>{selected && <Check className="ml-auto size-4 text-[var(--vds-color-success)]" aria-hidden="true"/>}</div><h2 className="mt-5 font-semibold text-[var(--vds-color-foreground)]">{choice.label}</h2><p className="mt-2 text-sm leading-6 text-[var(--vds-color-muted)]">{choice.description}</p></button> })}</div><p role="status" className="mt-5 text-sm text-[var(--vds-color-muted)]">Active appearance: <span className="font-medium capitalize text-[var(--vds-color-foreground)]">{resolved}</span>{mode === "system" ? " (following system preference)" : ""}.</p><p className="mt-2 text-xs text-[var(--vds-color-subtle)]">Saved only in this browser. No workspace or database setting is changed.</p></div> }
