"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, useSyncExternalStore, type ReactNode } from "react";
import { VDS_THEME_STORAGE_KEY, type VdsCustomTheme, type VdsResolvedTheme, type VdsThemeContextValue, type VdsThemeMode } from "./contracts";
const themeEvent = "vds-theme-change";
export const ThemeContext = createContext<VdsThemeContextValue | undefined>(undefined), media = "(prefers-color-scheme: dark)";
function subscribe(callback: () => void) { const query = window.matchMedia(media); query.addEventListener("change", callback); return () => query.removeEventListener("change", callback) }
function systemSnapshot() { return window.matchMedia(media).matches }
function isMode(value: string | null): value is VdsThemeMode { return value === "dark" || value === "light" || value === "system" || value === "custom" }
function subscribeMode(callback: () => void) { window.addEventListener("storage", callback); window.addEventListener(themeEvent, callback); return () => { window.removeEventListener("storage", callback); window.removeEventListener(themeEvent, callback) } }
function readMode() { const value = window.localStorage.getItem(VDS_THEME_STORAGE_KEY); return isMode(value) ? value : "dark" }
export function VdsThemeProvider({ children, defaultMode = "dark" }: { readonly children: ReactNode; readonly defaultMode?: VdsThemeMode }) { const mode = useSyncExternalStore(subscribeMode, readMode, () => defaultMode), [custom, setCustomTheme] = useState<VdsCustomTheme>(); const systemDark = useSyncExternalStore(subscribe, systemSnapshot, () => true); const resolved: VdsResolvedTheme = mode === "custom" ? custom?.base ?? "dark" : mode === "system" ? systemDark ? "dark" : "light" : mode; const setMode = useCallback((next: VdsThemeMode) => { try { window.localStorage.setItem(VDS_THEME_STORAGE_KEY, next) } catch { /* Browser storage may be unavailable. */ } window.dispatchEvent(new Event(themeEvent)) }, []); useEffect(() => { const root = document.documentElement; root.dataset.vdsTheme = resolved; root.style.colorScheme = resolved; const variables = custom?.variables ?? {}; Object.entries(variables).forEach(([key, value]) => root.style.setProperty(key, value)); requestAnimationFrame(() => root.classList.add("vds-theme-ready")); return () => Object.keys(variables).forEach(key => root.style.removeProperty(key)) }, [custom, resolved]); const value = useMemo(() => ({ mode, resolved, custom, setMode, setCustomTheme }), [custom, mode, resolved, setMode]); return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider> }
export function useVdsTheme() { const value = useContext(ThemeContext); if (!value) throw new Error("useVdsTheme must be used inside VdsThemeProvider."); return value }
