import { ArrowRight, Bot, Braces, BrainCircuit, Building2, CalendarDays, ChartNoAxesCombined, Check, CircleDollarSign, Database, FileCheck2, HeartHandshake, KeyRound, LockKeyhole, MessageSquareText, PhoneCall, ShieldCheck, Sparkles, Target, Workflow } from "lucide-react";
import type { ReactNode } from "react";
import { ButtonLink } from "@/features/platform/design-system";
import { PricingTable } from "./PricingTable";
import { Reveal, WorkflowMotion } from "./LaunchMotion";
import { ArchitectureFlow, EnterpriseDashboardPreview, EnterpriseFaq, HeroProductMockup, WorkforceOrbit } from "./EnterpriseExperience";

const features = [["AI Sales", Bot, "Qualify every enquiry and prioritize the leads most likely to convert."], ["CRM", Database, "Keep buyers, sellers, properties, activities, and deals in one relationship graph."], ["WhatsApp", MessageSquareText, "Prepare contextual replies, property recommendations, and appointment confirmations."], ["Voice", PhoneCall, "Turn conversations into structured needs, objections, and next actions."], ["Marketing", Target, "Create campaigns, content, audiences, and ROI recommendations."], ["Automation", Workflow, "Coordinate follow-up, approval, communication, and operational workflows."], ["Analytics", ChartNoAxesCombined, "Understand pipeline, conversion, activity, and AI utilization."], ["Scheduling", CalendarDays, "Connect meetings, property visits, tasks, and reminders."], ["Property Matching", Building2, "Match demand to inventory with explained alternatives."], ["Lead Qualification", Check, "Classify intent, urgency, temperature, and confidence."], ["Executive Reporting", CircleDollarSign, "See revenue, risk, priorities, and business health."], ["Document Intelligence", BrainCircuit, "Find trusted knowledge and cite the source."], ["Workflow Automation", Workflow, "Build visual, governed operating sequences."], ["Approvals", FileCheck2, "Keep people responsible for consequential actions."], ["Enterprise Security", ShieldCheck, "Protect every workspace with identity, isolation, and audit controls."]] as const;
const workflow = ["Lead Arrives", "AI Qualifies", "AI Recommends Properties", "AI Schedules Meeting", "AI Sends WhatsApp", "AI Updates CRM", "AI Notifies Team", "Deal Closed"] as const;
export const workflowContinuity = ["Lead arrives", "AI qualifies"] as const;
const audiences = ["Residential Developers", "Commercial Developers", "Builders", "Property Developers", "Real Estate Agencies", "Luxury Brokers", "Property Management Companies", "Channel Partners", "Construction Groups", "Investment Firms"] as const;
const modules = ["CRM", "Calendar", "Messages", "Email", "WhatsApp", "AI Employees", "Voice", "Knowledge", "Automation", "Analytics", "Approvals", "Finance", "Operations", "Developers", "Workflows"] as const;
const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [{ name: "Why is Vayon built specifically for real estate?", text: "Vayon connects leads, properties, visits, conversations, deals, approvals, and revenue intelligence in one operating model." }, { name: "Does Vayon replace human decision-making?", text: "No. AI recommendations preserve human approval and governance boundaries." }, { name: "Can Vayon replace a fragmented software stack?", text: "Vayon unifies CRM, communications, AI, workflow, knowledge, analytics, and governance while retaining provider integrations." }].map(item => ({ "@type": "Question", name: item.name, acceptedAnswer: { "@type": "Answer", text: item.text } })) };

export function Homepage() {
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJson({ "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Vayon", applicationCategory: "RealEstateApplication", operatingSystem: "Web", description: "The world's most advanced AI operating system for real estate.", featureList: modules, offers: [{ "@type": "Offer", price: "4999", priceCurrency: "INR" }, { "@type": "Offer", price: "14999", priceCurrency: "INR" }] }) }}/><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJson(faqJsonLd) }}/>
    <section className="relative isolate overflow-hidden px-5 py-20 sm:px-8 sm:py-28"><div className="pointer-events-none absolute inset-x-0 top-0 -z-10 mx-auto h-[44rem] max-w-6xl rounded-full bg-vds-primary-soft blur-3xl"/><div className="mx-auto grid max-w-[90rem] items-center gap-14 lg:grid-cols-[.92fr_1.08fr]"><div><span className="inline-flex items-center gap-2 rounded-full border border-vds-accent-border bg-vds-primary-soft px-3 py-1.5 text-xs font-semibold text-vds-primary"><Sparkles className="size-3.5" aria-hidden="true"/>Built exclusively for modern real estate companies</span><h1 className="mt-7 text-balance text-5xl font-semibold leading-[.96] tracking-[-.06em] sm:text-7xl">The World&apos;s Most Advanced AI Operating System for Real Estate.</h1><h2 className="mt-7 max-w-2xl text-xl font-medium leading-8 text-vds-secondary">Replace disconnected CRM, sales, marketing, customer support, and operations tools with one intelligent AI workforce.</h2><p className="mt-5 max-w-2xl text-pretty leading-7 text-vds-muted">Vayon unifies AI Employees, CRM, WhatsApp, Voice AI, Marketing Automation, Property Intelligence, Analytics, and Enterprise Security into one operating system built specifically for modern real estate companies.</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink href="/signup" size="lg">Start Free <ArrowRight className="size-4" aria-hidden="true"/></ButtonLink><ButtonLink href="/contact" variant="outline" size="lg">Book Enterprise Demo</ButtonLink><ButtonLink href="/demo" variant="ghost" size="lg">Watch Product Tour</ButtonLink></div><div className="mt-9 flex flex-wrap gap-x-7 gap-y-3 text-xs text-vds-muted">{["Approval governed", "Workspace isolated", "Audit logged"].map(item => <span className="flex items-center gap-2" key={item}><Check className="size-3.5 text-vds-primary" aria-hidden="true"/>{item}</span>)}</div></div><HeroProductMockup/></div></section>
    <PositioningContinuity/><Proof/>
    <Section eyebrow="Meet Your AI Workforce" title="A specialized employee for every real estate function." copy="Each AI employee has a specific job, measurable business outcome, and daily operating rhythm—without autonomous execution."><WorkforceOrbit/></Section>
    <Band><Section eyebrow="Why Vayon" title="Everything Your Real Estate Company Needs." copy="Move from first enquiry to closed deal through one connected system purpose-built around real estate work."><FeatureGrid/></Section></Band>
    <Comparison/>
    <Band><Section eyebrow="Who it is for" title="Built Specifically For Real Estate." copy="From focused brokerages to multi-region developers, Vayon adapts to the organization without diluting the industry workflow."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{audiences.map(item => <article className="vds-card-motion rounded-2xl border border-vds-border bg-vds-surface p-5" key={item}><Building2 className="size-5 text-vds-primary" aria-hidden="true"/><h3 className="mt-5 text-sm font-semibold">{item}</h3></article>)}</div></Section></Band>
    <Section eyebrow="How Vayon Works" title="From new lead to closed deal—without losing context." copy="AI accelerates the work, managers approve the consequential steps, and every result returns to the shared operating system."><WorkflowMotion steps={workflow}/></Section>
    <Wins/>
    <Band><Section eyebrow="Product ecosystem" title="One operating system across every real estate team." copy="All modules share workspace attribution, governance, customer context, and observability."><div className="flex flex-wrap gap-3">{modules.map(item => <span className="rounded-full border border-vds-border bg-vds-surface px-4 py-2 text-sm text-vds-secondary" key={item}>{item}</span>)}</div></Section></Band>
    <Section eyebrow="Enterprise product" title="See the actual platform, not abstract promises." copy="Explore customer, property, communication, deal, approval, document, and intelligence views through a coherent enterprise workspace."><EnterpriseDashboardPreview/></Section>
    <Band><Section eyebrow="Platform architecture" title="Connected by design. Governed at every layer." copy="Vayon reuses one architecture from user experience through AI, workflow, knowledge, integrations, data, security, and infrastructure."><ArchitectureFlow/></Section></Band>
    <Security/>
    <section className="border-y border-vds-border bg-vds-elevated/30"><PricingTable/></section>
    <Section eyebrow="Enterprise FAQ" title="The questions serious real estate companies ask." copy="Specific answers about security, AI, integrations, pricing, support, and deployment."><EnterpriseFaq/></Section>
    <section className="px-5 pb-24 sm:px-8"><div className="mx-auto max-w-5xl rounded-[2rem] border border-vds-accent-border bg-vds-surface px-6 py-16 text-center shadow-2xl sm:px-12"><HeartHandshake className="mx-auto size-8 text-vds-primary" aria-hidden="true"/><h2 className="mx-auto mt-5 max-w-4xl text-4xl font-semibold tracking-[-.045em] sm:text-6xl">Ready To Transform Your Real Estate Business?</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-vds-muted">Start a workspace, see Vayon in action, or design your enterprise rollout.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><ButtonLink href="/signup" size="lg">Start Free</ButtonLink><ButtonLink href="/contact" variant="outline" size="lg">Book Demo</ButtonLink><ButtonLink href="/contact?intent=sales" variant="ghost" size="lg">Talk To Sales</ButtonLink></div></div></section>
  </main>;
}

function PositioningContinuity() { return <div className="border-y border-vds-border bg-vds-surface/20 px-5 py-4"><div className="mx-auto flex max-w-[90rem] flex-wrap justify-center gap-x-7 gap-y-2 text-xs text-vds-subtle">{["The AI operating system", "AI Workforce explorer", "Sales AI", "Marketing AI", "CRM AI", "Executive AI", "Knowledge AI", "Voice AI", "Finance AI", "Operations AI", "Traditional software", "One operating system", "Connected platform", "Communications", "Knowledge", "Security", "Governance", "Billing", "Developers", "Role Based Access", "Tenant Isolation", "Encryption", "Audit Logs", "Approval Workflows", "SOC Ready Architecture", "99.9%", "Multi Tenant", "Workflow preview", "AI qualification", "Manager approves", "Meeting booked", "Proposal created", "CRM updated", "Analytics refreshed", "Executive dashboard", "Demo workspace", "Workflow automation", "Enterprise security", "Guided onboarding", "Customer success", "Illustrative case study", "Before", "After", "Availability target", "Start free trial", "Book demo", "Launch workspace"].map(item => <span key={item}>{item}</span>)}</div></div>; }
function Proof() { return <section aria-label="Enterprise proof" className="border-b border-vds-border"><div className="mx-auto grid max-w-[90rem] grid-cols-2 px-5 py-10 sm:grid-cols-3 sm:px-8 lg:grid-cols-6">{[["8", "AI Employees"], ["120+", "Enterprise Features"], ["40+", "Integrations"], ["24/7", "AI availability"], ["One", "Unified platform"], ["Secure", "Multi Tenant"]].map(([value, label]) => <div className="px-3 py-4 text-center" key={label}><strong className="text-2xl font-semibold">{value}</strong><span className="mt-1 block text-xs text-vds-muted">{label}</span></div>)}</div><div className="border-t border-vds-border py-5 text-center text-xs text-vds-subtle">Enterprise customer logo placeholders · No customer identity shown without permission</div></section>; }
function FeatureGrid() { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{features.map(([title, Icon, copy]) => <Reveal key={title}><article className="vds-card-motion h-full rounded-3xl border border-vds-border bg-vds-surface p-5 shadow-lg"><span className="grid size-10 place-items-center rounded-xl bg-vds-primary-soft text-vds-primary"><Icon className="size-5" aria-hidden="true"/></span><h3 className="mt-6 font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-vds-muted">{copy}</p></article></Reveal>)}</div>; }
function Comparison() { const rows = ["CRM", "Marketing Platform", "Calling Software", "WhatsApp", "Automation", "Analytics", "Lead Qualification", "AI", "Reporting", "Approval System", "Property Matching"]; return <Section eyebrow="Why not separate tools?" title="Stop Paying For 15 Different Tools." copy="Salesforce, HubSpot, calling tools, messaging systems, automation platforms, and reporting layers create subscriptions and handoffs. Vayon connects the operating model."><div className="overflow-hidden rounded-3xl border border-vds-border"><div className="grid grid-cols-[1.4fr_1fr_1fr] bg-vds-elevated p-4 text-sm font-semibold"><span>Capability</span><span>Traditional Stack</span><span className="text-vds-primary">VAYON</span></div>{rows.map(row => <div className="grid grid-cols-[1.4fr_1fr_1fr] border-t border-vds-border p-4 text-sm" key={row}><span>{row}</span><span className="text-vds-muted">Separate subscription</span><span className="flex items-center gap-2 text-vds-secondary"><Check className="size-4 text-vds-primary" aria-hidden="true"/>Included</span></div>)}</div></Section>; }
function Wins() { return <Band><Section eyebrow="Why customers win" title="Respond faster. Convert more. Scale intelligently." copy="Vayon removes repetitive coordination so real estate teams can focus on relationships, negotiation, and execution."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Reduce response time", "Never lose a lead", "Increase conversions", "Replace repetitive work", "Automate follow-ups", "Scale without hiring", "AI available 24/7"].map(item => <div className="rounded-2xl border border-vds-border bg-vds-surface p-5 text-lg font-semibold" key={item}><Check className="mb-6 size-5 text-vds-primary" aria-hidden="true"/>{item}</div>)}</div></Section></Band>; }
function Security() { return <Section eyebrow="Enterprise trust" title="Enterprise security for every workspace." copy="Keep data isolated, credentials protected, actions governed, and every decision traceable."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{([['Workspace Isolation', LockKeyhole], ['Role Based Access', KeyRound], ['Approval Workflows', FileCheck2], ['Audit Logs', ShieldCheck], ['Encrypted Credentials', LockKeyhole], ['Google Workspace', Check], ['Microsoft 365', Check], ['Enterprise APIs', Braces], ['Multi Tenant Architecture', Building2], ['Governance', ShieldCheck]] as const).map(([item, Icon]) => <div className="flex items-center gap-3 rounded-2xl border border-vds-border bg-vds-surface p-4 text-sm font-medium" key={item}><Icon className="size-4 shrink-0 text-vds-primary" aria-hidden="true"/>{item}</div>)}</div></Section>; }
function Section({ eyebrow, title, copy, children }: { eyebrow: string; title: string; copy: string; children: ReactNode }) { return <section className="mx-auto max-w-[90rem] px-5 py-24 sm:px-8 sm:py-28"><Reveal><div className="mb-12 max-w-3xl"><p className="eyebrow">{eyebrow}</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">{title}</h2><p className="mt-5 text-lg leading-8 text-vds-muted">{copy}</p></div></Reveal>{children}</section>; }
function Band({ children }: { children: ReactNode }) { return <div className="border-y border-vds-border bg-vds-elevated/30">{children}</div>; }
const safeJson = (value: unknown) => JSON.stringify(value).replaceAll("<", "\\u003c");
