export { auroraRealtyGroup } from "./config/aurora-realty-group";
export { getAuroraNavigationContext } from "./services/navigation-context";
export type * from "./domain/contracts";
export { auroraEmployees } from "./people/employees";
export { auroraOrganizationChart, AuroraOrganizationChart } from "./people/organization-chart";
export type * from "./people/contracts";
export { auroraCompanies } from "./crm-network/companies";
export { auroraContacts } from "./crm-network/contacts";
export { auroraCrmNetwork, AuroraCrmNetwork } from "./crm-network/network.service";
export type * from "./crm-network/contracts";
export { auroraProperties } from "./property-portfolio/properties";
export { auroraPropertyPortfolio, AuroraPropertyPortfolio } from "./property-portfolio/portfolio.service";
export { auroraPropertyContextRegistry, AuroraPropertyContextRegistry } from "./property-portfolio/context.registry";
export type * from "./property-portfolio/contracts";
export { auroraLeads,auroraDeals,auroraTasks,auroraMeetings,auroraDocuments,auroraCalendarEvents } from "./sales-operations/records";
export { auroraSalesOperations,AuroraSalesOperations } from "./sales-operations/sales-operations.service";
export { auroraSalesContextRegistry,AuroraSalesContextRegistry } from "./sales-operations/context.registry";
export type * from "./sales-operations/contracts";
export { auroraCampaigns,auroraCommunications } from "./business-activity/records";
export { auroraTimelineHistory } from "./business-activity/timeline.history";
export { auroraBusinessActivity,AuroraBusinessActivity } from "./business-activity/activity.service";
export { auroraActivityContextRegistry,AuroraActivityContextRegistry } from "./business-activity/context.registry";
export type * from "./business-activity/contracts";
export { auroraExecutiveIntelligence,AuroraExecutiveIntelligence } from "./executive-intelligence/executive-intelligence.service";
export type * from "./executive-intelligence/contracts";
