import type { CampaignService, ContentStudio, GrowthObjectiveService, LandingPageService, MarketingAnalyticsProvider, MarketingCalendarService, MarketingFormService, PublishingCenter, QRCodeService, ReferralService, SocialAccountRegistry } from "../contracts/ports";
import type { Campaign, ContentAsset, GrowthObjective, LandingPage, MarketingCalendarItem, MarketingForm, PublishingJob, QRCodeDefinition, ReferralProgram, SocialAccount } from "../domain/contracts";
export class InMemorySocialAccountRegistry implements SocialAccountRegistry { private values: SocialAccount[] = []; register(value: SocialAccount) { this.values = [...this.values.filter(item => item.id !== value.id), { ...value, oauthAvailable: false }] } list(workspaceId?: string) { return workspaceId ? this.values.filter(item => item.workspaceId === workspaceId) : this.values } }
export class InMemoryCampaignService implements CampaignService { private values: Campaign[] = []; list() { return this.values } save(value: Campaign) { this.values = [...this.values.filter(item => item.id !== value.id), value] } }
export class InMemoryContentStudio implements ContentStudio { private values: ContentAsset[] = []; list() { return this.values } save(value: ContentAsset) { this.values = [...this.values.filter(item => item.id !== value.id), { ...value, generationStatus: "unavailable" }] } }
export class ArchitecturePublishingCenter implements PublishingCenter { private jobs: PublishingJob[] = []; validate(job: PublishingJob) { const errors = [...(!job.contentId ? ["Content is required."] : []), ...(job.accountIds.length === 0 ? ["At least one account is required."] : []), ...(job.approvalRequired && job.approvalStatus !== "approved" ? ["Publishing approval is required."] : [])]; return { valid: errors.length === 0, errors, warnings: ["External publishing is unavailable."], previewAvailable: true } } queue(job: PublishingJob) { const validation = this.validate(job), blocked = { ...job, validation, status: "blocked" as const, executable: false as const }; this.jobs = [...this.jobs, blocked]; return blocked } history() { return this.jobs } }
export class InMemoryMarketingCalendar implements MarketingCalendarService { constructor(private values: readonly MarketingCalendarItem[] = []) {} list(_view: "month" | "week" | "day", range?: { from: string; to: string }) { return range ? this.values.filter(item => item.startsAt >= range.from && item.startsAt <= range.to) : this.values } }
export class InMemoryLandingPageService implements LandingPageService { private values: LandingPage[] = []; list() { return this.values } save(value: LandingPage) { this.values = [...this.values.filter(item => item.id !== value.id), value] } }
export class InMemoryMarketingFormService implements MarketingFormService { private values: MarketingForm[] = []; list() { return this.values } validate(form: MarketingForm, values: Readonly<Record<string, unknown>>) { return form.fields.flatMap(field => field.required && (values[field.key] === undefined || values[field.key] === "") ? [`${field.label} is required.`] : []) } }
export class InMemoryReferralService implements ReferralService { private values: ReferralProgram[] = []; list() { return this.values } save(value: ReferralProgram) { this.values = [...this.values.filter(item => item.id !== value.id), { ...value, payoutStatus: "unavailable" }] } }
export class InMemoryQRCodeService implements QRCodeService { private values: QRCodeDefinition[] = []; list() { return this.values } save(value: QRCodeDefinition) { this.values = [...this.values.filter(item => item.id !== value.id), { ...value, imageStatus: "placeholder", trackingStatus: "placeholder" }] } }
export class PlaceholderMarketingAnalytics implements MarketingAnalyticsProvider { async query() { return { values: {}, status: "placeholder" as const, sources: [] } } }
export class InMemoryGrowthObjectiveService implements GrowthObjectiveService { private values: GrowthObjective[] = []; list() { return this.values } save(value: GrowthObjective) { this.values = [...this.values.filter(item => item.id !== value.id), value] } }
