import "server-only";
import OpenAI from"openai";
import { OpenAIProvider as PlatformOpenAIProvider } from "@/features/platform/openai/providers/openai.provider";
import { aiOutputSchema } from "../validation/output";
import type {
  AIGenerationRequest,
  AIGenerationResult,
  AIProvider,
} from "./types";

export interface OpenAIProviderOptions {
  apiKey?: string;
  model?: string;
  client?: Pick<OpenAI, "responses">;
}

// The platform provider owns responses.parse and zodTextFormat structured output handling.
export class OpenAIProvider implements AIProvider {
  readonly id = "openai";
  private readonly provider: PlatformOpenAIProvider;
  private readonly model: string;

  constructor(options: OpenAIProviderOptions = {}) {
    const apiKey = options.apiKey ?? process.env.OPENAI_API_KEY;
    if (!options.client && !apiKey)
      throw new Error("OPENAI_API_KEY is required when the OpenAI provider is enabled.");
    this.model = options.model ?? process.env.OPENAI_MODEL ?? "gpt-5";
    const sharedClient = options.client ?? new OpenAI({ apiKey });
    this.provider = new PlatformOpenAIProvider(
      sharedClient as ConstructorParameters<typeof PlatformOpenAIProvider>[0],
    );
  }

  generateText(request: AIGenerationRequest) {
    return this.generateStructured(request);
  }

  async generateStructured(
    request: AIGenerationRequest,
  ): Promise<AIGenerationResult> {
    const response = await this.provider.responses({
      system: request.system,
      prompt: request.prompt,
      workspaceId: request.metadata.workspaceId,
      employee: employeeCode(request.metadata.employeeCode),
      model: this.model,
    });
    const output = aiOutputSchema.parse({
      summary: response.output,
      reasoning: "Generated by the governed OpenAI provider from approved workspace context.",
      confidence: 1,
      referencedCrmRecords: [],
      recommendedActions: [],
      approvalRequired: true,
    });
    return {
      output,
      provider: response.provider,
      model: response.model,
      latencyMs: response.latencyMs,
      inputTokens: response.usage.promptTokens,
      outputTokens: response.usage.completionTokens,
      costEstimate: response.cost.totalUsd,
    };
  }

  async embed(): Promise<never> {
    throw new Error("Use the platform OpenAI embeddings capability.");
  }

  async stream(): Promise<never> {
    throw new Error("Use the platform OpenAI streaming capability.");
  }
}

function employeeCode(value: string) {
  const supported = [
    "sales-ai",
    "crm-ai",
    "marketing-ai",
    "whatsapp-ai",
    "voice-ai",
    "operations-ai",
    "finance-ai",
    "executive-ai",
  ] as const;
  return supported.includes(value as (typeof supported)[number])
    ? (value as (typeof supported)[number])
    : "executive-ai";
}
