import Image from "next/image";
import { Building2, Globe2, Mail, MapPin, Phone, UsersRound } from "lucide-react";
import type { AuroraCompany, AuroraContact, RelationshipSummaryModel } from "./contracts";
import { auroraCrmNetwork } from "./network.service";
export function CompanyCard({company}:{readonly company:AuroraCompany}){return <article className="rounded-3xl border border-vds-border bg-vds-surface p-5"><div className="flex items-start gap-4"><Image src={company.logoPlaceholder} width={48} height={48} alt="" className="size-12 rounded-2xl border border-vds-border"/><div className="min-w-0"><h3 className="truncate font-semibold">{company.name}</h3><p className="mt-1 text-xs capitalize text-vds-primary">{company.category.replaceAll("-"," ")}</p></div></div><p className="mt-4 text-sm leading-6 text-vds-muted">{company.description}</p><div className="mt-4 flex items-center gap-2 text-xs text-vds-subtle"><MapPin className="size-4"/>{company.officeCity}<span>·</span><span className="capitalize">{company.relationshipStatus}</span></div></article>}
export function ContactCard({contact}:{readonly contact:AuroraContact}){const company=auroraCrmNetwork.company(contact.companyId);return <article className="rounded-3xl border border-vds-border bg-vds-surface p-5"><div className="flex gap-4"><Image src={contact.avatarPlaceholder} width={48} height={48} alt="" className="size-12 rounded-2xl border border-vds-border"/><div className="min-w-0"><h3 className="truncate font-semibold">{contact.name}</h3><p className="mt-1 text-xs text-vds-primary">{contact.title}</p><p className="mt-1 truncate text-xs text-vds-muted">{company?.name}</p></div></div><p className="mt-4 text-xs capitalize text-vds-subtle">{contact.relationshipRole.replaceAll("-"," ")} · {contact.city}</p></article>}
export function CompanyProfile({company}:{readonly company:AuroraCompany}){const summary=auroraCrmNetwork.relationships(company.id);return <section className="space-y-5"><CompanyCard company={company}/><div className="grid gap-3 rounded-3xl border border-vds-border bg-vds-surface p-5 text-sm sm:grid-cols-2"><Item icon={Globe2} label="Website" value={company.website}/><Item icon={Building2} label="Industry" value={company.industry}/><Item icon={MapPin} label="Office" value={company.officeCity}/><Item icon={UsersRound} label="Contacts" value={String(summary.contacts.length)}/></div><RelationshipSummary summary={summary}/></section>}
export function ContactProfile({contact}:{readonly contact:AuroraContact}){const company=auroraCrmNetwork.company(contact.companyId);return <section className="space-y-5"><ContactCard contact={contact}/><div className="grid gap-3 rounded-3xl border border-vds-border bg-vds-surface p-5 text-sm sm:grid-cols-2"><Item icon={Building2} label="Company" value={company?.name??"Unavailable"}/><Item icon={Mail} label="Email" value={contact.email}/><Item icon={Phone} label="Phone" value={contact.phone}/><Item icon={MapPin} label="City" value={contact.city}/></div><p className="rounded-2xl border border-dashed border-vds-border p-4 text-sm text-vds-muted">{contact.notesPlaceholder}</p></section>}
export function RelationshipSummary({summary}:{readonly summary:RelationshipSummaryModel}){const rows=[["Primary",[summary.primaryContact]],["Decision makers",summary.decisionMakers],["Influencers",summary.influencers],["Legal",summary.legalContacts],["Finance",summary.financeContacts],["Technical",summary.technicalContacts]] as const;return <section className="rounded-3xl border border-vds-border bg-vds-surface p-5" aria-label="Company relationship summary"><h2 className="font-semibold">Relationship summary</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{rows.map(([label,contacts])=><div key={label} className="rounded-2xl bg-vds-elevated p-3"><p className="text-[10px] uppercase tracking-wide text-vds-subtle">{label}</p><p className="mt-2 text-sm text-vds-secondary">{contacts.map(item=>item.name).join(", ")||"No assigned contact"}</p></div>)}</div></section>}
function Item({icon:Icon,label,value}:{readonly icon:typeof Globe2;readonly label:string;readonly value:string}){return <div className="flex items-center gap-3"><Icon className="size-4 text-vds-primary"/><span><span className="block text-xs text-vds-subtle">{label}</span><span className="mt-1 block text-vds-secondary">{value}</span></span></div>}
