import type { AuroraCompany, AuroraCompanyId, CompanyCategory, RelationshipStatus } from "./contracts";
import type { AuroraBusinessUnitId } from "../people/contracts";
type Input=readonly[string,CompanyCategory,string,string,readonly AuroraBusinessUnitId[],RelationshipStatus,string,readonly string[]];
const data:readonly Input[]=[
["Skyline Developers","developer","Real Estate Development","Bengaluru",["residential","luxury"],"strategic","development-partner",["urban","residential"]],["Prestige Urban Projects","developer","Urban Development","Mumbai",["residential","commercial"],"active","development-partner",["mixed-use","urban"]],["CedarField Developments","developer","Land Development","Hyderabad",["land","residential"],"developing","development-partner",["land","planning"]],
["Grand Oak Infrastructure","builder","Infrastructure and Building","Pune",["commercial","land"],"preferred","delivery-partner",["infrastructure","commercial"]],["Horizon Buildworks","builder","Residential Construction","Bengaluru",["residential"],"active","delivery-partner",["housing","construction"]],["Stonebridge Builders","builder","Premium Construction","Mumbai",["luxury","residential"],"strategic","delivery-partner",["premium","construction"]],
["BlueStone Capital","investor","Real Estate Investment","Mumbai",["investment","commercial"],"strategic","capital-partner",["private-equity","commercial"]],["NorthStar Holdings","investor","Investment Holding","Delhi",["investment","land"],"active","capital-partner",["holdings","land"]],["Emerald Asset Management","investor","Asset Management","Bengaluru",["investment","commercial"],"preferred","capital-partner",["assets","portfolio"]],["Summit Property Ventures","investor","Property Investment","Hyderabad",["investment","residential"],"developing","capital-partner",["ventures","residential"]],
["Meridian Commerce Bank","bank","Banking","Mumbai",["investment","commercial"],"strategic","lending-partner",["lending","institutional"]],["Harbor Trust Bank","bank","Banking","Chennai",["residential","investment"],"preferred","lending-partner",["mortgage","retail"]],["Crescent Cooperative Bank","bank","Cooperative Banking","Pune",["residential","rentals"],"active","lending-partner",["local","mortgage"]],
["Veritas Property Law","law-firm","Legal Services","Bengaluru",["residential","commercial"],"preferred","legal-advisor",["contracts","property-law"]],["Oak & Vale Legal","law-firm","Legal Services","Mumbai",["luxury","investment"],"strategic","legal-advisor",["transactions","compliance"]],["JurisStone Partners","law-firm","Legal Services","Delhi",["land","commercial"],"active","legal-advisor",["land-law","due-diligence"]],
["Canvas & Hearth Interiors","interior-designer","Interior Design","Bengaluru",["residential","luxury"],"preferred","design-partner",["interiors","residential"]],["Lumen Space Studio","interior-designer","Interior Design","Mumbai",["luxury","commercial"],"active","design-partner",["workplace","luxury"]],["UrbanWeave Design House","interior-designer","Interior Design","Hyderabad",["residential","commercial"],"developing","design-partner",["design","fit-out"]],
["Axis Habitat Architects","architect","Architecture","Bengaluru",["residential","land"],"strategic","design-partner",["architecture","planning"]],["Formline Collaborative","architect","Architecture","Pune",["commercial","luxury"],"preferred","design-partner",["commercial","sustainable"]],["Studio North Arc","architect","Architecture","Delhi",["residential","commercial"],"active","design-partner",["urban-design","architecture"]],
["Ironwood Construction","construction-company","Construction","Hyderabad",["commercial","land"],"active","construction-partner",["engineering","delivery"]],["CivicSpan Engineering","construction-company","Civil Engineering","Bengaluru",["commercial","land"],"strategic","construction-partner",["civil","infrastructure"]],["TerraCore Projects","construction-company","Construction","Chennai",["residential","commercial"],"preferred","construction-partner",["projects","quality"]],
["Vertex Commercial","corporate-client","Business Services","Mumbai",["commercial","rentals"],"strategic","corporate-client",["office","leasing"]],["Nimbus Technologies","corporate-client","Technology","Bengaluru",["commercial","rentals"],"active","corporate-client",["technology","workspace"]],["Arbor Health Systems","corporate-client","Healthcare","Hyderabad",["commercial","land"],"developing","corporate-client",["healthcare","expansion"]],["Solstice Retail Group","corporate-client","Retail","Delhi",["commercial","rentals"],"preferred","corporate-client",["retail","leasing"]],
["Silverline Realty Partners","channel-partner","Real Estate Services","Pune",["residential","investment"],"strategic","channel-partner",["referrals","brokerage"]],["UrbanNest Living","channel-partner","Residential Services","Bengaluru",["residential","rentals"],"active","channel-partner",["housing","referrals"]],["KeyStone Referral Network","channel-partner","Real Estate Network","Mumbai",["luxury","investment"],"preferred","channel-partner",["network","luxury"]],["MetroLink Realty Alliance","channel-partner","Real Estate Network","Chennai",["commercial","residential"],"developing","channel-partner",["regional","brokerage"]],
["Evergreen Properties","property-management","Property Management","Bengaluru",["residential","rentals"],"strategic","management-partner",["managed-homes","tenant-care"]],["CrownGate Estate Services","property-management","Property Management","Mumbai",["luxury","rentals"],"preferred","management-partner",["luxury","facilities"]],["Parkview Asset Services","property-management","Asset Services","Hyderabad",["commercial","investment"],"active","management-partner",["facilities","assets"]],
];
const slug=(value:string)=>value.toLocaleLowerCase().replaceAll("&","and").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
export const companyId=(name:string)=>`aurora-company-${slug(name)}` as AuroraCompanyId;
export const auroraCompanies=Object.freeze(data.map(([name,category,industry,officeCity,businessUnitIds,relationshipStatus,relationshipType,tags])=>{const id=companyId(name),companySlug=slug(name);return Object.freeze({id,name,category,industry,description:`${name} is a fictional ${industry.toLocaleLowerCase()} organization in Aurora Realty Group's demo CRM network.`,officeCity,website:`https://${companySlug}.example`,primaryContactId:`aurora-contact-${companySlug}-1` as const,businessUnitIds,relationshipStatus,relationshipType,tags,logoPlaceholder:"/vayon/demo/crm/company-placeholder.svg",identity:{namespace:"aurora-demo-crm" as const,objectType:"company" as const,objectId:id,timelineEligible:true as const,events:Object.freeze([])}})})) satisfies readonly AuroraCompany[];
