import type { AuroraBusinessUnitId } from "../people/contracts";
export type AuroraCompanyId=`aurora-company-${string}`;export type AuroraContactId=`aurora-contact-${string}`;
export type CompanyCategory="developer"|"builder"|"investor"|"bank"|"law-firm"|"interior-designer"|"architect"|"construction-company"|"corporate-client"|"channel-partner"|"property-management";
export type RelationshipStatus="strategic"|"active"|"developing"|"preferred";
export type ContactRelationshipRole="decision-maker"|"influencer"|"legal-contact"|"finance-contact"|"technical-contact";
export interface CrmObjectIdentity {readonly namespace:"aurora-demo-crm";readonly objectType:"company"|"contact";readonly objectId:string;readonly timelineEligible:true;readonly events:readonly never[]}
export interface AuroraCompany {readonly id:AuroraCompanyId;readonly name:string;readonly category:CompanyCategory;readonly industry:string;readonly description:string;readonly officeCity:string;readonly website:string;readonly primaryContactId:AuroraContactId;readonly businessUnitIds:readonly AuroraBusinessUnitId[];readonly relationshipStatus:RelationshipStatus;readonly relationshipType:string;readonly tags:readonly string[];readonly logoPlaceholder:string;readonly identity:CrmObjectIdentity}
export interface AuroraContact {readonly id:AuroraContactId;readonly companyId:AuroraCompanyId;readonly name:string;readonly title:string;readonly email:string;readonly phone:string;readonly city:string;readonly department:string;readonly businessUnitIds:readonly AuroraBusinessUnitId[];readonly preferredLanguage:string;readonly relationshipType:string;readonly relationshipRole:ContactRelationshipRole;readonly isPrimary:boolean;readonly tags:readonly string[];readonly notesPlaceholder:"No CRM notes recorded.";readonly avatarPlaceholder:string;readonly identity:CrmObjectIdentity}
export interface CrmNetworkFilters {readonly industry?:string;readonly city?:string;readonly relationshipStatus?:RelationshipStatus;readonly businessUnit?:AuroraBusinessUnitId;readonly companyType?:CompanyCategory;readonly contactRole?:ContactRelationshipRole;readonly tags?:readonly string[]}
export interface RelationshipSummaryModel {readonly company:AuroraCompany;readonly contacts:readonly AuroraContact[];readonly primaryContact:AuroraContact;readonly decisionMakers:readonly AuroraContact[];readonly influencers:readonly AuroraContact[];readonly legalContacts:readonly AuroraContact[];readonly financeContacts:readonly AuroraContact[];readonly technicalContacts:readonly AuroraContact[]}
export interface AuroraCrmHomeProjection {readonly topCompanies:readonly AuroraCompany[];readonly strategicPartners:readonly AuroraCompany[];readonly newestContacts:readonly never[];readonly analytics:"none";readonly persistence:"none"}
