import { auroraCompanies } from "./companies";
import { auroraContacts } from "./contacts";
import type { AuroraCompany, AuroraContact, AuroraCrmHomeProjection, CrmNetworkFilters, RelationshipSummaryModel } from "./contracts";
export class AuroraCrmNetwork {
  readonly companies=auroraCompanies;readonly contacts=auroraContacts;
  constructor(){const companyIds=new Set(this.companies.map(item=>item.id)),contactIds=new Set(this.contacts.map(item=>item.id));if(companyIds.size!==this.companies.length)throw new Error("Duplicate Aurora company identity.");if(contactIds.size!==this.contacts.length)throw new Error("Duplicate Aurora contact identity.");for(const contact of this.contacts)if(!companyIds.has(contact.companyId))throw new Error(`Orphan Aurora contact ${contact.id}.`);for(const company of this.companies){const primary=this.contacts.find(contact=>contact.id===company.primaryContactId&&contact.companyId===company.id);if(!primary?.isPrimary)throw new Error(`Invalid primary contact for ${company.id}.`)}}
  company(id:string){return this.companies.find(item=>item.id===id)}contact(id:string){return this.contacts.find(item=>item.id===id)}
  relationships(companyId:string):RelationshipSummaryModel{const company=this.company(companyId);if(!company)throw new Error(`Unknown Aurora company ${companyId}.`);const contacts=this.contacts.filter(item=>item.companyId===company.id),primaryContact=contacts.find(item=>item.id===company.primaryContactId);if(!primaryContact)throw new Error(`Missing primary contact for ${company.id}.`);const role=(value:AuroraContact["relationshipRole"])=>contacts.filter(item=>item.relationshipRole===value);return Object.freeze({company,contacts,primaryContact,decisionMakers:role("decision-maker"),influencers:role("influencer"),legalContacts:role("legal-contact"),financeContacts:role("finance-contact"),technicalContacts:role("technical-contact")})}
  filterCompanies(filters:CrmNetworkFilters):readonly AuroraCompany[]{return this.companies.filter(item=>(!filters.industry||item.industry===filters.industry)&&(!filters.city||item.officeCity===filters.city)&&(!filters.relationshipStatus||item.relationshipStatus===filters.relationshipStatus)&&(!filters.businessUnit||item.businessUnitIds.includes(filters.businessUnit))&&(!filters.companyType||item.category===filters.companyType)&&(!filters.tags?.length||filters.tags.every(tag=>item.tags.includes(tag))))}
  filterContacts(filters:CrmNetworkFilters):readonly AuroraContact[]{return this.contacts.filter(item=>{const company=this.company(item.companyId);return Boolean(company)&&(!filters.industry||company?.industry===filters.industry)&&(!filters.city||item.city===filters.city)&&(!filters.relationshipStatus||company?.relationshipStatus===filters.relationshipStatus)&&(!filters.businessUnit||item.businessUnitIds.includes(filters.businessUnit))&&(!filters.companyType||company?.category===filters.companyType)&&(!filters.contactRole||item.relationshipRole===filters.contactRole)&&(!filters.tags?.length||filters.tags.every(tag=>item.tags.includes(tag))||filters.tags.every(tag=>company?.tags.includes(tag)))})}
  homeProjection():AuroraCrmHomeProjection{return Object.freeze({topCompanies:Object.freeze([]),strategicPartners:Object.freeze(this.companies.filter(item=>item.relationshipStatus==="strategic")),newestContacts:Object.freeze([]),analytics:"none",persistence:"none"})}
}
export const auroraCrmNetwork=new AuroraCrmNetwork();
