import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { GoogleConnectionSummary,TenantSettings,UserProfile } from "../domain/models";

export class IdentityWorkspaceRepository {
  constructor(private readonly client:SupabaseClient,private readonly organizationId:string,private readonly workspaceId:string){}
  async profile(userId:string):Promise<UserProfile>{const{data,error}=await this.client.from("user_profiles").select("user_id,name,email,avatar_url,timezone,language,country,phone,job_title,department,notification_preferences,security_settings,last_login_at,version").eq("user_id",userId).single();if(error)throw error;return{userId:data.user_id,name:data.name,email:data.email,avatarUrl:data.avatar_url,timezone:data.timezone,language:data.language,country:data.country,phone:data.phone,jobTitle:data.job_title,department:data.department,notificationPreferences:data.notification_preferences??{},securitySettings:data.security_settings??{},lastLoginAt:data.last_login_at,version:data.version}}
  async tenant():Promise<TenantSettings>{const[organization,workspace]=await Promise.all([this.client.from("organizations").select("id,name,country,timezone,business_type,company_size,phone,website,industry,logo_path").eq("id",this.organizationId).single(),this.client.from("workspaces").select("id,name").eq("id",this.workspaceId).single()]);if(organization.error)throw organization.error;if(workspace.error)throw workspace.error;return{organizationId:organization.data.id,organizationName:organization.data.name,workspaceId:workspace.data.id,workspaceName:workspace.data.name,country:organization.data.country,timezone:organization.data.timezone,businessType:organization.data.business_type,companySize:organization.data.company_size,phone:organization.data.phone,website:organization.data.website,industry:organization.data.industry,logoPath:organization.data.logo_path}}
  async google():Promise<GoogleConnectionSummary>{const{data,error}=await this.client.rpc("get_google_credential",{p_organization_id:this.organizationId,p_workspace_id:this.workspaceId});if(error)throw error;const row=data?.[0];if(!row)return{status:"disconnected",email:null,scopes:[],expiresAt:null,refreshAvailable:false};const expired=new Date(row.expires_at).getTime()<=Date.now();return{status:expired?"expired":"connected",email:row.email,scopes:row.scopes??[],expiresAt:row.expires_at,refreshAvailable:Boolean(row.refresh_ciphertext)}}
  async updateProfile(input:Record<string,unknown>){const{error}=await this.client.rpc("update_user_profile",{p_input:input});if(error)throw error}
  async invite(input:{email:string;name:string;role:string}){const{error}=await this.client.rpc("create_team_invitation",{p_workspace_id:this.workspaceId,p_email:input.email,p_name:input.name,p_role:input.role});if(error)throw error}
}

