import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read = path => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");

test("runtime core exposes the complete provider-neutral envelope", () => { const source = read("features/platform/ai-runtime/domain/contracts.ts"); for (const contract of ["AIRuntimeRequest", "AIRuntimeResponse", "AIRuntimeSession", "AIRuntimeConversation", "AIRuntimeContext", "AIRuntimeCapability", "AIRuntimeMetadata", "AIRuntimeCost", "AIRuntimeUsage", "AIRuntimeTrace", "AIRuntimeError", "AIRuntimeExplanation", "AIRuntimeCitation"]) assert.match(source, new RegExp(`interface ${contract}|type ${contract}`)) });
test("registry declares all future providers with disabled adapters", () => { const source = read("features/platform/ai-runtime/providers/provider-registry.ts"); for (const provider of ["openai", "anthropic", "google-gemini", "azure-openai", "ollama", "openrouter", "local-model", "enterprise-model"]) assert.match(source, new RegExp(provider)); assert.match(source, /adapterAvailable: false/); assert.match(source, /enabled: false/) });
test("router supports policy strategies without external calls", () => { const domain = read("features/platform/ai-runtime/domain/contracts.ts"), router = read("features/platform/ai-runtime/routing/provider-router.ts"); for (const strategy of ["preferred", "fallback", "capability", "cost", "latency", "region", "workspace", "ab-placeholder", "load-balance-placeholder"]) assert.match(domain, new RegExp(strategy)); assert.doesNotMatch(router, /fetch\(|axios|sdk|apiKey|new OpenAI|Anthropic|Gemini/i) });
test("prompts validation safety streaming and tools cover required contracts", () => { const files = ["prompts/prompt-management.ts", "validation/output-validator.ts", "safety/safety-layer.ts", "streaming/streaming-controller.ts", "tools/tool-registry.ts"].map(file => read(`features/platform/ai-runtime/${file}`)).join("\n"); for (const feature of ["requiredVariables", "Missing required field", "prompt-injection", "pii", "tenant-isolation", "permission", "cancel", "timeout", "reconnect", "heartbeat", "calendar", "crm", "email", "documents", "search", "tasks", "properties", "leads", "deals", "analytics", "plugin"]) assert.match(files, new RegExp(feature, "i")) });
test("runtime never invokes providers or executes tools", () => { const files = ["services/ai-runtime.ts", "providers/provider-registry.ts", "routing/provider-router.ts", "tools/tool-registry.ts", "safety/safety-layer.ts"].map(file => read(`features/platform/ai-runtime/${file}`)).join("\n"); assert.doesNotMatch(files, /fetch\(|axios|new OpenAI|createClient|supabase|\.from\(|\.rpc\(/i); assert.match(files, /executable: false/); assert.match(files, /Provider adapters are disabled/) });
test("runtime dashboard route documentation and ADR are registered", () => { assert.match(read("app/vayon/runtime/page.tsx"), /RuntimeDashboard/); assert.match(read("features/platform/builder/config/vayon-navigation.ts"), /href: "\/vayon\/runtime"/); assert.match(read("docs/RELEASE_0_8_AI_RUNTIME.md"), /Vayon AI Runtime/); assert.match(read("docs/adr/ADR-0008-ai-runtime.md"), /# ADR-0008/) });

