import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read = path => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
test("canonical envelope implements every approved field as readonly", () => { const source = read("features/platform/business-timeline/domain/contracts.ts"); for (const field of ["eventId", "eventName", "eventVersion", "envelopeVersion", "organizationId", "workspaceId", "partitionKey", "subject", "relatedObjects", "actor", "owner", "source", "occurredAt", "recordedAt", "receivedAt", "sequence", "correlationId", "causationId", "idempotencyKey", "category", "priority", "severity", "visibility", "summary", "payload", "classification", "retentionClass", "derivedFrom", "supersedesEventId", "traceId", "integrity"]) assert.match(source, new RegExp(`readonly ${field}`)) });
test("taxonomy registry covers all categories and supports versions", () => { const source = read("features/platform/business-timeline/domain/taxonomy.ts"); for (const category of ["sales", "growth", "communication", "operations", "finance", "documents", "governance", "customer", "integration", "workforce", "intelligence", "platform", "audit"]) assert.match(source, new RegExp(category)); assert.match(source, /versions\(eventName/); assert.match(source, /eventVersion/) });
test("object links reference identities and roles without object payloads", () => { const source = read("features/platform/business-timeline/domain/contracts.ts"); assert.match(source, /TimelineObjectRef/); assert.match(source, /EventObjectLink/); assert.match(source, /ObjectRole/); assert.doesNotMatch(source, /UniversalObjectBase|UniversalObject=/) });
test("in-memory storage is append-only immutable idempotent and replayable", () => { const source = read("features/platform/business-timeline/storage/in-memory-timeline.store.ts"); for (const guarantee of ["Object.freeze", "idempotency", "sequences", "append", "read", "replay", "Event ID already exists"]) assert.match(source, new RegExp(guarantee)); assert.doesNotMatch(source, /update\(|delete\(|remove\(|splice\(|supabase|createClient|\.from\(|\.rpc\(/i) });
test("projection search and subscription contracts cover the foundation", () => { const projections = read("features/platform/business-timeline/projections/contracts.ts"), search = read("features/platform/business-timeline/search/contracts.ts"), subscriptions = read("features/platform/business-timeline/subscriptions/contracts.ts"); for (const value of ["workspace-timeline", "object-timeline", "recent-events", "category-view", "actor-view", "correlation-view"]) assert.match(projections, new RegExp(value)); for (const value of ["timeRange", "categories", "object", "actorId", "correlationId", "severities", "priorities", "workspaceId", "organizationId", "indexStatus: \"unavailable\""]) assert.match(search, new RegExp(value)); for (const value of ["consumerIdentity", "cursor", "ordering", "retryPolicy", "deadLetterStatus", "SubscriptionReplay", "executable: false"]) assert.match(subscriptions, new RegExp(value)) });
test("validation covers tenant workspace envelope version idempotency visibility classification and required fields", () => { const source = read("features/platform/business-timeline/services/validation.service.ts"); for (const value of ["tenant", "workspace", "envelope", "version", "idempotency", "visibility", "classification", "required", "taxonomy"]) assert.match(source, new RegExp(value)) });
test("timeline foundation has no database broker external API AI or execution", () => { const files = ["storage/in-memory-timeline.store.ts", "subscriptions/in-memory-subscriptions.ts", "search/in-memory-search.ts", "services/timeline.service.ts"].map(file => read(`features/platform/business-timeline/${file}`)).join("\n"); assert.doesNotMatch(files, /fetch\(|axios|createClient|supabase|\.from\(|\.rpc\(|kafka|eventbridge|openai|anthropic|gemini|execute\(/i) });
test("dashboard and navigation are registered", () => { assert.match(read("app/vayon/timeline/page.tsx"), /TimelineDashboard/); assert.match(read("features/platform/builder/config/vayon-navigation.ts"), /href: "\/vayon\/timeline"/); assert.match(read("docs/RELEASE_1_1_BUSINESS_TIMELINE_FOUNDATION.md"), /Business Timeline Foundation/); assert.match(read("docs/adr/ADR-0011-business-timeline-foundation.md"), /# ADR-0011/) });

