import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read = path => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");

test("context graph supports typed evidence-backed traversal", () => { const domain = read("features/platform/intelligence/cognitive/domain/contracts.ts"), graph = read("features/platform/intelligence/cognitive/graph/context-graph.ts"); for (const value of ["organization", "workspace", "user", "contact", "company", "property", "lead", "deal", "task", "activity", "document", "calendar-event", "knowledge", "memory", "recommendation", "prediction", "event", "analytics", "direction", "weight", "confidence", "evidence"]) assert.match(domain, new RegExp(value)); assert.match(graph, /traverse/); assert.doesNotMatch(graph, /supabase|\.from\(|\.rpc\(|fetch\(/i) });
test("goals planning policies and approvals expose complete contracts", () => { const source = read("features/platform/intelligence/cognitive/domain/contracts.ts"); for (const value of ["business", "personal", "team", "ai", "workflow", "successCriteria", "failureCriteria", "dependencyIds", "parallel", "sequential", "estimatedMinutes", "future-reinforcement", "manager", "owner", "legal", "finance", "executive", "delegatedTo", "expiresAt", "auditId"]) assert.match(source, new RegExp(value)) });
test("action lifecycle is safe and cannot execute", () => { const source = read("features/platform/intelligence/cognitive/lifecycle/action-lifecycle.ts"); for (const stage of ["observe", "understand", "plan", "evaluate", "policy-check", "approval-check", "execute-placeholder", "verify", "explain", "learn", "store-memory", "audit", "rollback-placeholder"]) assert.match(source, new RegExp(stage)); assert.match(source, /executionAvailable: false/); assert.match(source, /rollbackAvailable: false/) });
test("workforce consumes brain and cognitive contracts without execution", () => { const source = read("features/platform/intelligence/cognitive/workforce/contracts.ts"); for (const value of ["goals", "policies", "approvalTypes", "createBrainRequest", "createCognitiveRequest", "consumePlan", "consumeReflection", "consumeLearning", "explain"]) assert.match(source, new RegExp(value)); assert.match(source, /execute\?: never/) });
test("cognitive implementation has no providers databases or production calls", () => { for (const file of ["services/cognitive-engine.ts", "policies/policy-engine.ts", "planning/planners.ts", "learning/learning-engine.ts", "reflection/reflection-engine.ts", "rules/business-rules.ts"]) assert.doesNotMatch(read(`features/platform/intelligence/cognitive/${file}`), /new OpenAI|Anthropic|Gemini|supabase|createClient|\.from\(|\.rpc\(|fetch\(/i) });
test("cognitive dashboard and architecture records are registered", () => { assert.match(read("features/platform/builder/config/vayon-navigation.ts"), /href: "\/vayon\/cognitive"/); assert.match(read("app/vayon/cognitive/page.tsx"), /CognitiveDashboard/); assert.match(read("docs/RELEASE_0_6_6_COGNITIVE_ENGINE.md"), /Vayon Cognitive Engine/); assert.match(read("docs/adr/ADR-0007-cognitive-engine.md"), /# ADR-0007/) });

