import assert from"node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";const read=path=>readFileSync(path,"utf8");
test("contact provider contracts are neutral",()=>{const source=read("features/platform/external-contacts/domain/contracts.ts");for(const provider of["google_contacts","microsoft_people","exchange_contacts","apple_contacts","carddav","enterprise_contacts"])assert.match(source,new RegExp(provider));for(const field of["primaryEmail","phones","organization","birthday","groups"])assert.match(source,new RegExp(field))});
test("Contacts authorization is incremental and read only",()=>{const scopes=read("features/platform/integrations/identity/registry.ts"),actions=read("features/platform/integrations/google/actions.ts");assert.match(scopes,/contacts\.readonly/);assert.match(scopes,/contacts\.other\.readonly/);assert.match(scopes,/directory\.readonly/);assert.match(actions,/additionalScopes:googleContactsScopes/)});
test("matching is deterministic and never merges",()=>{const source=read("features/platform/external-contacts/matching/contact-matcher.ts");for(const reason of["email_exact","phone_exact","organization_exact","name_exact"])assert.match(source,new RegExp(reason));assert.match(source,/automaticMerge:false/);assert.doesNotMatch(source,/merge\(|update.*contact/i)});
test("link contracts cover CRM and platform identities",()=>{const source=read("features/platform/external-contacts/domain/contracts.ts");for(const type of["contact","company","lead","deal","communication","meeting","timeline_identity","context_identity"])assert.match(source,new RegExp(type));assert.match(source,/status:"proposed"/)});
test("timeline proposals never write",()=>{const source=read("features/platform/external-contacts/timeline/contact-proposals.ts");for(const event of["contact.imported","contact.updated","contact.linked","contact.unlinked","contact.duplicate.detected"])assert.match(source,new RegExp(event.replaceAll(".","\\.")));assert.doesNotMatch(source,/append\(|publish\(/)});
test("Universal Bar context and Integration Center are registered",()=>{assert.match(read("features/platform/external-contacts/search/google-contacts-search.ts"),/GoogleContactsService/);assert.match(read("features/platform/external-contacts/context/provider-contact-context.ts"),/ProviderContactContextSlice/);const registry=read("features/platform/integrations/center/registry.ts");assert.match(registry,/google_contacts[\s\S]+featureFlag:\s*"google_contacts"/);assert.match(registry,/\/vayon\/contacts\/google/)});
test("observability excludes contact details",()=>{const source=read("features/platform/integrations/google/services/contacts.service.ts"),calls=source.match(/log\("google_contacts\.[^;]+/g)??[];assert.ok(calls.length);for(const call of calls)assert.doesNotMatch(call,/name:|email:|phone:|address:|organization:|notes:/)});
test("workspace has exact disconnected state",()=>assert.match(read("features/platform/external-contacts/components/GoogleContactsWorkspace.tsx"),/Google Contacts is not connected\./));
