import assert from"node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";const read=path=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
test("Microsoft identity uses authorization code PKCE state nonce and offline consent",()=>{const oauth=read("features/platform/integrations/microsoft/services/microsoft-oauth.service.ts"),scopes=read("features/platform/integrations/identity/registry.ts"),actions=read("features/platform/integrations/microsoft/actions.ts"),callback=read("app/integrations/microsoft/callback/route.ts");for(const value of["grant_type:\"authorization_code\"","code_challenge_method:\"S256\"","nonce","organizations"])assert.match(oauth,new RegExp(value));assert.match(scopes,/offline_access/);assert.match(actions,/randomBytes\(32\)/);assert.match(callback,/microsoftSafeEqual/)});
test("Microsoft token validation verifies signature tenant issuer audience expiry and nonce",()=>{const source=read("features/platform/integrations/microsoft/services/microsoft-oauth.service.ts");for(const value of["RS256","discovery/v2.0/keys","createPublicKey","verify(\"RSA-SHA256\"","claims.aud","claims.exp","claims.nonce","claims.tid","claims.iss"])assert.match(source,new RegExp(value.replace("(","\\(")))});
test("credential vault uses AES-256-GCM workspace AAD secure HttpOnly cookies and versioning",()=>{const vault=read("features/platform/integrations/microsoft/storage/cookie-credential.vault.ts"),oauth=read("features/platform/integrations/microsoft/services/microsoft-oauth.service.ts");for(const value of["aes-256-gcm","setAAD","httpOnly:true","sameSite:\"lax\"","secure:"])assert.match(vault,new RegExp(value));assert.match(oauth,/version:stored.version\+1/);assert.doesNotMatch(vault,/google_oauth_credentials|supabase/)});
test("provider registry covers identity and five active Graph products",()=>{const source=read("features/platform/integrations/microsoft/provider/registry.ts");for(const provider of["microsoft_identity","outlook","microsoft_calendar","onedrive","microsoft_people","teams"])assert.match(source,new RegExp(provider));assert.equal((source.match(/status:\"active\"/g)??[]).length,6)});
test("Integration Center exposes Microsoft status scopes validation flags and settings",()=>{const registry=read("features/platform/integrations/center/registry.ts"),service=read("features/platform/integrations/center/service.ts");assert.match(registry,/microsoft_identity/);assert.match(registry,/settings\/integrations\/microsoft/);assert.match(service,/validatedAt/);assert.match(service,/microsoft\?\.scopes/)});
test("Microsoft workflow actions are non executable contracts",()=>{const source=read("features/platform/workflows/registry/microsoft-provider-nodes.ts");for(const label of["Send Outlook Email","Schedule Outlook Meeting","Upload to OneDrive","Send Teams Message"])assert.match(source,new RegExp(label));assert.equal((source.match(/executable:false/g)??[]).length,6);assert.doesNotMatch(source,/fetch\(|execute\(/)});
test("feature flags environment docs and customer dashboard are registered",()=>{assert.match(read("lib/infrastructure/feature-flags.ts"),/microsoft_identity/);assert.match(read(".env.example"),/FEATURE_MICROSOFT_IDENTITY=false/);assert.match(read("app/vayon/settings/integrations/microsoft/page.tsx"),/MicrosoftIdentityDashboard/);assert.match(read("docs/RELEASE_2_8_MICROSOFT_PLATFORM.md"),/Known limitations/i);assert.match(read("docs/MICROSOFT_SETUP.md"),/Azure app registration/i)});
test("Microsoft workflow contracts cannot execute provider operations",()=>{const source=read("features/platform/workflows/registry/microsoft-provider-nodes.ts");assert.match(source,/contract-only/);assert.doesNotMatch(source,/sendMail|calendar\/events|drive\/items|chats\/|contacts\//)});
