import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const read=(path)=>readFile(path,"utf8");

test("CRM AI reuses the existing streaming workforce runtime",async()=>{const runtime=await read("features/platform/openai/runtime/service.ts");assert.match(runtime,/CRMAIService\.production/);assert.match(runtime,/input\.employee === "crm-ai"/);assert.match(runtime,/this\.provider\.stream/);});
test("CRM AI repository preserves tenant isolation and production evidence",async()=>{const source=await read("features/platform/crm-ai/repositories/supabase-crm-ai.repository.ts");assert.match(source,/eq\("organization_id", this\.organizationId\)/);assert.match(source,/eq\("workspace_id", this\.workspaceId\)/);for(const table of ["leads","deals","meetings","communications","activity_events","ai_recommendations"])assert.match(source,new RegExp(`\\"${table}\\"`));assert.doesNotMatch(source,/mock|fixture/i);});
test("customer intelligence includes summaries timeline interactions opportunities and lifetime activity",async()=>{const source=await read("features/platform/crm-ai/repositories/supabase-crm-ai.repository.ts");for(const field of ["summary","timelineSummary","recentInteractions","openOpportunities","opportunityValue","lifetimeActivity","lastContact","nextEngagement"])assert.match(source,new RegExp(field));});
test("CRM health covers data quality without fabricating unavailable company storage",async()=>{const source=await read("features/platform/crm-ai/repositories/supabase-crm-ai.repository.ts");for(const code of ["duplicate_leads","duplicate_contacts","duplicate_companies","missing_contact","invalid_data","incomplete_opportunities","orphaned_records"])assert.match(source,new RegExp(code));assert.match(source,/Company storage is not available/);assert.match(source,/available: false/);});
test("relationship and activity intelligence provide health segments and engagement",async()=>{const source=await read("features/platform/crm-ai/repositories/supabase-crm-ai.repository.ts");for(const segment of ["vip","high-value","returning","at-risk","inactive","active"])assert.match(source,new RegExp(segment));assert.match(source,/healthScore/);assert.match(source,/channels\.email/);assert.match(source,/channels\.whatsapp/);});
test("natural-language CRM search supports required query intents",async()=>{const [service,search]=await Promise.all([read("features/platform/crm-ai/services/crm-ai.service.ts"),read("features/platform/crm-ai/components/CRMSearch.tsx")]);for(const phrase of ["missing email","missing phone","haven't replied","worth","vip"])assert.match(`${service}\n${search}`,new RegExp(phrase.replace("'","['’]"),"i"));assert.match(service,/async search\(query: string\)/);});
test("CRM dashboard includes health cleanup activity and observability",async()=>{const source=await read("features/platform/crm-ai/components/CRMAIDashboard.tsx");for(const label of ["CRM health score","Duplicate records","Missing data","Inactive customers","High value customers","Cleanup recommendations","Recent CRM activity","Latency","Prompt tokens","Completion tokens","Estimated cost","Model","Recommendations"])assert.match(source,new RegExp(label,"i"));});
test("CRM AI is recommendation-only approval-governed and cannot edit",async()=>{const [service,runtime]=await Promise.all([read("features/platform/crm-ai/services/crm-ai.service.ts"),read("features/platform/openai/runtime/service.ts")]);assert.match(service,/recommendationOnly:true/);assert.match(service,/approvalRequired:true/);assert.match(service,/editingAllowed:false/);assert.match(runtime,/Never invent CRM relationships/);assert.match(runtime,/Never execute or send messages/);assert.match(runtime,/Never edit records/);});
