import assert from "node:assert/strict";import{existsSync,readFileSync}from"node:fs";import test from"node:test";const read=path=>readFileSync(path,"utf8");
test("Marketing Studio is protected by production subscription licensing",()=>{const flags=read("lib/infrastructure/feature-flags.ts"),access=read("features/vayon/creative-studio/access.service.ts"),env=read(".env.example");assert.doesNotMatch(flags,/creative_studio_beta/);assert.doesNotMatch(env,/FEATURE_CREATIVE_STUDIO_BETA/);for(const source of ["FeatureLicensingService","marketing_studio","subscription","internal","workspace_members"])assert.match(access,new RegExp(source));assert.match(read("app/vayon/creative-studio/page.tsx"),/notFound/)});
test("campaign wizard covers every project campaign audience and platform step",()=>{const domain=read("features/vayon/creative-studio/domain.ts"),ui=read("features/vayon/creative-studio/components/StudioViews.tsx");for(const value of ["Choose Project","Campaign Type","Audience","Platforms","AI Draft Package","Launch","Festival","Inventory Clearance","Price Revision","New Tower","Luxury","Rental","Referral","First-time buyers","Investors","NRIs","Print","Instagram","Facebook","LinkedIn","WhatsApp","Email","SMS","Website Banner","YouTube","Reels","Stories"])assert.match(`${domain}\n${ui}`,new RegExp(value))});
test("designer social video and copy studios expose complete draft catalogs",()=>{const source=read("features/vayon/creative-studio/domain.ts");for(const value of ["A4 Flyer","Roll-up Banner","Billboard","Newspaper Advertisement","Brochure Cover","Project Factsheet","QR Flyer","Instagram Post","Carousel","WhatsApp Status","Customer Testimonial Layout","15 Second Promo","60 Second Promo","Property Slideshow","YouTube Short","TikTok-style Vertical Video","voiceover","captions","Facebook Ad Copy","Google Ad Copy","Landing Page Copy","Blog Article","SEO Meta","Hashtags"])assert.match(source,new RegExp(value))});
test("service reuses inventory organization branding and governed collaboration",()=>{const service=read("features/vayon/creative-studio/service.ts"),provider=read("features/vayon/creative-studio/providers.ts");assert.match(service,/InventoryService\.production/);assert.match(service,/EnterpriseOrganizationService/);for(const employee of ["Marketing Manager","Copywriter","Designer","Campaign Manager","Compliance Reviewer","Brand Guardian","Sales Manager"])assert.match(provider,new RegExp(employee));for(const value of ["recommendationOnly:true","draftOnly:true","approvalRequired:true","livePublishing:false","externalRendering:false","tenantScoped:true"])assert.match(`${service}\n${provider}`,new RegExp(value))});
test("brand guardian scoring variations templates exports and timeline are modeled",()=>{const domain=read("features/vayon/creative-studio/domain.ts"),ui=read("features/vayon/creative-studio/components/StudioViews.tsx");for(const value of ["logoPath","secondaryLogoPath","colors","typography","fonts","watermarks","emailSignature","legalDisclaimer","reraInformation","tone","overall","visual","copy","brand","readability","ctaStrength","offerVisibility","trust","Version A","Version B","Version C","prompt","approver","edits","exports","publishingHistory","Print-ready PDF","PowerPoint placeholder"])assert.match(`${domain}\n${ui}`,new RegExp(value))});
test("future publishing provider cannot publish or call an external service",()=>{const source=read("features/vayon/creative-studio/providers.ts");assert.match(source,/FutureCreativePublishingProvider/);assert.match(source,/livePublishing=false/);assert.match(source,/state:"draft"/);assert.match(source,/approvalRequired:true/);assert.doesNotMatch(source,/fetch\(|axios|publish\(|render\(|send\(/i)});
test("studio routes cover dashboard wizard assets brand kits templates and analytics",()=>{for(const route of ["app/vayon/creative-studio/page.tsx","app/vayon/creative-studio/wizard/page.tsx","app/vayon/creative-studio/assets/page.tsx","app/vayon/creative-studio/brand-kits/page.tsx","app/vayon/creative-studio/templates/page.tsx","app/vayon/creative-studio/analytics/page.tsx"])assert.ok(existsSync(route),route)});
test("migration enforces tenant RLS draft status sequential approval and audit history",()=>{const sql=read("supabase/migrations/20260911000000_sprint82_creative_studio_beta.sql");for(const value of ["creative_brand_kits","creative_campaigns","creative_assets","creative_timeline","enable row level security","creative_studio_member","creative_studio_manage","create_creative_campaign_draft","advance_creative_campaign","'draft'","'marketing-review'","'sales-review'","'management-approval'","'approved'","'ready-to-publish'","invalid approval transition","recommendation_only","live_publishing"])assert.match(sql,new RegExp(value,"i"))});
