import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";
const read = (path) => readFileSync(path, "utf8");

test("unified inbox exposes requested channels filters and smart search", () => {
  const model=read("features/vayon/communications-workspace/domain/models.ts"),page=read("app/vayon/communications/inbox/page.tsx"),repo=read("features/vayon/communications-workspace/repositories/supabase.repository.ts");
  for(const value of ["All Conversations","WhatsApp","Email","Internal Notes","Calls","SMS","System Notifications","Unread","Assigned","AI Draft Pending","High Priority","Closed","Archived"]) assert.match(page,new RegExp(value));
  for(const value of ["customer","leadId","opportunityId","propertyId","projectId","assignedHuman","timeline","tags","notes"]) assert.match(model,new RegExp(value));
  assert.match(repo,/organization_id/);assert.match(repo,/workspace_id/);
});
test("provider abstraction prepares every future connector without live delivery",()=>{const contract=read("features/vayon/communications-workspace/contracts/repository.ts"),provider=read("features/vayon/communications-workspace/providers/connector.provider.ts");for(const value of ["whatsapp-cloud","gmail","outlook","microsoft-365","sms","voice"])assert.match(provider,new RegExp(value));assert.match(contract,/CommunicationsConnectorProvider/);assert.match(provider,/liveDelivery: false/);assert.doesNotMatch(provider,/fetch\(|send\(|axios/i)});
test("AI assistance remains recommendation-only and governed",()=>{const model=read("features/vayon/communications-workspace/domain/models.ts"),service=read("features/vayon/communications-workspace/services/communications.service.ts"),governance=read("features/vayon/communications-workspace/services/outbound-governance.ts");for(const value of ["summary","suggestedReply","actionItems","urgency","recommendationOnly"])assert.match(model,new RegExp(value));assert.match(service,/deterministic-rules/);assert.match(governance,/approvalRequired:\s*true/);assert.match(governance,/executionRequested:\s*false/)});
test("dashboard reports attachments notes and channel readiness",()=>{const ui=read("features/vayon/communications-workspace/components/CommunicationViews.tsx"),service=read("features/vayon/communications-workspace/services/communications.service.ts");for(const value of ["Open Conversations","Response Time","Unread","Resolved Today","Pending AI Drafts","Conversations by Channel","Agent Workload","Messages by channel","Resolution rate","AI draft usage"])assert.match(service,new RegExp(value));for(const value of ["Channel readiness","Internal notes","Attachments","Communication reporting"])assert.match(ui,new RegExp(value))});
test("communications routes cover hub inbox threads connectors notifications and reports",()=>{for(const path of ["app/vayon/communications/page.tsx","app/vayon/communications/inbox/page.tsx","app/vayon/communications/conversations/page.tsx","app/vayon/communications/conversations/[conversationId]/page.tsx","app/vayon/communications/connectors/page.tsx","app/vayon/communications/notifications/page.tsx","app/vayon/communications/reports/page.tsx"])assert.ok(existsSync(path),path)});
test("migration enforces tenant RLS permissions audit and safe attachments",()=>{const sql=read("supabase/migrations/20260910000000_sprint81_enterprise_communications_hub.sql");for(const value of ["communication_attachments","communication_ai_recommendations","communication_audit","enable row level security","communication_tenant_member","communication_can_manage","recommendation_only","conversation-members","internal_note.created","authenticated"])assert.match(sql,new RegExp(value,"i"));assert.doesNotMatch(sql,/service_role/)});
