import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";const read=path=>readFile(path,"utf8");
test("Marketing AI reuses the existing streaming workforce runtime",async()=>{const s=await read("features/platform/openai/runtime/service.ts");assert.match(s,/MarketingAIService\.production/);assert.match(s,/input\.employee === "marketing-ai"/);assert.match(s,/this\.provider\.stream/)});
test("repository uses tenant scoped CRM communications billing and observability evidence",async()=>{const s=await read("features/platform/marketing-ai/repositories/supabase-marketing-ai.repository.ts");assert.match(s,/eq\("organization_id",this\.organizationId\)/);assert.match(s,/eq\("workspace_id",this\.workspaceId\)/);for(const table of["leads","communications","subscriptions","activity_events","ai_recommendations","ai_workforce_messages"])assert.match(s,new RegExp(`\\"${table}\\"`));assert.doesNotMatch(s,/mock|fixture/i)});
test("campaign intelligence playbook covers objectives audiences channels budgets and probability",async()=>{const c=await read("features/platform/openai/runtime/ChatPanel.tsx");assert.match(c,/campaign with objectives, audience, channels, budget, and confidence/i)});
test("Marketing AI supports Facebook Google SEO email social and lead generation drafts",async()=>{const c=await read("features/platform/openai/runtime/ChatPanel.tsx");for(const phrase of["Facebook ads","Google ads","SEO topic","email nurture","LinkedIn, Facebook, Instagram, X, and YouTube Shorts","lead magnets, landing pages, forms, CTAs, and funnels"])assert.match(c,new RegExp(phrase,"i"))});
test("lead source analytics calculates qualified won conversion and high intent",async()=>{const s=await read("features/platform/marketing-ai/repositories/supabase-marketing-ai.repository.ts");for(const field of["leadSources","qualified","won","conversionRate","highIntent"])assert.match(s,new RegExp(field))});
test("campaign health CAC and ROI remain explicitly unavailable without evidence",async()=>{const s=await read("features/platform/marketing-ai/services/marketing-ai.service.ts");assert.match(s,/campaign performance repository is connected/);assert.match(s,/Campaign spend and attributable revenue are unavailable/);assert.match(s,/Campaign spend and attributable acquisition data are unavailable/);assert.match(s,/Never treat subscription billing as campaign spend/)});
test("dashboard exposes campaign lead source ROI calendar recommendation timeline and observability surfaces",async()=>{const s=await read("features/platform/marketing-ai/components/MarketingAIDashboard.tsx");for(const label of["Campaign health","Top campaigns","Lead sources","ROI","Content calendar","Recent recommendations","Marketing timeline","Prompt tokens","Completion tokens","Latency","Model","Estimated cost","Recommendation count"])assert.match(s,new RegExp(label,"i"))});
test("Marketing AI cannot publish spend email or message autonomously",async()=>{const[s,r]=await Promise.all([read("features/platform/marketing-ai/services/marketing-ai.service.ts"),read("features/platform/openai/runtime/service.ts")]);assert.match(s,/recommendationOnly:true/);assert.match(s,/approvalRequired:true/);assert.match(s,/publishingAllowed:false/);assert.match(s,/adSpendAllowed:false/);assert.match(s,/emailSendingAllowed:false/);assert.match(s,/whatsappSendingAllowed:false/);assert.match(r,/Never publish or spend/)});
