import assert from"node:assert/strict";import{existsSync,readFileSync}from"node:fs";import test from"node:test";const read=p=>readFileSync(p,"utf8");
test("knowledge platform preserves repository service provider architecture",()=>{for(const file of["contracts/index.ts","repositories/knowledge.repository.ts","services/knowledge.service.ts","providers/future-rag.provider.ts","components/KnowledgeCenter.tsx","actions/index.ts"])assert.ok(existsSync(`features/platform/knowledge/${file}`));const service=read("features/platform/knowledge/services/knowledge.service.ts");assert.match(service,/KnowledgeRepository/);assert.match(service,/AIService/);assert.match(service,/FutureEnterpriseRagProvider/)});
test("canonical center covers every documentation category",()=>{const contracts=read("features/platform/knowledge/contracts/index.ts");for(const category of["user","administrator","ai","crm","workflow","billing","security","api","faq","release_notes","tutorial","organization"])assert.match(contracts,new RegExp(category));assert.match(read("app/vayon/ai/knowledge/page.tsx"),/vayon\/knowledge/)});
test("repository supports governed documents versions and permitted formats",()=>{const migration=read("supabase/migrations/20260827000000_sprint63_enterprise_knowledge_platform.sql"),repository=read("features/platform/knowledge/repositories/knowledge.repository.ts");for(const table of["knowledge_articles","knowledge_article_versions","knowledge_documents","knowledge_analytics"])assert.match(migration,new RegExp(`public\\.${table}`));for(const format of["pdf","docx","md","txt"])assert.match(repository,new RegExp(format));for(const state of["draft","published","archived"])assert.match(migration,new RegExp(state));assert.match(migration,/last_reviewed_at/);assert.match(migration,/author_name/)});
test("enterprise search is full text tenant scoped and records analytics",()=>{const migration=read("supabase/migrations/20260827000000_sprint63_enterprise_knowledge_platform.sql");assert.match(migration,/to_tsvector/);assert.match(migration,/websearch_to_tsquery/);assert.match(migration,/current_workspace_role/);assert.match(migration,/search_failed/);assert.match(migration,/latency_ms/);assert.match(migration,/view_count/);assert.match(migration,/helpful_count/)});
test("AI help cites evidence escalates and remains recommendation only",()=>{const service=read("features/platform/knowledge/services/knowledge.service.ts"),page=read("app/vayon/knowledge/help/page.tsx");assert.match(service,/citations/);assert.match(service,/escalate:true/);assert.match(service,/recommendationOnly:true/);assert.match(service,/AIService/);assert.match(page,/Supporting documents/);assert.match(page,/Escalate to support/)});
test("tutorial and developer portals cover requested content",()=>{const center=read("features/platform/knowledge/components/KnowledgeCenter.tsx"),developer=read("app/vayon/developers/page.tsx");for(const tutorial of["Dashboard","CRM","Properties","Sales AI","CRM AI","WhatsApp AI","Marketing AI","Executive AI","Workflow Builder","Billing","Organizations","Security"])assert.match(center,new RegExp(tutorial));for(const section of["REST API reference","Authentication","Webhooks","SDK examples","Error codes","Rate limits","Changelog"])assert.match(developer,new RegExp(section))});
test("RAG preparation is an extension point without vector infrastructure",()=>{const provider=read("features/platform/knowledge/providers/future-rag.provider.ts");assert.match(provider,/SemanticKnowledgeProvider/);assert.match(provider,/Extension point only/);assert.doesNotMatch(provider,/pinecone|weaviate|qdrant|pgvector|@langchain/i)});
test("knowledge storage enforces RLS RBAC audit and private objects",()=>{const migration=read("supabase/migrations/20260827000000_sprint63_enterprise_knowledge_platform.sql");assert.match(migration,/enable row level security/g);assert.match(migration,/can_manage_knowledge/);assert.match(migration,/organization_audit_events/);assert.match(migration,/public\s*,\s*file_size_limit/);assert.match(migration,/values\('knowledge-documents','knowledge-documents',false/);assert.match(migration,/organization_id/);assert.match(migration,/workspace_id/)});
