import assert from"node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";const read=p=>readFileSync(p,"utf8");
test("notification domain covers every category channel and center state",()=>{const s=read("features/notifications/types.ts");for(const value of["system","ai_recommendation","workflow","crm","lead","deal","whatsapp","gmail","calendar","billing","security","organization","user_invitation","approval","marketing","in_app","email","browser_push","webhook","unread","archived","snoozed","starred","mentioned","high_priority"])assert.match(s,new RegExp(value))});
test("production provider applies preferences and preserves governed delivery boundaries",()=>{const s=read("features/notifications/providers/enterprise-notification.provider.ts");assert.match(s,/enqueue_notification/);assert.match(s,/configuredChannels/);assert.match(s,/notification_preferences/);assert.match(s,/categories/);assert.match(s,/recommendation_only/);assert.match(s,/future_ready/);assert.match(s,/WhatsApp delivery requires human approval/);assert.doesNotMatch(s,/Math\.random|mock|fake/i)});
test("repository scopes notifications and preferences to tenant and user",()=>{const s=read("features/notifications/repositories/notification.repository.ts");for(const value of["organization_id","workspace_id","user_id","notification_preferences","notification_reminders","notification_observability"])assert.match(s,new RegExp(value));assert.match(s,/\.eq\("organization_id",this\.o\)/);assert.match(s,/\.eq\("workspace_id",this\.w\)/)});
test("reminder engine supports every required reminder",()=>{const s=read("features/notifications/types.ts")+read("supabase/migrations/20260823000000_sprint59_enterprise_notifications.sql");for(const value of["meeting","task","lead_follow_up","deal_deadline","subscription_renewal","trial_ending","workflow_approval","ai_recommendation","custom","process_due_notification_reminders"])assert.match(s,new RegExp(value))});
test("database integrates AI approval billing security timeline and observability",()=>{const s=read("supabase/migrations/20260823000000_sprint59_enterprise_notifications.sql");for(const value of["notify_ai_recommendation","notify_ai_approval","notify_security_alert","notify_billing_event","activity_events","notification_observability","delivered","latency","enable row level security","is_organization_member"])assert.match(s,new RegExp(value,"i"));assert.match(s,/security definer/);assert.match(s,/service_role/)});
test("notification center implements search filters grouping pagination and metrics",()=>{const s=read("features/notifications/components/NotificationCenter.tsx");for(const value of["Search notifications","All categories","Map.groupBy","Previous","Next","Unread","Delivered","Failures","Avg latency","Schedule a reminder"])assert.match(s,new RegExp(value))});
test("preferences expose delivery categories mute quiet hours and digest",()=>{const s=read("features/notifications/components/NotificationPreferences.tsx");for(const value of["In-app","Email","Browser push","WhatsApp","Webhook","Mute notifications","Quiet hours","Digest","Categories"])assert.match(s,new RegExp(value))});
test("all notification routes use the unified production module",()=>{const center=read("app/vayon/notifications/page.tsx"),preferences=read("app/vayon/notifications/preferences/page.tsx"),inbox=read("app/vayon/notifications/inbox/page.tsx"),history=read("app/vayon/notifications/history/page.tsx");assert.match(center,/features\/notifications/);assert.match(preferences,/features\/notifications/);assert.doesNotMatch(center+preferences,/features\/platform\/notifications/);assert.match(inbox,/redirect/);assert.match(history,/archived/)});
