export type BillingMetric="ai_requests"|"tokens"|"storage_gb"|"users"|"whatsapp_messages"|"emails"|"calendar_events"|"api_calls";
export interface PlanRecord{id:string;code:string;name:string;description:string;monthlyPrice:number|null;currency:string;limits:Record<string,number|null>;features:string[];active:boolean}
export interface SubscriptionRecord{id:string;planId:string;planCode?:string;planName?:string;status:string;trialEndsAt?:string;currentPeriodEndsAt?:string;cancelAtPeriodEnd:boolean;seatQuantity:number;version:number;providerSubscriptionId?:string}
export interface UsageRecord{metric:string;quantity:number;periodStart:string;periodEnd:string;limit?:number|null}
export interface InvoiceRecord{id:string;number:string;status:string;currency:string;subtotal:number;tax:number;total:number;issuedAt?:string;dueAt?:string;paidAt?:string;downloadUrl?:string;providerInvoiceId?:string}
export interface PaymentMethodRecord{id:string;type:string;brand?:string;last4?:string;expiry?:string;isDefault:boolean;createdAt:string}
export interface BillingEventRecord{id:string;type:string;status:string;createdAt:string}
export interface BillingContactRecord{id:string;companyName:string;billingEmail:string;taxId?:string;address?:Record<string,string>;version:number}
export interface BillingDashboard{plans:PlanRecord[];subscription:SubscriptionRecord|null;usage:UsageRecord[];invoices:InvoiceRecord[];paymentMethods:PaymentMethodRecord[];events:BillingEventRecord[];contact:BillingContactRecord|null}
