import Image from "next/image";
import { Bath, BedDouble, Building2, Car, MapPin, Maximize2, UsersRound } from "lucide-react";
import { auroraCompanies } from "../crm-network/companies";
import { auroraEmployees } from "../people/employees";
import type { AuroraProperty } from "./contracts";

export function PropertyCard({property}:{readonly property:AuroraProperty}){return <article className="overflow-hidden rounded-3xl border border-vds-border bg-vds-surface"><Image src={property.thumbnailPlaceholder} width={640} height={360} alt="" className="aspect-video w-full object-cover"/><div className="p-5"><div className="flex flex-wrap gap-2">{property.categories.slice(0,2).map(item=><span key={item} className="rounded-full bg-vds-primary-soft px-2.5 py-1 text-[10px] capitalize text-vds-primary">{item.replaceAll("-"," ")}</span>)}</div><h3 className="mt-4 text-lg font-semibold">{property.name}</h3><p className="mt-1 flex items-center gap-1.5 text-xs text-vds-muted"><MapPin className="size-4"/>{property.locality}, {property.city}</p><p className="mt-4 font-medium text-vds-primary">{property.priceRange.label}</p><PropertySummary property={property}/></div></article>}
export function PropertySummary({property}:{readonly property:AuroraProperty}){return <div className="mt-4 flex flex-wrap gap-4 border-t border-vds-border pt-4 text-xs text-vds-muted">{property.bedrooms&&<span className="flex items-center gap-1"><BedDouble className="size-4"/>{property.bedrooms} beds</span>}{property.bathrooms&&<span className="flex items-center gap-1"><Bath className="size-4"/>{property.bathrooms} baths</span>}<span className="flex items-center gap-1"><Maximize2 className="size-4"/>{property.areaSquareFeet.toLocaleString()} sq ft</span></div>}
export function PropertyProfile({property}:{readonly property:AuroraProperty}){return <section className="space-y-5"><PropertyCard property={property}/><PropertySpecifications property={property}/><PropertyGalleryPlaceholder property={property}/><PropertyRelationshipPanel property={property}/></section>}
export function PropertyGalleryPlaceholder({property}:{readonly property:AuroraProperty}){return <section aria-label="Property gallery placeholder" className="grid gap-3 sm:grid-cols-3">{property.galleryPlaceholders.map((asset,index)=><Image key={`${asset}-${index}`} src={asset} width={480} height={270} alt="" className="aspect-video w-full rounded-2xl border border-vds-border object-cover"/>)}</section>}
export function PropertySpecifications({property}:{readonly property:AuroraProperty}){const rows=[["Type",property.propertyType.replaceAll("-"," ")],["Construction",property.constructionStatus.replaceAll("-"," ")],["Area",`${property.areaSquareFeet.toLocaleString()} sq ft`],["Parking",String(property.parking)],["Amenities",property.amenities.join(", ")]];return <section className="rounded-3xl border border-vds-border bg-vds-surface p-5"><h2 className="font-semibold">Specifications</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2">{rows.map(([label,value])=><div key={label}><dt className="text-xs text-vds-subtle">{label}</dt><dd className="mt-1 text-sm capitalize text-vds-secondary">{value}</dd></div>)}</dl></section>}
export function PropertyRelationshipPanel({property}:{readonly property:AuroraProperty}){const developer=auroraCompanies.find(item=>item.id===property.developerCompanyId),owner=auroraCompanies.find(item=>item.id===property.ownerCompanyId),manager=auroraEmployees.find(item=>item.id===property.assignedSalesManagerId),agent=auroraEmployees.find(item=>item.id===property.assignedSalesAgentId);return <section className="rounded-3xl border border-vds-border bg-vds-surface p-5"><h2 className="font-semibold">Property relationships</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Relation icon={Building2} label="Developer" value={developer?.name}/><Relation icon={Building2} label="Owner company" value={owner?.name}/><Relation icon={UsersRound} label="Sales manager" value={manager?.name}/><Relation icon={UsersRound} label="Sales agent" value={agent?.name}/><Relation icon={Car} label="Assigned office" value={property.officeId}/><Relation icon={UsersRound} label="Sales team" value={property.assignedSalesTeam}/></div></section>}
function Relation({icon:Icon,label,value}:{readonly icon:typeof Building2;readonly label:string;readonly value?:string}){return <div className="flex gap-3 rounded-2xl bg-vds-elevated p-3"><Icon className="mt-0.5 size-4 text-vds-primary"/><span><span className="block text-[10px] uppercase tracking-wide text-vds-subtle">{label}</span><span className="mt-1 block text-sm text-vds-secondary">{value??"Awaiting connected business data"}</span></span></div>}
