import { auroraCompanies } from "../crm-network/companies";
import { auroraEmployees } from "../people/employees";
import type { AuroraBusinessUnitId } from "../people/contracts";
import type { AuroraConstructionStatus, AuroraPriceBand, AuroraProperty, AuroraPropertyCategory, AuroraPropertyId, AuroraPropertyType } from "./contracts";

const roots=["Palm Vista","Emerald","Skyline","Ocean Crest","Crystal","Infinity","Royal Garden","Silver Oak","Urban One","Green Valley","Cedar Haven","Lakefront","Aster Grove","Blue Horizon","Maple Crown","Willow Brook","Sunstone","Orchid Bay","Riverstone","Golden Meadow","Arbor Rise","Serene Coast","Northgate","Ivory Park","Coral Springs"] as const;
const types:readonly {type:AuroraPropertyType;suffix:string;unit:AuroraBusinessUnitId;team:string;bedrooms?:number;area:number;parking:number;amenities:readonly string[];priceBand:AuroraPriceBand;priceLabel:string;min?:number;max?:number}[]=[
  {type:"residential-apartment",suffix:"Residences",unit:"residential",team:"Residential Advisory",bedrooms:3,area:1680,parking:2,amenities:["Clubhouse","Fitness studio","Children's play area"],priceBand:"1-5-to-3-crore",priceLabel:"₹1.6–2.8 crore",min:16000000,max:28000000},
  {type:"luxury-villa",suffix:"Villas",unit:"luxury",team:"Private Client Advisory",bedrooms:4,area:4200,parking:3,amenities:["Private garden","Pool provision","Concierge lounge"],priceBand:"3-to-7-crore",priceLabel:"₹4.2–6.8 crore",min:42000000,max:68000000},
  {type:"commercial-office",suffix:"Business Park",unit:"commercial",team:"Commercial Advisory",area:5200,parking:8,amenities:["Managed reception","Backup power","Visitor parking"],priceBand:"above-7-crore",priceLabel:"₹7.5–11 crore",min:75000000,max:110000000},
  {type:"retail-space",suffix:"Retail Arcade",unit:"commercial",team:"Commercial Advisory",area:2400,parking:4,amenities:["Street frontage","Service access","Signage zone"],priceBand:"3-to-7-crore",priceLabel:"₹3.2–5.4 crore",min:32000000,max:54000000},
  {type:"warehouse",suffix:"Logistics Centre",unit:"commercial",team:"Commercial Advisory",area:18000,parking:12,amenities:["Loading bays","Security cabin","Truck circulation"],priceBand:"above-7-crore",priceLabel:"₹8–13 crore",min:80000000,max:130000000},
  {type:"industrial",suffix:"Industrial Campus",unit:"investment",team:"Investment Advisory",area:26000,parking:16,amenities:["Utility yard","Heavy vehicle access","Operations block"],priceBand:"above-7-crore",priceLabel:"₹12–18 crore",min:120000000,max:180000000},
  {type:"plot",suffix:"Estate Plots",unit:"land",team:"Land Advisory",area:3200,parking:0,amenities:["Surveyed boundary","Road access","Utility corridor"],priceBand:"75-lakh-to-1-5-crore",priceLabel:"₹90 lakh–1.4 crore",min:9000000,max:14000000},
  {type:"farm-land",suffix:"Farm Estates",unit:"land",team:"Land Advisory",area:43560,parking:0,amenities:["Approach road","Water source placeholder","Boundary markers"],priceBand:"1-5-to-3-crore",priceLabel:"₹1.8–2.7 crore",min:18000000,max:27000000},
  {type:"investment-asset",suffix:"Investment Suites",unit:"investment",team:"Investment Advisory",area:3600,parking:5,amenities:["Managed lobby","Flexible floorplate","Service access"],priceBand:"3-to-7-crore",priceLabel:"₹3.8–6.2 crore",min:38000000,max:62000000},
  {type:"rental-property",suffix:"Rental Homes",unit:"rentals",team:"Rental Advisory",bedrooms:2,area:1180,parking:1,amenities:["Resident lounge","Security","Visitor parking"],priceBand:"lease-on-request",priceLabel:"Lease terms on request"},
] as const;
const locations=[{city:"Bengaluru",localities:["Whitefield","Indiranagar","Hebbal","Jayanagar","Sarjapur Road"]},{city:"Mumbai",localities:["Bandra West","Powai","Worli","Andheri East","Thane West"]},{city:"Hyderabad",localities:["Gachibowli","Kondapur","Jubilee Hills","Financial District","Kokapet"]},{city:"Pune",localities:["Kharadi","Baner","Hinjawadi","Viman Nagar","Wakad"]},{city:"Chennai",localities:["OMR","Adyar","Porur","Guindy","Velachery"]},{city:"Delhi",localities:["Aerocity","Saket","Dwarka","Vasant Kunj","Okhla"]}] as const;
const developers=auroraCompanies.filter(company=>company.category==="developer"),builders=auroraCompanies.filter(company=>company.category==="builder"),owners=auroraCompanies.filter(company=>["developer","builder","investor","property-management"].includes(company.category));
const sales=auroraEmployees.filter(person=>person.departmentId==="sales");
const construction:readonly AuroraConstructionStatus[]=["ready-to-move","under-construction","pre-launch"];
const category=(type:AuroraPropertyType,status:AuroraConstructionStatus,index:number):readonly AuroraPropertyCategory[]=>Object.freeze([status,type==="luxury-villa"?"luxury":type==="commercial-office"||type==="retail-space"||type==="warehouse"?"commercial":type==="investment-asset"||type==="industrial"?"investment":type==="rental-property"?"rental":index%4===0?"featured":index%3===0?"premium":"affordable"]);
const slug=(value:string)=>value.toLocaleLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");

export const auroraProperties=Object.freeze(types.flatMap((definition,typeIndex)=>roots.map((root,index)=>{const name=`${root} ${definition.suffix}`,id=`aurora-property-${slug(name)}` as AuroraPropertyId,location=locations[(index+typeIndex)%locations.length]!,constructionStatus=construction[(index+typeIndex)%construction.length]!,unitSales=sales.filter(person=>person.businessUnitIds.includes(definition.unit)),manager=unitSales.find(person=>person.title.includes("Manager"))??auroraEmployees.find(person=>person.title==="Sales Director")!,agent=unitSales.find(person=>person.title.includes("Agent"))??manager,developer=developers[(index+typeIndex)%developers.length]!,builder=builders[(index*2+typeIndex)%builders.length]!,owner=owners[(index*3+typeIndex)%owners.length]!,officeId=manager.officeId;return Object.freeze({id,name,businessUnitId:definition.unit,propertyType:definition.type,status:definition.type==="rental-property"?"rental-available" as const:index%7===0?"reserved" as const:index%11===0?"off-market" as const:"available" as const,city:location.city,locality:location.localities[index%location.localities.length]!,priceRange:Object.freeze({currency:"INR" as const,minimum:definition.min,maximum:definition.max,label:definition.priceLabel,band:definition.priceBand}),bedrooms:definition.bedrooms,bathrooms:definition.bedrooms?Math.max(1,definition.bedrooms-1):undefined,areaSquareFeet:definition.area+(index%5)*120,parking:definition.parking,amenities:Object.freeze([...definition.amenities]),constructionStatus,categories:category(definition.type,constructionStatus,index),developerCompanyId:developer.id,builderCompanyId:builder.id,ownerCompanyId:owner.id,officeId,assignedSalesTeam:definition.team,assignedSalesManagerId:manager.id,assignedSalesAgentId:agent.id,description:`${name} is a fictional ${definition.type.replaceAll("-"," ")} inventory profile in ${location.localities[index%location.localities.length]}, ${location.city}.`,tags:Object.freeze([definition.unit,definition.type,constructionStatus,location.city.toLocaleLowerCase().replaceAll(" ","-")]),thumbnailPlaceholder:`/vayon/demo/properties/property-${(typeIndex%4)+1}.svg`,galleryPlaceholders:Object.freeze([1,2,3].map(value=>`/vayon/demo/properties/property-${((typeIndex+value)%4)+1}.svg`)),futureDealReferences:Object.freeze([]),futureLeadReferences:Object.freeze([]),identity:Object.freeze({namespace:"aurora-demo-property" as const,objectId:id,objectType:"property" as const,context:Object.freeze({id,type:"property" as const,label:name,timelineRef:Object.freeze({objectId:id,objectType:"property",displayHint:name})}),timelineEvents:Object.freeze([])})})}))) satisfies readonly AuroraProperty[];
