import type { Theme } from "../types/theme";

export const themes: Theme[] = [
  {
    id: "atlas-dark",
    name: "Atlas Dark",
    description: "The signature dark-first AtlasOS operating environment.",
    typography: "Geist",
    colors: ["#060A10", "#0B1119", "#67E8F9", "#F8FAFC"],
    borderRadius: "16px",
    status: "Available",
    isDefault: true,
    previewClass: "from-[#05090f] via-[#0b1520] to-[#0b1119]",
  },
  {
    id: "atlas-light",
    name: "Atlas Light",
    description: "A clean, high-clarity light operating environment.",
    typography: "Geist",
    colors: ["#FFFFFF", "#F1F5F9", "#0891B2", "#0F172A"],
    borderRadius: "16px",
    status: "Preview",
    isDefault: false,
    previewClass: "from-white via-slate-100 to-slate-300",
  },
  {
    id: "corporate",
    name: "Corporate",
    description: "Structured enterprise presentation for regulated teams.",
    typography: "Inter",
    colors: ["#0F172A", "#1E293B", "#3B82F6", "#E2E8F0"],
    borderRadius: "10px",
    status: "Available",
    isDefault: false,
    previewClass: "from-slate-950 via-slate-800 to-blue-950",
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Calm blue and teal tones for expansive workspaces.",
    typography: "Geist",
    colors: ["#042F2E", "#083344", "#2DD4BF", "#ECFEFF"],
    borderRadius: "18px",
    status: "Available",
    isDefault: false,
    previewClass: "from-teal-950 via-cyan-950 to-blue-950",
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Deep contrast with restrained violet accents.",
    typography: "Geist",
    colors: ["#020617", "#111827", "#A78BFA", "#F5F3FF"],
    borderRadius: "14px",
    status: "Available",
    isDefault: false,
    previewClass: "from-black via-slate-950 to-violet-950",
  },
  {
    id: "glass",
    name: "Glass",
    description: "Layered translucency for expressive premium products.",
    typography: "Geist",
    colors: ["#0C1220", "#FFFFFF14", "#22D3EE", "#FFFFFF"],
    borderRadius: "22px",
    status: "Preview",
    isDefault: false,
    previewClass: "from-cyan-950 via-slate-900 to-fuchsia-950",
  },
  {
    id: "high-contrast",
    name: "High Contrast",
    description: "Maximum clarity designed around accessibility requirements.",
    typography: "Atkinson",
    colors: ["#000000", "#171717", "#FFFF00", "#FFFFFF"],
    borderRadius: "8px",
    status: "Available",
    isDefault: false,
    previewClass: "from-black via-neutral-950 to-yellow-950",
  },
  {
    id: "custom-branding",
    name: "Custom Branding",
    description: "A governed theme surface for organization brand systems.",
    typography: "Configurable",
    colors: ["#18181B", "#27272A", "#D946EF", "#FAFAFA"],
    borderRadius: "Custom",
    status: "Custom",
    isDefault: false,
    previewClass: "from-zinc-950 via-zinc-900 to-fuchsia-950",
  },
];
