import "server-only";
import { operationsContext } from "@/features/vayon/operations/services/context";
import type { CRMAIRepositoryContract } from "../contracts/repository";
import { SupabaseCRMAIRepository } from "../repositories/supabase-crm-ai.repository";
import type { CRMAIDashboard, CRMCustomerIntelligence } from "../types";

export class CRMAIService {
  constructor(private repository: CRMAIRepositoryContract) {}
  static async production() { const context = await operationsContext(); return new CRMAIService(new SupabaseCRMAIRepository(context.client, context.organizationId, context.workspaceId)); }
  async dashboard(): Promise<CRMAIDashboard> { const evidence = await this.repository.evidence(), available = evidence.issues.filter((issue) => issue.available), defects = available.reduce((sum,issue) => sum + (issue.count ?? 0),0), denominator = Math.max(1,evidence.customers.length + available.length); return { healthScore: Math.max(0,Math.round(100-defects/denominator*25)), customers: evidence.customers, issues: evidence.issues, duplicateRecords: evidence.issues.filter((issue) => issue.code.startsWith("duplicate_") && issue.available).reduce((sum,issue) => sum+(issue.count??0),0), missingData: evidence.issues.find((issue) => issue.code === "missing_contact")?.count ?? 0, inactiveCustomers: evidence.customers.filter((customer) => customer.segment === "inactive").length, highValueCustomers: evidence.customers.filter((customer) => customer.segment === "high-value" || customer.segment === "vip").length, recommendations: evidence.recommendations, recentActivity: evidence.recentActivity, observability: evidence.observability, generatedAt: new Date().toISOString() }; }
  async search(query: string): Promise<readonly CRMCustomerIntelligence[]> { const normalized=query.trim().toLowerCase(), data=await this.dashboard(); if(!normalized)return data.customers; const daysMatch=normalized.match(/(\d+)\s*days?/), amountMatch=normalized.match(/(?:over|above|worth)\s*(?:\$|₹)?\s*([\d,.]+)\s*(k|m|lakh|crore)?/); const inactivity=daysMatch?Number(daysMatch[1]):null; let amount=amountMatch?Number(amountMatch[1].replaceAll(",","")):null; if(amount&&amountMatch?.[2]==="k")amount*=1_000;if(amount&&amountMatch?.[2]==="m")amount*=1_000_000;if(amount&&amountMatch?.[2]==="lakh")amount*=100_000;if(amount&&amountMatch?.[2]==="crore")amount*=10_000_000; return data.customers.filter((customer) => (!normalized.includes("missing email") || !customer.email) && (!normalized.includes("missing phone") || !customer.phone) && (!normalized.includes("inactive") || customer.segment === "inactive") && (!normalized.includes("haven't replied") && !normalized.includes("haven’t replied") || customer.lastContact == null || (Date.now()-new Date(customer.lastContact).getTime())/86_400_000 >= (inactivity??30)) && (amount==null || customer.opportunityValue>amount) && (!normalized.includes("vip") || customer.segment === "vip") && (!normalized.includes("risk") || customer.segment === "at-risk")); }
  async runtimeContext() { const dashboard=await this.dashboard(); return JSON.stringify({ generatedAt:dashboard.generatedAt, crmHealthScore:dashboard.healthScore, customers:dashboard.customers.slice(0,40), healthIssues:dashboard.issues, cleanupRecommendations:dashboard.issues.filter((issue)=>issue.available&&(issue.count??0)>0).map((issue)=>({issue:issue.label,count:issue.count,recommendation:issue.recommendation})), recentCRMActivity:dashboard.recentActivity.slice(0,30), governance:{recommendationOnly:true,approvalRequired:true,editingAllowed:false}, limitations:["Company and contact analysis is unavailable until authoritative repositories exist.","Never infer or fabricate CRM relationships."] }); }
}
