import type { ActivityEvent } from "../types/activity";

export const activityEvents: ActivityEvent[] = [
  {
    id: "activity-login",
    title: "User Logged In",
    description: "Amelia Chen opened Mission Control.",
    category: "Identity",
    actor: "Amelia Chen",
    organization: "Northstar Holdings",
    date: "Today",
    time: "09:42",
    iconName: "login",
  },
  {
    id: "activity-organization",
    title: "Organization Created",
    description: "Aurora Ventures entered provisioning.",
    category: "Organizations",
    actor: "Platform Operations",
    organization: "Aurora Ventures",
    date: "Today",
    time: "09:18",
    iconName: "organization",
  },
  {
    id: "activity-property",
    title: "Property Added",
    description: "Marina Residence 402 was added to inventory.",
    category: "Properties",
    actor: "Daniel Kim",
    organization: "Northstar Holdings",
    date: "Today",
    time: "08:57",
    iconName: "property",
  },
  {
    id: "activity-lead",
    title: "Lead Created",
    description: "A new qualified enquiry entered Sales Operations.",
    category: "CRM",
    actor: "Vayon OS",
    organization: "Northstar Holdings",
    date: "Today",
    time: "08:31",
    iconName: "lead",
  },
  {
    id: "activity-ai",
    title: "AI Qualified Lead",
    description: "Sales AI classified a lead as high intent.",
    category: "AI",
    actor: "Sales AI",
    organization: "Northstar Holdings",
    date: "Today",
    time: "08:24",
    iconName: "ai",
  },
  {
    id: "activity-workflow",
    title: "Workflow Published",
    description: "Lead follow-up v3 entered production.",
    category: "Automation",
    actor: "James Wilson",
    organization: "Meridian Group",
    date: "Yesterday",
    time: "17:05",
    iconName: "workflow",
  },
  {
    id: "activity-theme",
    title: "Theme Updated",
    description: "Corporate theme typography was revised.",
    category: "Themes",
    actor: "Priya Raman",
    organization: "Aurora Ventures",
    date: "Yesterday",
    time: "15:48",
    iconName: "theme",
  },
  {
    id: "activity-role",
    title: "Role Assigned",
    description: "Workspace Manager was assigned to Daniel Kim.",
    category: "Identity",
    actor: "Amelia Chen",
    organization: "Northstar Holdings",
    date: "Yesterday",
    time: "14:12",
    iconName: "role",
  },
  {
    id: "activity-permission",
    title: "Permission Changed",
    description: "Marketing publication scope was updated.",
    category: "Security",
    actor: "Platform Admin",
    organization: "AtlasOS",
    date: "Yesterday",
    time: "11:39",
    iconName: "permission",
  },
];

export const activityFilters = [
  {
    id: "activity-category",
    label: "Category",
    options: [
      { label: "Identity", value: "identity" },
      { label: "Organizations", value: "organizations" },
      { label: "AI", value: "ai" },
      { label: "Security", value: "security" },
    ],
  },
  {
    id: "activity-date",
    label: "Date",
    options: [
      { label: "Today", value: "today" },
      { label: "Yesterday", value: "yesterday" },
      { label: "Last 7 days", value: "week" },
    ],
  },
];
