export type ContactProviderCode="google_contacts"|"microsoft_people"|"exchange_contacts"|"apple_contacts"|"carddav"|"enterprise_contacts";export type ContactView="all"|"other"|"directory"|"recent"|"favorites";
export interface ProviderContact{readonly id:string;readonly provider:ContactProviderCode;readonly resourceName:string;readonly etag:string|null;readonly name:string;readonly primaryEmail:string|null;readonly emails:readonly string[];readonly phones:readonly string[];readonly company:string|null;readonly jobTitle:string|null;readonly addresses:readonly string[];readonly organization:string|null;readonly websites:readonly string[];readonly notesAvailable:boolean;readonly birthday:string|null;readonly photoUrl:string|null;readonly groups:readonly string[];readonly updatedAt:string|null}
export interface ContactPage{readonly contacts:readonly ProviderContact[];readonly nextPageToken:string|null;readonly totalItems:number|null}
export interface ContactProvider{readonly code:ContactProviderCode;status():Promise<"connected"|"not_connected"|"scope_required">;list(input:{view:ContactView;query?:string;sort?:"name"|"updated";group?:string;pageToken?:string}):Promise<ContactPage>;contact(resourceName:string):Promise<ProviderContact>}
export type ContactMatchObject="contact"|"company"|"lead"|"deal"|"communication"|"meeting"|"timeline_identity"|"context_identity";
export interface ContactIdentityCandidate{readonly objectType:ContactMatchObject;readonly objectId:string;readonly displayName:string;readonly emails:readonly string[];readonly phones:readonly string[];readonly organization:string|null}
export interface ContactMatch{readonly providerContactId:string;readonly candidate:ContactIdentityCandidate;readonly reasons:readonly("email_exact"|"phone_exact"|"organization_exact"|"name_exact")[];readonly score:number;readonly automaticMerge:false}
export interface ContactDuplicateSuggestion{readonly kind:"email"|"phone"|"provider"|"crm";readonly leftId:string;readonly rightId:string;readonly reason:string;readonly automaticMerge:false}
export interface ProviderContactLink{readonly provider:ContactProviderCode;readonly providerContactId:string;readonly targetType:ContactMatchObject;readonly targetId:string;readonly status:"proposed";readonly createdAt:string}
