export type CommunicationChannel = "gmail" | "outlook" | "whatsapp-business" | "sms" | "facebook-messenger" | "instagram-dm" | "telegram" | "signal" | "linkedin-messages" | "web-chat" | "internal-notes";
export interface ChannelDescriptor { id: CommunicationChannel; name: string; status: "disconnected" | "pending" | "connected" | "error"; capabilities: readonly ("message" | "attachment" | "template" | "schedule" | "call" | "meeting")[]; permissions: readonly string[]; workspaceId?: string; integrationAvailable: false }
export type ConversationPriority = "low" | "normal" | "high" | "urgent";
export type ConversationStatus = "open" | "pending" | "resolved" | "snoozed" | "archived";
export interface ConversationParticipant { id: string; displayName: string; kind: "contact" | "user" | "team" | "system"; address?: string }
export interface ConversationThread { id: string; workspaceId: string; subject: string; channels: readonly CommunicationChannel[]; participantIds: readonly string[]; labels: readonly string[]; priority: ConversationPriority; status: ConversationStatus; ownerId?: string; assigneeIds: readonly string[]; unreadCount: number; lastActivityAt: string; version: number }
export type TimelineItemType = "message" | "call" | "meeting" | "document" | "task" | "activity" | "note" | "email" | "attachment" | "system-event";
export interface ConversationTimelineItem { id: string; threadId: string; type: TimelineItemType; occurredAt: string; direction?: "inbound" | "outbound" | "internal"; actorId?: string; title: string; body?: string; attachmentIds: readonly string[]; metadata: Readonly<Record<string, unknown>> }
export interface ComposerDraft { id: string; threadId?: string; channel?: CommunicationChannel; richText: string; templateId?: string; attachmentIds: readonly string[]; scheduledAt?: string; mentionIds: readonly string[]; internalComment: boolean; suggestionStatus: "unavailable"; status: "draft" | "ready" | "discarded"; sendAvailable: false }
export type MeetingProvider = "google-meet" | "zoom" | "microsoft-teams";
export interface MeetingRecord { id: string; threadId?: string; provider: MeetingProvider; title: string; startsAt: string; endsAt?: string; participantIds: readonly string[]; status: "planned" | "completed" | "cancelled"; summaryStatus: "placeholder"; actionItemsStatus: "placeholder"; transcriptStatus: "placeholder"; providerAvailable: false }
export type CallDirection = "inbound" | "outbound" | "missed" | "voicemail";
export interface CallRecord { id: string; threadId?: string; direction: CallDirection; occurredAt: string; durationSeconds?: number; status: "logged" | "planned" | "completed"; recordingStatus: "placeholder"; transcriptStatus: "placeholder"; sentimentStatus: "placeholder"; providerAvailable: false }
export interface CommunicationIntelligence { threadId: string; summary?: string; priority?: ConversationPriority; urgency?: number; responseRecommendations: readonly string[]; riskIndicators: readonly string[]; followUpReminders: readonly string[]; sentimentStatus: "placeholder"; confidence: number; citations: readonly string[]; status: "placeholder" | "ready" }
export type TemplateChannel = "email" | "whatsapp" | "sms" | "internal";
export interface CommunicationTemplate { id: string; workspaceId?: string; name: string; channel: TemplateChannel; version: number; locale: string; subject?: string; body: string; variables: readonly string[]; approvalStatus: "draft" | "pending" | "approved" | "rejected"; active: boolean }
export interface InboxQuery { workspaceId?: string; channels?: readonly CommunicationChannel[]; labels?: readonly string[]; priorities?: readonly ConversationPriority[]; statuses?: readonly ConversationStatus[]; assigneeId?: string; unreadOnly?: boolean; search?: string }
export interface CommunicationDashboardSnapshot { threads: readonly ConversationThread[]; timeline: readonly ConversationTimelineItem[]; channels: readonly ChannelDescriptor[]; pendingReplies: readonly ConversationThread[]; followUps: readonly ConversationThread[]; health: { status: "placeholder" | "ready"; risks: readonly string[] }; insights: CommunicationIntelligence[] }

