"use server";
import{randomBytes}from"node:crypto";
import{cookies}from"next/headers";
import{redirect}from"next/navigation";
import{revalidatePath}from"next/cache";
import{integrationContext}from"@/features/platform/integrations/services/integration-context";
import{EnvironmentFeatureFlagProvider}from"@/lib/infrastructure/feature-flags";
import{MicrosoftOAuthService}from"./services/microsoft-oauth.service";
import{microsoftProductScopes}from"./provider/registry";
import type{MicrosoftCapability}from"./contracts";
const destinations:Record<Exclude<MicrosoftCapability,"identity">,string>={outlook_mail:"/vayon/communications/outlook",outlook_calendar:"/vayon/calendar/outlook",onedrive:"/vayon/documents/onedrive",people:"/vayon/contacts/microsoft",teams:"/vayon/communications/teams"};
export async function connectMicrosoftAction(){const ctx=await integrationContext(),flag=await new EnvironmentFeatureFlagProvider().evaluate(ctx.workspaceId,"microsoft_identity");if(!flag.enabled)redirect("/vayon/settings/integrations/microsoft?error=Microsoft%20365%20is%20disabled%20for%20this%20workspace.");const state=randomBytes(32).toString("base64url"),nonce=randomBytes(32).toString("base64url"),verifier=randomBytes(64).toString("base64url"),store=await cookies(),options={httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax"as const,path:"/integrations/microsoft/callback",maxAge:600};store.set("microsoft_oauth_state",state,options);store.set("microsoft_oauth_nonce",nonce,options);store.set("microsoft_oauth_verifier",verifier,options);redirect(new MicrosoftOAuthService().authorizationUrl({state,nonce,codeChallenge:MicrosoftOAuthService.codeChallenge(verifier)}))}
export async function disconnectMicrosoftAction(){await new MicrosoftOAuthService().disconnect();revalidatePath("/vayon/settings/integrations/microsoft");redirect("/vayon/settings/integrations/microsoft?success=Microsoft%20365%20disconnected")}
export async function connectMicrosoftCapabilityAction(form:FormData){await integrationContext();const capability=String(form.get("capability"))as Exclude<MicrosoftCapability,"identity">,scopes=microsoftProductScopes[capability],destination=destinations[capability];if(!scopes||!destination)redirect("/vayon/settings/integrations/microsoft?error=Unknown%20Microsoft%20capability");const state=randomBytes(32).toString("base64url"),nonce=randomBytes(32).toString("base64url"),verifier=randomBytes(64).toString("base64url"),store=await cookies(),options={httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax"as const,path:"/integrations/microsoft/callback",maxAge:600};store.set("microsoft_oauth_state",state,options);store.set("microsoft_oauth_nonce",nonce,options);store.set("microsoft_oauth_verifier",verifier,options);store.set("microsoft_oauth_product",capability,options);redirect(new MicrosoftOAuthService().authorizationUrl({state,nonce,codeChallenge:MicrosoftOAuthService.codeChallenge(verifier),additionalScopes:scopes}))}
