import { CanonicalEventFactory } from "@/features/platform/business-timeline/ingestion/event.factory";import type { EventFactoryContext,EventFactoryInput } from "@/features/platform/business-timeline/ingestion/contracts";import { InMemoryAppendOnlyTimelineStore } from "@/features/platform/business-timeline/storage/in-memory-timeline.store";import type { CanonicalBusinessEvent,TimelineObjectRef } from "@/features/platform/business-timeline/domain/contracts";import { auroraEmployees } from "../people/employees";import { auroraProperties } from "../property-portfolio/properties";import { auroraDeals,auroraDocuments,auroraLeads,auroraMeetings,auroraTasks } from "../sales-operations/records";import { auroraCampaigns,auroraCommunications } from "./records";import type { AuroraTimelineHistory } from "./contracts";
const factory=new CanonicalEventFactory(),source={kind:"domain-service" as const,producerId:"aurora-demo-history",module:"aurora-demo-workspace",producerVersion:"1.8.5",trust:"system" as const},owner={id:"aurora-demo-workspace",kind:"workspace" as const},ref=(objectId:string,objectType:string,displayHint?:string):TimelineObjectRef=>({objectId,objectType,displayHint}),context=(actorId:string):EventFactoryContext=>({organizationId:"aurora-realty-group",workspaceId:"aurora-demo-workspace",partitionKey:"aurora-realty-group:aurora-demo-workspace",actor:{id:actorId,kind:"user",displayHint:auroraEmployees.find(item=>item.id===actorId)?.name},owner,source});
type Pending={readonly order:number;readonly proposal:ReturnType<CanonicalEventFactory["create"]>};const pending:Pending[]=[];let order=0;
function add(actorId:string,input:EventFactoryInput){pending.push({order:order++,proposal:factory.create(context(actorId),input)})}
const related=(values:readonly (readonly [string,string,string])[])=>values.map(([objectId,objectType,role])=>({object:ref(objectId,objectType),role}));
for(const campaign of auroraCampaigns)add(campaign.ownerId,{action:"campaign-saved",subject:ref(campaign.id,"campaign",campaign.name),relatedObjects:related([...campaign.relatedPropertyIds.map(id=>[id,"property","property"] as const),...campaign.influencedLeadIds.map(id=>[id,"lead","lead"] as const)]),summary:`Campaign recorded: ${campaign.name}`,payload:{status:campaign.status,budgetBand:campaign.budgetBand},occurredAt:campaign.createdAt,correlationId:`campaign:${campaign.id}`,idempotencyKey:`campaign-saved:${campaign.id}`});
for(const [index,property] of auroraProperties.entries())add(property.assignedSalesManagerId,{action:"property-published",subject:ref(property.id,"property",property.name),relatedObjects:related([[property.developerCompanyId,"company","account"]]),summary:`Property inventory published: ${property.name}`,payload:{status:property.status,constructionStatus:property.constructionStatus},occurredAt:new Date(Date.UTC(2026,1,15+(index%14),10)).toISOString(),correlationId:`property:${property.id}`,idempotencyKey:`property-published:${property.id}`});
for(const [index,lead] of auroraLeads.entries()){const campaign=auroraCampaigns[Math.floor(index/6)]!;add(lead.salesAgentId,{action:"lead-created",subject:ref(lead.id,"lead",lead.title),relatedObjects:related([[lead.preferredPropertyId,"property","property"],[lead.contactId,"contact","recipient"],[campaign.id,"campaign","campaign"]]),summary:`Lead created: ${lead.title}`,payload:{source:lead.source,priority:lead.priority},occurredAt:new Date(Date.UTC(2026,2+(index%2),1+(index%28),9)).toISOString(),correlationId:`journey:${lead.id}`,causationId:`campaign:${campaign.id}`,idempotencyKey:`lead-created:${lead.id}`})}
for(const communication of auroraCommunications)add(communication.employeeId,{action:"communication-recorded",subject:ref(communication.id,"communication",communication.subject),relatedObjects:related([[communication.leadId,"lead","lead"],[communication.dealId,"deal","deal"],[communication.contactId,"contact","recipient"],[communication.companyId,"company","account"]]),summary:`Communication logged: ${communication.channel}`,payload:{channel:communication.channel,direction:communication.direction,status:communication.status},occurredAt:communication.occurredAt,correlationId:`journey:${communication.leadId}`,causationId:`lead:${communication.leadId}`,idempotencyKey:`communication-recorded:${communication.id}`});
for(const meeting of auroraMeetings)add(meeting.employeeId,{action:"meeting-scheduled",subject:ref(`calendar:${meeting.id}`,"calendar",meeting.title),relatedObjects:related([[meeting.id,"meeting","meeting"],[meeting.leadId,"lead","lead"],[meeting.dealId,"deal","deal"],[meeting.propertyId,"property","property"]]),summary:`Meeting scheduled: ${meeting.title}`,payload:{kind:meeting.kind,location:meeting.location},occurredAt:new Date(Date.UTC(2026,5,1+(Number(meeting.id.split("-").at(-1))%28),10)).toISOString(),correlationId:`journey:${meeting.leadId}`,causationId:`communication:${meeting.leadId}`,idempotencyKey:`meeting-scheduled:${meeting.id}`});
for(const [index,document] of auroraDocuments.entries()){const deal=auroraDeals.find(item=>item.id===document.dealId)!;add(deal.salesAgentId,{action:"document-uploaded",subject:ref(document.id,"document",document.title),relatedObjects:related([[document.dealId,"deal","deal"],[document.leadId,"lead","lead"],[document.propertyId,"property","property"]]),summary:`Document metadata recorded: ${document.kind}`,payload:{kind:document.kind,status:document.status},occurredAt:new Date(Date.UTC(2026,6,1+(index%28),11)).toISOString(),correlationId:`journey:${document.leadId}`,causationId:`meeting:${document.dealId}`,idempotencyKey:`document-uploaded:${document.id}`})}
for(const task of auroraTasks.filter(item=>item.status==="completed"))add(task.employeeId,{action:"task-completed",subject:ref(task.id,"task",task.title),relatedObjects:related([[task.dealId,"deal","deal"],[task.leadId,"lead","lead"]]),summary:`Task completed: ${task.kind}`,payload:{kind:task.kind,status:task.status},occurredAt:new Date(Date.UTC(2026,6,20+(Number(task.id.split("-").at(-1))%10),12)).toISOString(),correlationId:`journey:${task.leadId}`,idempotencyKey:`task-completed:${task.id}`});
for(const deal of auroraDeals.filter(item=>item.stage==="closed-won"))add(deal.salesManagerId,{action:"deal-won",subject:ref(deal.id,"deal",deal.title),relatedObjects:related([[deal.leadId,"lead","lead"],[deal.propertyId,"property","property"],[deal.companyId,"company","account"]]),summary:`Deal closed won: ${deal.title}`,payload:{stage:deal.stage},occurredAt:new Date(Date.UTC(2026,7,1+(Number(deal.id.split("-").at(-1))%12),14)).toISOString(),correlationId:`journey:${deal.leadId}`,causationId:`document:${deal.id}`,idempotencyKey:`deal-won:${deal.id}`,severity:"success"});
pending.sort((a,b)=>a.proposal.occurredAt.localeCompare(b.proposal.occurredAt)||a.order-b.order);const store=new InMemoryAppendOnlyTimelineStore((()=>{let value=0;return()=>`aurora-event-${++value}`})(),()=>new Date("2026-08-13T12:00:00.000Z"));for(const item of pending)store.append(item.proposal);const events=Object.freeze(store.all()) as readonly CanonicalBusinessEvent[];
export const auroraTimelineHistory:AuroraTimelineHistory=Object.freeze({events,firstOccurredAt:events[0]!.occurredAt,lastOccurredAt:events.at(-1)!.occurredAt,canonical:true,persistence:"in-memory"});
