import { auroraRealtyGroup } from "../config/aurora-realty-group";
import { auroraEmployees } from "./employees";
import type { AuroraEmployee, AuroraEmployeeId, AuroraPeopleWorkspace, OrganizationChartGroup, OrganizationChartModel, OrganizationChartNode, OrganizationChartView } from "./contracts";

const byId=new Map(auroraEmployees.map(employee=>[employee.id,employee]));
function depth(employee:AuroraEmployee,seen=new Set<AuroraEmployeeId>()):number{if(!employee.reportsTo)return 0;if(seen.has(employee.id))throw new Error(`Circular Aurora reporting relationship at ${employee.id}.`);const manager=byId.get(employee.reportsTo);if(!manager)throw new Error(`Missing Aurora manager ${employee.reportsTo}.`);seen.add(employee.id);return 1+depth(manager,seen)}
function label(view:OrganizationChartView,id:string){if(view==="department")return auroraRealtyGroup.departments.find(item=>item.id===id)?.name??id;if(view==="office")return auroraRealtyGroup.offices.find(item=>item.id===id)?.name??id;if(view==="business-unit")return auroraRealtyGroup.businessUnits.find(item=>item.id===id)?.name??id;return id}
export class AuroraOrganizationChart {
  readonly employees=auroraEmployees;
  constructor(){const ids=new Set<string>();for(const employee of this.employees){if(ids.has(employee.id))throw new Error(`Duplicate Aurora employee ${employee.id}.`);ids.add(employee.id);if(employee.reportsTo&&!byId.has(employee.reportsTo))throw new Error(`Missing Aurora manager ${employee.reportsTo}.`);depth(employee)}}
  nodes():readonly OrganizationChartNode[]{return this.employees.map(employee=>Object.freeze({employee,manager:employee.reportsTo?byId.get(employee.reportsTo):undefined,directReports:this.employees.filter(item=>item.reportsTo===employee.id),depth:depth(employee)}))}
  model(view:OrganizationChartView):OrganizationChartModel{if(view==="reporting")return Object.freeze({view,groups:[{id:"reporting-tree",label:"Reporting tree",employees:[...this.employees].sort((a,b)=>depth(a)-depth(b)||a.name.localeCompare(b.name))}],nodes:this.nodes()});const grouped=new Map<string,AuroraEmployee[]>();for(const employee of this.employees){const keys=view==="department"?[employee.departmentId]:view==="office"?[employee.officeId]:employee.businessUnitIds.length?employee.businessUnitIds:["unassigned"];for(const key of keys)grouped.set(key,[...(grouped.get(key)??[]),employee])}const groups:OrganizationChartGroup[]=[...grouped].map(([id,employees])=>Object.freeze({id,label:label(view,id),employees:Object.freeze(employees)}));return Object.freeze({view,groups:Object.freeze(groups),nodes:this.nodes()})}
  peopleWorkspace():AuroraPeopleWorkspace{const leadership=this.employees.filter(employee=>employee.departmentId==="executive"||employee.title.endsWith("Director")),departmentHeads=auroraRealtyGroup.departments.map(department=>this.employees.find(employee=>employee.departmentId===department.id&&["Director","Manager","Counsel","Administrator","CEO","COO"].some(role=>employee.title.includes(role)))).filter((employee):employee is AuroraEmployee=>!!employee);return Object.freeze({leadership:Object.freeze(leadership),departmentHeads:Object.freeze(departmentHeads),recentJoiners:Object.freeze([]),birthdays:Object.freeze([]),announcements:Object.freeze([]),persistence:"none",analytics:"none"})}
}
export const auroraOrganizationChart=new AuroraOrganizationChart();
