"use server";
import {revalidatePath} from "next/cache";
import {CreativeStudioService} from "./service";
import {audiences,campaignTypes,creativePlatforms,type CampaignBrief} from "./domain";
import {CreativeGenerationService} from "./generation.service";
import {creativeStudioAccess} from "./access.service";
import {GrowthStudioService} from "./growth.service";
export async function createCreativeDraftAction(formData:FormData){const service=await CreativeStudioService.production();if(!service)throw new Error("Creative Studio Beta access is required.");const campaignType=String(formData.get("campaignType")),selectedAudiences=formData.getAll("audience").map(String),platforms=formData.getAll("platform").map(String);if(!campaignTypes.includes(campaignType as never)||selectedAudiences.some(x=>!audiences.includes(x as never))||platforms.some(x=>!creativePlatforms.includes(x as never)))throw new Error("Invalid campaign selection.");const brief:CampaignBrief={projectId:String(formData.get("projectId")),campaignType:campaignType as CampaignBrief["campaignType"],audiences:selectedAudiences as CampaignBrief["audiences"],platforms:platforms as CampaignBrief["platforms"],language:String(formData.get("language")??"English").slice(0,40),objective:String(formData.get("objective")??"").slice(0,1000)};await service.saveDraft(brief,String(formData.get("name")??"Untitled campaign").slice(0,160));revalidatePath("/vayon/creative-studio");}
export async function generateCreativeAssetAction(formData:FormData){await new CreativeGenerationService().assistant(String(formData.get("prompt")??""),String(formData.get("projectId")??"")||undefined);revalidatePath("/vayon/creative-studio/assistant");}
export async function creativeAssistantChatAction(_previous:{message:string;jobId:string|null},formData:FormData){const result=await new CreativeGenerationService().assistant(String(formData.get("prompt")??""),String(formData.get("projectId")??"")||undefined);revalidatePath("/vayon/creative-studio/assistant");return{message:`${result.intent.intentSummary}. ${result.message}`,jobId:result.jobId};}
export async function autosaveCreativeEditorAction(formData:FormData){const access=await creativeStudioAccess();if(!access)throw new Error("Creative Studio Beta access is required.");const raw=String(formData.get("elements")??"[]"),elements=JSON.parse(raw)as unknown;if(!Array.isArray(elements)||raw.length>100000)throw new Error("Invalid editor document.");const{error}=await access.client.rpc("autosave_creative_editor",{p_asset_id:String(formData.get("assetId")),p_expected_revision:Number(formData.get("revision")),p_elements:elements});if(error)throw error;revalidatePath(`/vayon/creative-studio/editor/${String(formData.get("assetId"))}`);}
export async function growthCampaignChatAction(_previous:{message:string;campaignId:string|null},formData:FormData){const result=await new GrowthStudioService().assistant(String(formData.get("prompt")??""),String(formData.get("projectId")??"")||undefined,String(formData.get("language")??"English"));revalidatePath("/vayon/creative-studio/growth");revalidatePath("/vayon/creative-studio/packs");return result;}
