import "server-only";
import {InventoryService} from "@/features/vayon/property-platform/inventory/service";
import {EnterpriseOrganizationService} from "@/features/platform/organization/services/organization.service";
import {creativeStudioAccess} from "./access.service";
import {SupabaseCreativeStudioRepository} from "./repository";
import {GovernedCreativeProvider} from "./providers";
import {templateCategories,type CampaignBrief,type CreativeBrandKit} from "./domain";
export class CreativeStudioService {
  private constructor(private repository:SupabaseCreativeStudioRepository,private source:"administrator"|"internal"|"selected-beta"|"environment"){}
  static async production(){const access=await creativeStudioAccess();if(!access)return null;return new CreativeStudioService(new SupabaseCreativeStudioRepository(access.client,access.organizationId,access.workspaceId),access.source)}
  async snapshot(){const[campaigns,assets,brandKits]=await Promise.all([this.repository.campaigns(),this.repository.assets(),this.repository.brandKits()]);return{campaigns,assets,brandKits,templates:templateCategories.map((category,index)=>({id:`template-${index+1}`,category,name:`${category} campaign system`,editable:true as const})),analytics:[{label:"Drafts",value:String(campaigns.filter(x=>x.status==="draft").length),measured:true},{label:"Published",value:"0 · publishing disabled",measured:true},{label:"Templates",value:String(templateCategories.length),measured:true},{label:"Brand Kits",value:String(brandKits.length),measured:true},{label:"Creative Analytics",value:assets.length?`${assets.length} governed assets`:"Awaiting asset history",measured:Boolean(assets.length)}],access:{enabled:true as const,source:this.source},governance:{draftOnly:true as const,approvalRequired:true as const,livePublishing:false as const,externalRendering:false as const,tenantScoped:true as const}};}
  async projectContext(){const inventoryService=await InventoryService.production(),[inventory,organization]=await Promise.all([inventoryService.snapshot(),new EnterpriseOrganizationService().snapshot()]);return{inventory,organization};}
  async preview(brief:CampaignBrief){const{inventory,organization}=await this.projectContext(),project=inventory.projects.find(x=>x.id===brief.projectId);if(!project)throw new Error("Select an authoritative inventory project.");const units=inventory.units.filter(x=>x.projectId===project.id&&x.status==="available"),prices=units.map(x=>x.offerPrice??x.price),brand:CreativeBrandKit=(await this.repository.brandKits())[0]??{id:"organization-brand",name:organization.profile.name,logoPath:organization.profile.logoPath??undefined,colors:[organization.profile.branding.primary,organization.profile.branding.accent].filter(Boolean)as string[],typography:[],fonts:[],icons:[],watermarks:[],phone:organization.profile.phone??undefined,address:Object.values(organization.profile.address).join(", "),website:organization.profile.website??undefined,socialLinks:{},tone:"Professional real estate",version:organization.profile.version};const generated=new GovernedCreativeProvider().generate({brief,projectName:project.name,developer:project.developer,location:`${project.city}, ${project.state}`,availableInventory:units.length,priceRange:prices.length?`${Math.min(...prices)}–${Math.max(...prices)} ${units[0]?.currency??organization.profile.currency}`:"Pricing unavailable",brandKit:brand});return{project,brand,generated,source:{inventory:units,pricing:inventory.prices.filter(x=>x.projectId===project.id),documents:inventory.documents.filter(x=>x.projectId===project.id),organization:organization.profile},draftOnly:true as const};}
  async saveDraft(brief:CampaignBrief,name:string){const preview=await this.preview(brief);return this.repository.saveDraft({brief,name,projectName:preview.project.name,developer:preview.project.developer,payload:preview.generated});}
}
