import "server-only";
import type { GoogleCalendarRepositoryContract } from "../contracts/repository";
import type { CalendarEventInput,CalendarIntelligence,CalendarQuery,CrmReference,FreeBusyQuery,GoogleCalendarHealth,WatchRequest } from "../domain/models";
import { GoogleCalendarRepository } from "../repositories/google-calendar.repository";

export const calendarWorkflowGovernance={stages:["Draft","Approval","Execution Request","Integration Platform","Google Calendar Provider","Timeline"],approvalRequired:true,bypassAllowed:false} as const;
export const calendarEventTypes=["calendar.connected","calendar.disconnected","meeting.created","meeting.updated","meeting.deleted","meeting.linked","availability.checked"] as const;
export const calendarTimelineEvents=["Meeting Created","Meeting Updated","Meeting Deleted","Attendee Changed","Meeting Linked","Calendar Connected","Calendar Disconnected"] as const;
export const calendarNotifications=["meeting invitations","meeting updates","approval required","conflicts","connection failures"] as const;

export class GoogleCalendarPlatformService {
  constructor(private readonly repository:GoogleCalendarRepositoryContract=new GoogleCalendarRepository()){}
  async health():Promise<GoogleCalendarHealth>{const started=Date.now();try{const status=await this.repository.status(),now=new Date().toISOString();return{state:status==="connected"?"healthy":status==="scope_required"?"authorization_required":status==="unavailable"?"unavailable":"needs_attention",connection:status==="connected"?"connected":status==="scope_required"?"authorization_required":status==="unavailable"?"unavailable":"disconnected",latencyMs:Date.now()-started,quota:"unknown",syncStatus:status==="connected"?"live":status==="unavailable"?"unavailable":"not_connected",lastSync:status==="connected"?now:null,lastRefresh:null,version:"1.0.0",...(status!=="connected"&&{reason:status==="scope_required"?"Google Calendar permissions must be granted.":status==="unavailable"?"Google Calendar health could not be checked.":"Google Calendar is not connected."})}}catch{return{state:"unavailable",connection:"unavailable",latencyMs:Date.now()-started,quota:"unknown",syncStatus:"unavailable",lastSync:null,lastRefresh:null,version:"1.0.0",reason:"Google Calendar is temporarily unavailable."}}}
  calendars(){return this.repository.calendars()} calendar(id:string){return this.repository.calendar(id)} events(query:CalendarQuery){return this.repository.events(query)} event(calendarId:string,eventId:string){return this.repository.event(calendarId,eventId)} create(input:CalendarEventInput){return this.repository.create(input)} update(id:string,input:CalendarEventInput){return this.repository.update(id,input)} remove(calendarId:string,id:string){return this.repository.remove(calendarId,id)} move(calendarId:string,id:string,destination:string){return this.repository.move(calendarId,id,destination)} async attendees(calendarId:string,eventId:string){return(await this.event(calendarId,eventId)).attendees} availability(query:FreeBusyQuery){return this.repository.availability(query)} watch(input:WatchRequest){return this.repository.watch(input)} stopWatching(channelId:string,resourceId:string){return this.repository.stopWatching(channelId,resourceId)} refresh(){return this.repository.refresh()} link(calendarId:string,eventId:string,reference:CrmReference){return this.repository.link(calendarId,eventId,reference)}
  intelligence():CalendarIntelligence{return{state:"unavailable",summary:null,suggestedAttendees:[],conflicts:[],suggestedTime:null,followUp:null,priority:null,recommendations:[],reason:"AI provider unavailable. No calendar intelligence was generated."}}
}
