import type { ChannelRegistry, CommunicationDashboardService, CommunicationHubStorage, CommunicationIntelligenceService, ConversationComposer, ConversationTimeline, MeetingCenter, CallCenter, TemplateRegistry, UnifiedInbox } from "../contracts/ports";
import type { ChannelDescriptor, CommunicationIntelligence, CommunicationTemplate, ComposerDraft, ConversationThread, InboxQuery } from "../domain/contracts";
export const channelDescriptors: readonly ChannelDescriptor[] = ["gmail", "outlook", "whatsapp-business", "sms", "facebook-messenger", "instagram-dm", "telegram", "signal", "linkedin-messages", "web-chat", "internal-notes"].map(id => ({ id: id as ChannelDescriptor["id"], name: id.replaceAll("-", " "), status: "disconnected", capabilities: [], permissions: [], integrationAvailable: false }));
export class InMemoryChannelRegistry implements ChannelRegistry { private values = new Map<ChannelDescriptor["id"], ChannelDescriptor>(); constructor(initial: readonly ChannelDescriptor[] = channelDescriptors) { initial.forEach(item => this.register(item)) } register(value: ChannelDescriptor) { this.values.set(value.id, { ...value, integrationAvailable: false }) } list() { return [...this.values.values()] } }
export class InMemoryUnifiedInbox implements UnifiedInbox { constructor(private readonly values: readonly ConversationThread[] = []) {} search(query: InboxQuery) { const term = query.search?.toLowerCase(); return this.values.filter(item => (!query.workspaceId || item.workspaceId === query.workspaceId) && (!query.channels?.length || item.channels.some(channel => query.channels?.includes(channel))) && (!query.labels?.length || item.labels.some(label => query.labels?.includes(label))) && (!query.priorities?.length || query.priorities.includes(item.priority)) && (!query.statuses?.length || query.statuses.includes(item.status)) && (!query.assigneeId || item.assigneeIds.includes(query.assigneeId)) && (!query.unreadOnly || item.unreadCount > 0) && (!term || item.subject.toLowerCase().includes(term))).sort((a, b) => b.lastActivityAt.localeCompare(a.lastActivityAt)) } get(id: string) { return this.values.find(item => item.id === id) } }
export class InMemoryConversationTimeline implements ConversationTimeline { constructor(private readonly values: CommunicationHubStorage["timeline"] extends () => infer T ? T : never = []) {} list(threadId: string) { return this.values.filter(item => item.threadId === threadId).sort((a, b) => a.occurredAt.localeCompare(b.occurredAt)) } }
export class ArchitectureConversationComposer implements ConversationComposer { create(draft: ComposerDraft) { return { ...draft, suggestionStatus: "unavailable" as const, status: "draft" as const, sendAvailable: false as const } } validate(draft: ComposerDraft) { return [...(!draft.richText.trim() ? ["Message content is required."] : []), ...(!draft.channel && !draft.internalComment ? ["A channel is required."] : [])] } send(): never { throw new Error("Sending is unavailable in the Communication Hub architecture release.") } }
export class InMemoryMeetingCenter implements MeetingCenter { constructor(private readonly values: ReturnType<CommunicationHubStorage["meetings"]> = []) {} list() { return this.values } }
export class InMemoryCallCenter implements CallCenter { constructor(private readonly values: ReturnType<CommunicationHubStorage["calls"]> = []) {} list() { return this.values } }
export class PlaceholderCommunicationIntelligence implements CommunicationIntelligenceService { async analyze(thread: ConversationThread): Promise<CommunicationIntelligence> { return { threadId: thread.id, responseRecommendations: [], riskIndicators: [], followUpReminders: [], sentimentStatus: "placeholder", confidence: 0, citations: [], status: "placeholder" } } }
export class InMemoryTemplateRegistry implements TemplateRegistry { private values: CommunicationTemplate[] = []; register(value: CommunicationTemplate) { this.values = [...this.values.filter(item => !(item.id === value.id && item.version === value.version && item.locale === value.locale)), value] } resolve(id: string, locale?: string, version?: number) { return this.values.filter(item => item.id === id && item.active && (!locale || item.locale === locale) && (!version || item.version === version)).sort((a, b) => b.version - a.version)[0] } list() { return this.values } }
export class ArchitectureCommunicationDashboard implements CommunicationDashboardService { constructor(private readonly inbox: UnifiedInbox, private readonly timeline: ConversationTimeline, private readonly channels: ChannelRegistry, private readonly intelligence: CommunicationIntelligenceService) {} async snapshot(query: InboxQuery = {}) { const threads = this.inbox.search(query), insights = await Promise.all(threads.map(thread => this.intelligence.analyze(thread))); return { threads, timeline: threads.flatMap(thread => this.timeline.list(thread.id)), channels: this.channels.list(), pendingReplies: threads.filter(thread => thread.status === "pending"), followUps: [], health: { status: "placeholder" as const, risks: [] }, insights } } }
