import type {
  SearchResult,
  SearchResultCategory,
} from "../types/search";

export const searchCategories: SearchResultCategory[] = [
  "Applications",
  "Organizations",
  "Users",
  "Properties",
  "Leads",
  "Commands",
  "Pages",
  "Reports",
  "Documents",
  "Settings",
];

export const searchResults: SearchResult[] = [
  {
    id: "search-application",
    title: "LeadEstate AI",
    description: "AI-native real estate operating application.",
    category: "Applications",
    metadata: "Application",
    iconName: "application",
  },
  {
    id: "search-organization",
    title: "Northstar Holdings",
    description: "Active organization with six workspaces.",
    category: "Organizations",
    metadata: "Organization",
    iconName: "organization",
  },
  {
    id: "search-user",
    title: "Amelia Chen",
    description: "Organization Owner at Northstar Holdings.",
    category: "Users",
    metadata: "User",
    iconName: "user",
  },
  {
    id: "search-property",
    title: "Marina Residence 402",
    description: "Available property in LeadEstate Global.",
    category: "Properties",
    metadata: "Property",
    iconName: "property",
  },
  {
    id: "search-lead",
    title: "High Intent Leads",
    description: "Saved lead view in Sales Operations.",
    category: "Leads",
    metadata: "Lead view",
    iconName: "lead",
  },
  {
    id: "search-command",
    title: "Create organization",
    description: "Open the organization provisioning interface.",
    category: "Commands",
    metadata: "Command",
    iconName: "command",
  },
  {
    id: "search-page",
    title: "Portfolio Launch",
    description: "Draft landing page in Marketing Studio.",
    category: "Pages",
    metadata: "Page",
    iconName: "page",
  },
  {
    id: "search-report",
    title: "AI Workforce Performance",
    description: "Governed quality and usage report.",
    category: "Reports",
    metadata: "Report",
    iconName: "report",
  },
  {
    id: "search-document",
    title: "AtlasOS Security Overview",
    description: "Internal platform security document.",
    category: "Documents",
    metadata: "Document",
    iconName: "document",
  },
  {
    id: "search-settings",
    title: "Workspace localization",
    description: "Language, timezone, and regional formats.",
    category: "Settings",
    metadata: "Settings",
    iconName: "settings",
  },
];
