import type { ContextObjectIdentity, SupportedContextObjectType } from "@/features/platform/context-engine/domain/contracts";
import type { AuroraCompanyId, AuroraContactId } from "../crm-network/contracts";
import type { AuroraBusinessUnitId, AuroraEmployeeId } from "../people/contracts";
import type { AuroraPropertyId } from "../property-portfolio/contracts";
export type AuroraLeadId=`aurora-lead-${number}`;export type AuroraDealId=`aurora-deal-${number}`;export type AuroraTaskId=`aurora-task-${number}`;export type AuroraMeetingId=`aurora-meeting-${number}`;export type AuroraDocumentId=`aurora-document-${number}`;export type AuroraCalendarEventId=`aurora-calendar-${number}`;
export type LeadSource="website"|"referral"|"walk-in"|"facebook"|"instagram"|"google-ads"|"property-portal"|"channel-partner"|"corporate"|"repeat-customer";
export type LeadStatus="new"|"contacted"|"qualified"|"nurturing"|"converted"|"closed";export type Priority="low"|"normal"|"high"|"urgent";export type BuyingTimeline="immediate"|"within-30-days"|"1-to-3-months"|"3-to-6-months"|"exploring";
export type DealStage="new"|"qualified"|"site-visit"|"negotiation"|"documentation"|"booked"|"closed-won"|"closed-lost";
export type TaskKind="call-customer"|"arrange-site-visit"|"prepare-quotation"|"collect-documents"|"follow-up"|"legal-review"|"payment-reminder"|"manager-approval";
export type MeetingKind="property-visit"|"sales-meeting"|"internal-review"|"developer-meeting"|"customer-meeting";export type DocumentKind="agreement"|"quotation"|"brochure"|"floor-plan"|"payment-schedule"|"kyc";
export interface SalesOperationIdentity {readonly namespace:"aurora-demo-sales";readonly objectId:string;readonly objectType:SupportedContextObjectType;readonly context:ContextObjectIdentity;readonly timelineEvents:readonly never[]}
export interface Assignment {readonly salesAgentId:AuroraEmployeeId;readonly salesManagerId:AuroraEmployeeId;readonly officeId:string;readonly businessUnitId:AuroraBusinessUnitId}
export interface AuroraLead extends Assignment {readonly id:AuroraLeadId;readonly title:string;readonly companyId?:AuroraCompanyId;readonly contactId:AuroraContactId;readonly preferredPropertyId:AuroraPropertyId;readonly status:LeadStatus;readonly priority:Priority;readonly budgetRange:string;readonly buyingTimeline:BuyingTimeline;readonly source:LeadSource;readonly createdAt:string;readonly identity:SalesOperationIdentity}
export interface AuroraDeal extends Assignment {readonly id:AuroraDealId;readonly title:string;readonly leadId:AuroraLeadId;readonly propertyId:AuroraPropertyId;readonly developerCompanyId:AuroraCompanyId;readonly companyId:AuroraCompanyId;readonly primaryContactId:AuroraContactId;readonly stage:DealStage;readonly openedAt:string;readonly identity:SalesOperationIdentity}
export interface AuroraTask {readonly id:AuroraTaskId;readonly title:string;readonly kind:TaskKind;readonly dealId:AuroraDealId;readonly leadId:AuroraLeadId;readonly employeeId:AuroraEmployeeId;readonly dueAt:string;readonly status:"open"|"completed";readonly priority:Priority;readonly identity:SalesOperationIdentity}
export interface AuroraMeeting {readonly id:AuroraMeetingId;readonly title:string;readonly kind:MeetingKind;readonly dealId:AuroraDealId;readonly leadId:AuroraLeadId;readonly propertyId:AuroraPropertyId;readonly employeeId:AuroraEmployeeId;readonly contactId:AuroraContactId;readonly startsAt:string;readonly endsAt:string;readonly location:string;readonly identity:SalesOperationIdentity}
export interface AuroraDocument {readonly id:AuroraDocumentId;readonly title:string;readonly kind:DocumentKind;readonly dealId:AuroraDealId;readonly leadId:AuroraLeadId;readonly propertyId:AuroraPropertyId;readonly companyId:AuroraCompanyId;readonly status:"metadata-placeholder";readonly fileReference?:never;readonly identity:SalesOperationIdentity}
export interface AuroraCalendarEvent {readonly id:AuroraCalendarEventId;readonly title:string;readonly kind:"meeting"|"task"|"site-visit"|"internal-review";readonly meetingId?:AuroraMeetingId;readonly taskId?:AuroraTaskId;readonly startsAt:string;readonly endsAt:string;readonly identity:SalesOperationIdentity}
export interface DeterministicAdvisoryExample {readonly id:string;readonly rule:string;readonly subjectId:AuroraDealId|AuroraTaskId;readonly observation:string;readonly generated:false;readonly executable:false}
export interface SalesOperationsHomeProjection {readonly pipelineOverview:readonly AuroraDeal[];readonly upcomingMeetings:readonly AuroraMeeting[];readonly todaysTasks:readonly AuroraTask[];readonly propertiesUnderNegotiation:readonly AuroraDeal[];readonly recentWins:readonly AuroraDeal[];readonly recentActivities:readonly (AuroraTask|AuroraMeeting)[];readonly analytics:"none"}
