-- Sprint 8: manually reviewed and applied Supabase foundation. Never auto-apply.
create extension if not exists pgcrypto;
create table if not exists public.roles(id uuid primary key default gen_random_uuid(),code text unique not null,name text not null,scope text not null,created_at timestamptz not null default now());
insert into public.roles(code,name,scope)values('super_admin','Super Admin','platform'),('organization_owner','Organization Owner','organization'),('organization_admin','Organization Admin','organization'),('branch_manager','Branch Manager','workspace'),('sales_manager','Sales Manager','workspace'),('agent','Agent','own'),('viewer','Viewer','organization')on conflict(code)do update set name=excluded.name,scope=excluded.scope;
create table if not exists public.organizations(id uuid primary key default gen_random_uuid(),name text not null,country char(2)not null,currency char(3)not null,timezone text not null,language text not null,logo_path text,status text not null default'active',created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.organization_members(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),user_id uuid not null references auth.users(id),role_id uuid not null references public.roles(id),status text not null default'active',created_at timestamptz not null default now(),unique(organization_id,user_id));
create table if not exists public.workspaces(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,office text,branch text,status text not null default'active',created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.workspace_members(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),organization_id uuid not null references public.organizations(id),user_id uuid not null references auth.users(id),role_id uuid not null references public.roles(id),status text not null default'active',created_at timestamptz not null default now(),unique(workspace_id,user_id));
create table if not exists public.invitations(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),workspace_id uuid references public.workspaces(id),email text not null,name text not null,role_id uuid not null references public.roles(id),status text not null default'pending',token_hash text not null default encode(gen_random_bytes(32),'hex'),expires_at timestamptz not null default now()+interval'7 days',invited_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(organization_id,email,status));
alter table public.organizations enable row level security;alter table public.organization_members enable row level security;alter table public.workspaces enable row level security;alter table public.workspace_members enable row level security;alter table public.invitations enable row level security;alter table public.roles enable row level security;
create or replace function public.is_organization_member(p_organization_id uuid)returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from organization_members where organization_id=p_organization_id and user_id=auth.uid() and status='active')$$;
create policy "roles_authenticated_read" on public.roles for select to authenticated using(true);
create policy "organizations_member_read" on public.organizations for select to authenticated using(public.is_organization_member(id));
create policy "organization_members_member_read" on public.organization_members for select to authenticated using(public.is_organization_member(organization_id));
create policy "workspaces_member_read" on public.workspaces for select to authenticated using(public.is_organization_member(organization_id));
create policy "workspace_members_member_read" on public.workspace_members for select to authenticated using(public.is_organization_member(organization_id));
create policy "invitations_member_read" on public.invitations for select to authenticated using(public.is_organization_member(organization_id));
create or replace function public.complete_organization_onboarding(p_organization_name text,p_country text,p_currency text,p_timezone text,p_language text,p_workspace_name text,p_office text,p_branch text,p_invitations jsonb default'[]')returns jsonb language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_org uuid;v_workspace uuid;v_owner_role uuid;v_item jsonb;v_role uuid;begin if v_user is null then raise exception'authentication required';end if;if exists(select 1 from organization_members where user_id=v_user and status='active')then raise exception'user already belongs to an organization';end if;select id into v_owner_role from roles where code='organization_owner';insert into organizations(name,country,currency,timezone,language,created_by)values(trim(p_organization_name),upper(p_country),upper(p_currency),p_timezone,p_language,v_user)returning id into v_org;insert into organization_members(organization_id,user_id,role_id)values(v_org,v_user,v_owner_role);insert into workspaces(organization_id,name,office,branch,created_by)values(v_org,trim(p_workspace_name),nullif(trim(p_office),''),nullif(trim(p_branch),''),v_user)returning id into v_workspace;insert into workspace_members(workspace_id,organization_id,user_id,role_id)values(v_workspace,v_org,v_user,v_owner_role);for v_item in select*from jsonb_array_elements(coalesce(p_invitations,'[]'))loop select id into v_role from roles where code=v_item->>'role' and code not in('super_admin','organization_owner');if v_role is not null then insert into invitations(organization_id,workspace_id,email,name,role_id,invited_by)values(v_org,v_workspace,lower(v_item->>'email'),v_item->>'name',v_role,v_user)on conflict do nothing;end if;end loop;return jsonb_build_object('organization_id',v_org,'workspace_id',v_workspace);end$$;
revoke all on function public.complete_organization_onboarding(text,text,text,text,text,text,text,text,jsonb)from public;grant execute on function public.complete_organization_onboarding(text,text,text,text,text,text,text,text,jsonb)to authenticated;

