-- Sprint 9 additive migration. Review and apply manually.
create table public.properties(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),workspace_id uuid not null references public.workspaces(id),reference text not null,title text not null,description text,property_type text not null,listing_type text not null,status text not null check(status in('available','reserved','sold','rented','under_negotiation','off_market','archived')),country_code char(2)not null,region text,city text not null,locality text,address text not null,sale_price numeric(18,2),rental_price numeric(18,2),currency char(3)not null,commission numeric(7,4),bedrooms integer,bathrooms numeric(5,1),area numeric(18,2),area_unit text not null default'sqft',parking integer,floor integer,amenities text[]not null default'{}',assigned_agent_id uuid references auth.users(id),featured boolean not null default false,published boolean not null default false,created_by uuid not null references auth.users(id),updated_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,version integer not null default 1,unique(organization_id,workspace_id,reference));
create index properties_workspace_active_updated_idx on public.properties(organization_id,workspace_id,updated_at desc)where deleted_at is null;
create index properties_workspace_status_idx on public.properties(organization_id,workspace_id,status)where deleted_at is null;
create index properties_search_idx on public.properties using gin(to_tsvector('simple',coalesce(title,'')||' '||coalesce(reference,'')||' '||coalesce(city,'')))where deleted_at is null;
create table public.property_saved_views(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),workspace_id uuid not null references public.workspaces(id),user_id uuid not null references auth.users(id),name text not null,query jsonb not null default'{}',is_default boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id,user_id,name));
alter table public.properties enable row level security;alter table public.property_saved_views enable row level security;
create policy "properties_workspace_read" on public.properties for select to authenticated using(public.is_organization_member(organization_id)and exists(select 1 from public.workspace_members wm where wm.workspace_id=properties.workspace_id and wm.user_id=auth.uid()and wm.status='active'));
create policy "property_saved_views_owner" on public.property_saved_views for all to authenticated using(user_id=auth.uid()and public.is_organization_member(organization_id))with check(user_id=auth.uid()and public.is_organization_member(organization_id));
create or replace function public.current_workspace_role(p_workspace_id uuid)returns text language sql stable security definer set search_path=public as $$select r.code from workspace_members wm join roles r on r.id=wm.role_id where wm.workspace_id=p_workspace_id and wm.user_id=auth.uid()and wm.status='active'limit 1$$;
create or replace function public.create_property(p_workspace_id uuid,p_input jsonb)returns uuid language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_org uuid;v_id uuid;v_role text;begin if v_user is null then raise exception'authentication required';end if;select organization_id into v_org from workspace_members where workspace_id=p_workspace_id and user_id=v_user and status='active';v_role:=current_workspace_role(p_workspace_id);if v_org is null or v_role not in('organization_owner','organization_admin','branch_manager','sales_manager')then raise exception'insufficient property permission';end if;insert into properties(organization_id,workspace_id,reference,title,description,property_type,listing_type,status,country_code,region,city,locality,address,sale_price,rental_price,currency,commission,bedrooms,bathrooms,area,area_unit,parking,floor,amenities,assigned_agent_id,created_by,updated_by)values(v_org,p_workspace_id,p_input->>'reference',p_input->>'title',p_input->>'description',p_input->>'propertyType',p_input->>'listingType',p_input->>'status',upper(p_input->>'countryCode'),p_input->>'region',p_input->>'city',p_input->>'locality',p_input->>'address',nullif(p_input->>'salePrice','')::numeric,nullif(p_input->>'rentalPrice','')::numeric,upper(p_input->>'currency'),nullif(p_input->>'commission','')::numeric,nullif(p_input->>'bedrooms','')::integer,nullif(p_input->>'bathrooms','')::numeric,nullif(p_input->>'area','')::numeric,p_input->>'areaUnit',nullif(p_input->>'parking','')::integer,nullif(p_input->>'floor','')::integer,array(select jsonb_array_elements_text(coalesce(p_input->'amenities','[]'))),nullif(p_input->>'assignedAgentId','')::uuid,v_user,v_user)returning id into v_id;return v_id;end$$;
create or replace function public.update_property(p_property_id uuid,p_expected_version integer,p_input jsonb)returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_property properties%rowtype;v_role text;begin select*into v_property from properties where id=p_property_id and deleted_at is null for update;if not found or not public.is_organization_member(v_property.organization_id)then raise exception'property not found';end if;v_role:=current_workspace_role(v_property.workspace_id);if v_role not in('organization_owner','organization_admin','branch_manager','sales_manager')and not(v_role='agent'and v_property.assigned_agent_id=v_user)then raise exception'insufficient property permission';end if;if v_property.version<>p_expected_version then raise exception'property changed by another user';end if;update properties set reference=p_input->>'reference',title=p_input->>'title',description=p_input->>'description',property_type=p_input->>'propertyType',listing_type=p_input->>'listingType',status=p_input->>'status',country_code=upper(p_input->>'countryCode'),region=p_input->>'region',city=p_input->>'city',locality=p_input->>'locality',address=p_input->>'address',sale_price=nullif(p_input->>'salePrice','')::numeric,rental_price=nullif(p_input->>'rentalPrice','')::numeric,currency=upper(p_input->>'currency'),commission=nullif(p_input->>'commission','')::numeric,bedrooms=nullif(p_input->>'bedrooms','')::integer,bathrooms=nullif(p_input->>'bathrooms','')::numeric,area=nullif(p_input->>'area','')::numeric,area_unit=p_input->>'areaUnit',parking=nullif(p_input->>'parking','')::integer,floor=nullif(p_input->>'floor','')::integer,amenities=array(select jsonb_array_elements_text(coalesce(p_input->'amenities','[]'))),assigned_agent_id=nullif(p_input->>'assignedAgentId','')::uuid,updated_by=v_user,updated_at=now(),version=version+1 where id=p_property_id;end$$;
create or replace function public.archive_properties(p_workspace_id uuid,p_property_ids uuid[])returns integer language plpgsql security definer set search_path=public as $$declare v_role text:=current_workspace_role(p_workspace_id);v_count integer;begin if v_role not in('organization_owner','organization_admin','branch_manager','sales_manager')then raise exception'insufficient property permission';end if;update properties set status='archived',deleted_at=now(),updated_at=now(),updated_by=auth.uid(),version=version+1 where workspace_id=p_workspace_id and id=any(p_property_ids)and deleted_at is null;get diagnostics v_count=row_count;return v_count;end$$;
revoke all on function public.create_property(uuid,jsonb),public.update_property(uuid,integer,jsonb),public.archive_properties(uuid,uuid[])from public;grant execute on function public.create_property(uuid,jsonb),public.update_property(uuid,integer,jsonb),public.archive_properties(uuid,uuid[])to authenticated;

