-- Sprint 20 additive migration. Review and apply manually; never auto-applied.
create table public.google_oauth_credentials(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),workspace_id uuid not null references public.workspaces(id),email text not null,scopes text[]not null default'{}',access_ciphertext text not null,access_iv text not null,access_tag text not null,refresh_ciphertext text not null,refresh_iv text not null,refresh_tag text not null,expires_at timestamptz not null,created_by uuid not null references auth.users(id),updated_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,version integer not null default 1,unique(workspace_id));
alter table public.google_oauth_credentials enable row level security;
-- No table policies by design: ciphertext is only exposed through membership-checked RPCs.
create or replace function public.get_google_credential(p_organization_id uuid,p_workspace_id uuid)returns table(id uuid,email text,scopes text[],access_ciphertext text,access_iv text,access_tag text,refresh_ciphertext text,refresh_iv text,refresh_tag text,expires_at timestamptz,version integer)language plpgsql security definer set search_path=public as $$begin if not public.is_organization_member(p_organization_id)or not exists(select 1 from workspace_members where workspace_id=p_workspace_id and organization_id=p_organization_id and user_id=auth.uid()and status='active')then raise exception'insufficient Google integration permission';end if;return query select c.id,c.email,c.scopes,c.access_ciphertext,c.access_iv,c.access_tag,c.refresh_ciphertext,c.refresh_iv,c.refresh_tag,c.expires_at,c.version from google_oauth_credentials c where c.organization_id=p_organization_id and c.workspace_id=p_workspace_id and c.deleted_at is null;end$$;
create or replace function public.upsert_google_credential(p_organization_id uuid,p_workspace_id uuid,p_email text,p_scopes text[],p_access_ciphertext text,p_access_iv text,p_access_tag text,p_refresh_ciphertext text,p_refresh_iv text,p_refresh_tag text,p_expires_at timestamptz)returns void language plpgsql security definer set search_path=public as $$begin if not public.can_manage_integrations(p_workspace_id)or not public.is_organization_member(p_organization_id)then raise exception'insufficient Google integration permission';end if;insert into google_oauth_credentials(organization_id,workspace_id,email,scopes,access_ciphertext,access_iv,access_tag,refresh_ciphertext,refresh_iv,refresh_tag,expires_at,created_by,updated_by)values(p_organization_id,p_workspace_id,lower(p_email),p_scopes,p_access_ciphertext,p_access_iv,p_access_tag,p_refresh_ciphertext,p_refresh_iv,p_refresh_tag,p_expires_at,auth.uid(),auth.uid())on conflict(workspace_id)do update set email=excluded.email,scopes=excluded.scopes,access_ciphertext=excluded.access_ciphertext,access_iv=excluded.access_iv,access_tag=excluded.access_tag,refresh_ciphertext=excluded.refresh_ciphertext,refresh_iv=excluded.refresh_iv,refresh_tag=excluded.refresh_tag,expires_at=excluded.expires_at,updated_by=auth.uid(),updated_at=now(),deleted_at=null,version=google_oauth_credentials.version+1;end$$;
create or replace function public.refresh_google_credential(p_organization_id uuid,p_workspace_id uuid,p_access_ciphertext text,p_access_iv text,p_access_tag text,p_expires_at timestamptz,p_expected_version integer)returns void language plpgsql security definer set search_path=public as $$begin if not public.is_organization_member(p_organization_id)then raise exception'insufficient Google integration permission';end if;update google_oauth_credentials set access_ciphertext=p_access_ciphertext,access_iv=p_access_iv,access_tag=p_access_tag,expires_at=p_expires_at,updated_by=auth.uid(),updated_at=now(),version=version+1 where organization_id=p_organization_id and workspace_id=p_workspace_id and version=p_expected_version and deleted_at is null;if not found then raise exception'Google credential changed concurrently';end if;end$$;
revoke all on function public.get_google_credential(uuid,uuid),public.upsert_google_credential(uuid,uuid,text,text[],text,text,text,text,text,text,timestamptz),public.refresh_google_credential(uuid,uuid,text,text,text,timestamptz,integer)from public;grant execute on function public.get_google_credential(uuid,uuid),public.upsert_google_credential(uuid,uuid,text,text[],text,text,text,text,text,text,timestamptz),public.refresh_google_credential(uuid,uuid,text,text,text,timestamptz,integer)to authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('leadestate-assets','leadestate-assets',false,20971520,array['image/jpeg','image/png','image/webp','image/avif','application/pdf'])on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "leadestate_assets_member_read" on storage.objects for select to authenticated using(bucket_id='leadestate-assets'and public.is_organization_member(((storage.foldername(name))[1])::uuid)and exists(select 1 from workspace_members wm where wm.workspace_id=((storage.foldername(name))[2])::uuid and wm.organization_id=((storage.foldername(name))[1])::uuid and wm.user_id=auth.uid()and wm.status='active'));
create policy "leadestate_assets_member_insert" on storage.objects for insert to authenticated with check(bucket_id='leadestate-assets'and public.is_organization_member(((storage.foldername(name))[1])::uuid)and exists(select 1 from workspace_members wm where wm.workspace_id=((storage.foldername(name))[2])::uuid and wm.organization_id=((storage.foldername(name))[1])::uuid and wm.user_id=auth.uid()and wm.status='active'));
create policy "leadestate_assets_member_update" on storage.objects for update to authenticated using(bucket_id='leadestate-assets'and public.is_organization_member(((storage.foldername(name))[1])::uuid))with check(bucket_id='leadestate-assets'and public.is_organization_member(((storage.foldername(name))[1])::uuid));
create policy "leadestate_assets_member_delete" on storage.objects for delete to authenticated using(bucket_id='leadestate-assets'and public.is_organization_member(((storage.foldername(name))[1])::uuid));
