-- Sprint 22 additive demo enrichment. Review and apply manually.
create or replace function public.enrich_demo_workspace()returns trigger language plpgsql security definer set search_path=public as $$declare u uuid:=new.owner_id;o uuid:=new.organization_id;w uuid:=new.workspace_id;employee uuid;subscription uuid;begin
insert into properties(organization_id,workspace_id,reference,title,property_type,listing_type,status,country_code,city,locality,address,sale_price,currency,bedrooms,bathrooms,area,amenities,created_by,updated_by,published,featured)values(o,w,'DEMO-P-002','Palm Grove Villa','villa','sale','under_negotiation','IN','Bengaluru','Whitefield','Palm Grove Road',32500000,'INR',4,4,3200,'{"Pool","Garden","Clubhouse"}',u,u,true,true),(o,w,'DEMO-P-003','Metro Heights 1204','apartment','rent','available','IN','Bengaluru','Koramangala','80 Feet Road',null,'INR',2,2,1180,'{"Gym","Security","Parking"}',u,u,true,false),(o,w,'DEMO-P-004','Orion Business Loft','commercial','sale','available','IN','Bengaluru','HSR Layout','Sector 2',14200000,'INR',null,1,1460,'{"Power backup","Parking"}',u,u,true,false)on conflict do nothing;
insert into leads(organization_id,workspace_id,name,phone,email,whatsapp,source,status,priority,budget,currency,buying_purpose,preferred_locations,lead_score,temperature,created_by,updated_by,last_activity_at)values(o,w,'Maya Kapoor','+919811223344','maya@example.com','+919811223344','referral','viewing_scheduled','vip',35000000,'INR','primary_residence','{"Whitefield"}',94,'hot',u,u,now()-interval'20 minutes'),(o,w,'Rohan Iyer','+919900112233','rohan@example.com','+919900112233','portal','contacted','medium',15000000,'INR','investment','{"HSR Layout","Bellandur"}',68,'warm',u,u,now()-interval'3 hours'),(o,w,'Sara Thomas','+919822334455','sara@example.com',null,'website','new','high',120000,'INR','rental','{"Koramangala"}',74,'warm',u,u,now()-interval'1 day')on conflict do nothing;
insert into tasks(organization_id,workspace_id,title,description,status,priority,due_at,assigned_user_id,created_by,updated_by)values(o,w,'Confirm Maya’s villa visit','Share access instructions and confirm attendees.','in_progress','urgent',now()+interval'2 hours',u,u,u),(o,w,'Prepare Skyline comparison','Compare shortlisted units and payment plans.','pending','high',now()+interval'1 day',u,u,u),(o,w,'Review weekly pipeline','Validate stalled opportunities before stand-up.','completed','medium',now()-interval'1 day',u,u,u);
insert into activity_events(organization_id,workspace_id,event_type,title,description,actor_id,occurred_at)values(o,w,'lead.updated','Maya moved to viewing scheduled','Site visit requested for Saturday.',u,now()-interval'20 minutes'),(o,w,'property.updated','Palm Grove Villa shortlisted','Matched to a qualified buyer.',u,now()-interval'1 hour'),(o,w,'task.completed','Weekly inventory review completed','Availability verified across active listings.',u,now()-interval'4 hours'),(o,w,'communication.received','New customer reply','Rohan requested an investment yield comparison.',u,now()-interval'6 hours');
select id into employee from ai_employees where workspace_id=w and code='ai_sales_director'limit 1;if employee is not null then insert into ai_recommendations(organization_id,workspace_id,employee_id,recommendation_type,title,summary,confidence,status,evidence,created_by,updated_by)values(o,w,employee,'next_best_action','Prioritize Maya’s villa viewing','High intent, verified budget, and an active viewing request make this today’s highest-value follow-up.',.91,'pending_approval','[{"signal":"viewing_requested"},{"signal":"budget_verified"}]',u,u);end if;
select id into subscription from subscriptions where workspace_id=w limit 1;if subscription is not null then insert into invoices(organization_id,workspace_id,subscription_id,invoice_number,status,currency,subtotal,tax,issued_at,paid_at,created_by,metadata)values(o,w,subscription,'DEMO-INV-001','paid','INR',14900,2682,now()-interval'30 days',now()-interval'29 days',u,'{"demo":true}'),(o,w,subscription,'DEMO-INV-002','paid','INR',14900,2682,now()-interval'60 days',now()-interval'59 days',u,'{"demo":true}')on conflict do nothing;end if;
update demo_organizations set metadata=metadata||'{"properties":4,"leads":4,"deals":1,"agents":1,"communications":2,"meetings":1,"tasks":3,"activities":4,"ai_recommendations":1,"billing_history":2,"support_tickets":1,"analytics":"populated"}'::jsonb where id=new.id;return new;end$$;
create trigger enrich_demo_after_generation after insert on public.demo_organizations for each row execute function public.enrich_demo_workspace();
