import type { ApprovalRequest, ApprovalStep, ApprovalType, CognitiveAction, PolicyCondition, PolicyEvaluationRequest, PolicyResult } from "../domain/contracts";
import type { ApprovalFramework, PolicyEngine } from "../contracts/ports";
function matches(condition: PolicyCondition, payload: Readonly<Record<string, unknown>>) { const actual = payload[condition.field]; switch (condition.operator) { case "equals": return actual === condition.value; case "not-equals": return actual !== condition.value; case "includes": return Array.isArray(actual) && actual.includes(condition.value); case "greater-than": return typeof actual === "number" && typeof condition.value === "number" && actual > condition.value; case "less-than": return typeof actual === "number" && typeof condition.value === "number" && actual < condition.value; case "exists": return actual !== undefined; } }
export class DeterministicPolicyEngine implements PolicyEngine {
  async evaluate({ action, policies }: PolicyEvaluationRequest): Promise<PolicyResult> { const matched = policies.filter(policy => policy.active && policy.conditions.every(condition => matches(condition, action.payload))); const denied = matched.filter(policy => policy.effect === "deny"), approvals = matched.filter(policy => policy.effect === "require-approval"); const requiredApprovalTypes = [...new Set(approvals.map(policy => policy.type === "financial" ? "finance" as const : policy.type === "legal" ? "legal" as const : policy.type === "approval" ? "manager" as const : "owner" as const))]; return { allowed: denied.length === 0, matchedPolicyIds: matched.map(policy => policy.id), requiredApprovalTypes, reasons: denied.map(policy => policy.description), explanation: denied.length ? "A deterministic policy denied this action." : approvals.length ? "Policy evaluation requires human approval." : "No active policy denied this action." } }
}
export class ArchitectureApprovalFramework implements ApprovalFramework {
  constructor(private readonly id: () => string = () => crypto.randomUUID(), private readonly now: () => Date = () => new Date()) {}
  async prepare(action: CognitiveAction, result: PolicyResult): Promise<ApprovalRequest | undefined> { const types: readonly ApprovalType[] = result.requiredApprovalTypes.length ? result.requiredApprovalTypes : action.requiresApproval ? ["manager"] : []; if (!types.length) return undefined; const steps: ApprovalStep[] = types.map((type, order) => ({ id: this.id(), type, order, status: "pending" })); return { id: this.id(), actionId: action.id, steps, currentStep: 0, status: "pending", createdAt: this.now().toISOString() } }
}

