import"server-only";import type{SupabaseClient}from"@supabase/supabase-js";import type{NotificationCategory,NotificationObservability,NotificationPage,NotificationPreference,NotificationQuery,ReminderRecord}from"../types";
export class NotificationRepository{constructor(private c:SupabaseClient,private o:string,private w:string,private u:string){}
async list(input:NotificationQuery={}):Promise<NotificationPage>{const page=Math.max(1,input.page??1),pageSize=Math.min(100,Math.max(1,input.pageSize??25)),from=(page-1)*pageSize;let q=this.c.from("notification_events").select("id,category,title,body,priority,source_type,source_id,read_at,archived_at,snoozed_until,starred,mentioned,created_at,notification_queue(channel)").eq("organization_id",this.o).eq("workspace_id",this.w).or(`user_id.is.null,user_id.eq.${this.u}`);if(input.view==="unread")q=q.is("read_at",null).is("archived_at",null);if(input.view==="read")q=q.not("read_at","is",null).is("archived_at",null);if(input.view==="archived")q=q.not("archived_at","is",null);if(input.view==="snoozed")q=q.gt("snoozed_until",new Date().toISOString());if(input.view==="starred")q=q.eq("starred",true);if(input.view==="mentioned")q=q.eq("mentioned",true);if(input.view==="high_priority")q=q.in("priority",["high","urgent"]);if(!input.view||input.view==="all")q=q.is("archived_at",null);if(input.category)q=q.eq("category",input.category);if(input.search){const term=input.search.replace(/[%_,()]/g,"").slice(0,100);q=q.or(`title.ilike.%${term}%,body.ilike.%${term}%`)}const{data,error}=await q.order("created_at",{ascending:false}).range(from,from+pageSize);if(error)throw error;const{count}=await this.c.from("notification_events").select("id",{count:"exact",head:true}).eq("organization_id",this.o).eq("workspace_id",this.w).or(`user_id.is.null,user_id.eq.${this.u}`).is("read_at",null).is("archived_at",null);const rows=data??[];return{items:rows.slice(0,pageSize).map(x=>({id:x.id,category:x.category,title:x.title,body:x.body,priority:x.priority,sourceType:x.source_type??undefined,sourceId:x.source_id??undefined,readAt:x.read_at??undefined,archivedAt:x.archived_at??undefined,snoozedUntil:x.snoozed_until??undefined,starred:x.starred,mentioned:x.mentioned,createdAt:x.created_at,channels:(x.notification_queue??[]).map((d:{channel:string})=>d.channel)})),page,pageSize,hasMore:rows.length>pageSize,unreadCount:count??0}as NotificationPage}
async mutate(id:string,action:"read"|"unread"|"archive"|"restore"|"star"|"unstar"|"snooze",until?:string){const{error}=await this.c.rpc("mutate_notification",{p_notification_id:id,p_action:action,p_snoozed_until:until??null});if(error)throw error}
async preferences():Promise<NotificationPreference>{const{data,error}=await this.c.from("notification_preferences").select("email_enabled,in_app_enabled,browser_push_enabled,whatsapp_enabled,webhook_enabled,muted,quiet_hours_start,quiet_hours_end,digest_frequency,categories").eq("organization_id",this.o).eq("workspace_id",this.w).eq("user_id",this.u).maybeSingle();if(error)throw error;return{email:data?.email_enabled??true,inApp:data?.in_app_enabled??true,browserPush:data?.browser_push_enabled??false,whatsapp:data?.whatsapp_enabled??false,webhook:data?.webhook_enabled??false,muted:data?.muted??false,quietHoursStart:data?.quiet_hours_start??undefined,quietHoursEnd:data?.quiet_hours_end??undefined,digestFrequency:data?.digest_frequency??"instant",categories:(data?.categories??{})as Partial<Record<NotificationCategory,boolean>>}}
async savePreferences(value:NotificationPreference){const{error}=await this.c.rpc("save_notification_preferences",{p_input:{organizationId:this.o,workspaceId:this.w,...value}});if(error)throw error}
async reminders():Promise<ReminderRecord[]>{const{data,error}=await this.c.from("notification_reminders").select("id,kind,title,remind_at,status,source_type,source_id").eq("organization_id",this.o).eq("workspace_id",this.w).eq("user_id",this.u).order("remind_at");if(error)throw error;return(data??[]).map(x=>({id:x.id,kind:x.kind,title:x.title,remindAt:x.remind_at,status:x.status,sourceType:x.source_type??undefined,sourceId:x.source_id??undefined}))as ReminderRecord[]}
async observability():Promise<NotificationObservability>{const{data,error}=await this.c.rpc("notification_observability",{p_workspace_id:this.w});if(error)throw error;const x=(data?.[0]??data??{})as Record<string,unknown>;return{unreadCount:Number(x.unread_count??0),queued:Number(x.queued??0),delivered:Number(x.delivered??0),failed:Number(x.failed??0),averageLatencyMs:x.average_latency_ms==null?null:Number(x.average_latency_ms),byChannel:(x.by_channel??{})as NotificationObservability["byChannel"],byCategory:(x.by_category??{})as NotificationObservability["byCategory"]}}
}
