import type{UniversalObjectRef,UniversalObjectType}from"@/features/platform/universal-objects/domain/models";
export type IntelligenceTarget=Extract<UniversalObjectType,"contact"|"company"|"property"|"lead"|"deal"|"task"|"calendar"|"document"|"activity">;
export type IntelligenceStatus="pending"|"ready"|"stale"|"failed";
export interface KnowledgeRecord{id:string;target:UniversalObjectRef;summary:string;insights:readonly string[];recommendations:readonly string[];warnings:readonly string[];strengths:readonly string[];weaknesses:readonly string[];predictions:readonly string[];confidence:number;lastAnalysis:string;version:number;source:string;status:IntelligenceStatus}
export type RecommendationType="next-best-action"|"cross-sell"|"upsell"|"follow-up"|"property-match"|"lead-match"|"risk-alert"|"productivity";
export interface Recommendation{id:string;type:RecommendationType;target:UniversalObjectRef;title:string;rationale:string;actions:readonly string[];priority:"low"|"medium"|"high"|"critical";confidence:number;status:"suggested"|"accepted"|"dismissed"|"completed";createdAt:string;expiresAt?:string}
export type PredictionType="close-probability"|"lead-quality"|"property-demand"|"revenue-forecast"|"activity-forecast"|"customer-churn"|"marketing-performance"|"completion-estimate";
export interface Prediction{id:string;type:PredictionType;target?:UniversalObjectRef;value:number;unit:"percent"|"currency"|"count"|"days"|"score";confidence:number;horizon:string;factors:readonly{label:string;weight:number}[];status:"placeholder"|"modeled";generatedAt:string;modelVersion:string}
export type InsightType="top-agents"|"slow-pipeline"|"lead-aging"|"missed-follow-ups"|"revenue-trend"|"conversion-funnel"|"weekly-summary"|"monthly-summary"|"quarterly-summary"|"business-health"|"growth-opportunity"|"revenue-leakage"|"team-productivity"|"deal-bottleneck"|"property-performance"|"marketing-roi"|"customer-satisfaction"|"executive-summary";
export interface BusinessInsight{id:string;type:InsightType;title:string;summary:string;value?:number;unit?:string;trend?:number;severity:"info"|"success"|"warning"|"critical";evidence:readonly UniversalObjectRef[];confidence?:number;period:string;status:"placeholder"|"ready"}
export interface AuditEntry{id:string;actor:UniversalObjectRef;occurredAt:string;action:string;module:string;object?:UniversalObjectRef;oldValue?:unknown;newValue?:unknown;ip?:string;device?:string;reason?:string;status:"success"|"failure"|"pending";correlationId:string}
export interface IntelligentNotification{id:string;title:string;message:string;priority:"low"|"normal"|"high"|"urgent";severity:"info"|"success"|"warning"|"error";category:string;actionRequired:boolean;suggestedResolution?:string;smartSuggestions:readonly string[];remindAt?:string;escalatedAt?:string;snoozedUntil?:string;dismissedAt?:string;aiExplanation?:string;groupId?:string;deliveryChannels:readonly string[];history:readonly{at:string;action:string;actor?:string}[]}
