import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { OrganizationAuditEvent, OrganizationDepartment, OrganizationInvitation, OrganizationMember, OrganizationProfile, OrganizationRole, OrganizationTeam } from "../types";
type Row=Record<string,unknown>;
export class OrganizationRepository{constructor(private client:SupabaseClient,private organizationId:string,private workspaceId:string){}
async profile():Promise<OrganizationProfile>{const{data,error}=await this.client.from("organizations").select("id,name,business_email,phone,website,timezone,locale,currency,address,branding,business_hours,regional_settings,logo_path,version").eq("id",this.organizationId).single();if(error)throw error;const address=(data.address??{})as Record<string,string>,branding=(data.branding??{})as Record<string,string>;return{id:data.id,name:data.name,businessEmail:data.business_email,phone:data.phone,website:data.website,timezone:data.timezone,locale:data.locale,currency:data.currency,address,branding:{primary:branding.primary??null,accent:branding.accent??null},businessHours:(data.business_hours??{})as OrganizationProfile["businessHours"],regionalSettings:(data.regional_settings??{})as Record<string,string>,logoPath:data.logo_path,version:data.version}}
async members():Promise<OrganizationMember[]>{const{data,error}=await this.client.from("workspace_members").select("id,user_id,status,created_at,roles(code,name)").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).neq("status","removed").order("created_at");if(error)throw error;const rows=(data??[])as unknown as Row[],ids=rows.map(row=>String(row.user_id));const profiles=ids.length?await this.client.from("user_profiles").select("user_id,name,email,last_login_at").in("user_id",ids):{data:[],error:null};if(profiles.error)throw profiles.error;const map=new Map((profiles.data??[]).map(profile=>[profile.user_id,profile]));return rows.map(row=>{const role=row.roles as {code:string;name:string}|null,profile=map.get(String(row.user_id));return{id:String(row.id),userId:String(row.user_id),name:profile?.name||"Member",email:profile?.email||"Unavailable",role:String(role?.code??"read_only")as OrganizationRole,roleName:role?.name??"Read-only",status:String(row.status)as OrganizationMember["status"],joinedAt:String(row.created_at),lastLoginAt:profile?.last_login_at??null}})}
async invitations():Promise<OrganizationInvitation[]>{const{data,error}=await this.client.from("invitations").select("id,name,email,status,expires_at,created_at,resent_at,roles(code,name)").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).in("status",["pending","expired"]).order("created_at",{ascending:false});if(error)throw error;return((data??[])as unknown as Row[]).map(row=>{const role=row.roles as {code:string;name:string}|null;return{id:String(row.id),name:String(row.name),email:String(row.email),role:String(role?.code??"read_only")as OrganizationRole,roleName:role?.name??"Read-only",status:String(row.status),expiresAt:String(row.expires_at),sentAt:String(row.created_at),resentAt:row.resent_at?String(row.resent_at):null}})}
async roles(){const{data,error}=await this.client.from("roles").select("code,name,role_permissions(permissions(key))").in("code",["organization_owner","organization_admin","manager","sales","marketing","operations","finance","support","read_only"]).order("name");if(error)throw error;return(data??[]).map(row=>({code:row.code as OrganizationRole,name:row.name,permissions:((row.role_permissions??[])as unknown as{permissions:{key:string}|null}[]).flatMap(item=>item.permissions?.key?[item.permissions.key]:[])}))}
async departments():Promise<OrganizationDepartment[]>{const{data,error}=await this.client.from("organization_departments").select("id,name,manager_member_id,kpis,permissions,status,version").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).order("name");if(error)throw error;const members=await this.members(),names=new Map(members.map(item=>[item.id,item.name]));return(data??[]).map(row=>({id:row.id,name:row.name,managerMemberId:row.manager_member_id,managerName:row.manager_member_id?names.get(row.manager_member_id)??"Unavailable":null,kpis:Array.isArray(row.kpis)?row.kpis.map(String):[],permissions:row.permissions??[],status:row.status,version:row.version}))}
async teams():Promise<OrganizationTeam[]>{const[{data,error},{data:links,error:linkError},departments,members]=await Promise.all([this.client.from("organization_teams").select("id,name,department_id,manager_member_id,capacity,status,version").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).order("name"),this.client.from("organization_team_members").select("team_id,member_id").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId),this.departments(),this.members()]);if(error)throw error;if(linkError)throw linkError;const departmentNames=new Map(departments.map(item=>[item.id,item.name])),memberNames=new Map(members.map(item=>[item.id,item.name]));return(data??[]).map(row=>{const memberIds=(links??[]).filter(item=>item.team_id===row.id).map(item=>item.member_id);return{id:row.id,name:row.name,departmentId:row.department_id,departmentName:departmentNames.get(row.department_id)??"Unavailable",managerMemberId:row.manager_member_id,managerName:row.manager_member_id?memberNames.get(row.manager_member_id)??"Unavailable":null,memberIds,capacity:row.capacity,workload:Math.round(memberIds.length/Math.max(1,row.capacity)*100),status:row.status,version:row.version}})}
async activity():Promise<OrganizationAuditEvent[]>{const{data,error}=await this.client.from("organization_audit_events").select("id,event_type,actor_id,subject_id,metadata,occurred_at").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).order("occurred_at",{ascending:false}).limit(100);if(error)throw error;return(data??[]).map(row=>({id:row.id,eventType:row.event_type,actorId:row.actor_id,subjectId:row.subject_id,metadata:row.metadata??{},occurredAt:row.occurred_at}))}
async mutate(fn:string,args:Record<string,unknown>){const{data,error}=await this.client.rpc(fn,{p_workspace_id:this.workspaceId,...args});if(error)throw error;return data}
}
