"use client";
import { useId, useState, type ReactNode } from "react";
import { ChevronDown, X } from "lucide-react";
import { useFocusTrap } from "../../accessibility/hooks";
export interface TabItem { readonly id: string; readonly label: string; readonly content: ReactNode; readonly disabled?: boolean }
export function Tabs({ items, defaultTab }: { readonly items: readonly TabItem[]; readonly defaultTab?: string }) { const [active, setActive] = useState(defaultTab ?? items[0]?.id), selected = items.find(item => item.id === active) ?? items[0]; function move(index: number, direction: number) { const enabled = items.filter(item => !item.disabled), current = enabled.findIndex(item => item.id === items[index]?.id), next = enabled[(current + direction + enabled.length) % enabled.length]; if (next) setActive(next.id) } return <div><div role="tablist" aria-label="Tabs" className="flex gap-1 overflow-x-auto border-b border-[var(--vds-color-border)]">{items.map((item, index) => <button key={item.id} type="button" role="tab" aria-selected={selected?.id === item.id} aria-controls={`vds-tab-${item.id}`} disabled={item.disabled} onClick={() => setActive(item.id)} onKeyDown={event => { if (event.key === "ArrowRight") { event.preventDefault(); move(index, 1) } else if (event.key === "ArrowLeft") { event.preventDefault(); move(index, -1) } }} className="vds-focus border-b-2 border-transparent px-3 py-2.5 text-sm text-[var(--vds-color-muted)] aria-selected:border-[var(--vds-color-primary)] aria-selected:text-[var(--vds-color-foreground)] disabled:opacity-50">{item.label}</button>)}</div>{selected && <div id={`vds-tab-${selected.id}`} role="tabpanel" className="pt-4">{selected.content}</div>}</div> }
export function Accordion({ title, children, defaultOpen = false }: { readonly title: string; readonly children: ReactNode; readonly defaultOpen?: boolean }) { return <details open={defaultOpen} className="vds-surface group rounded-xl"><summary className="vds-focus flex list-none items-center justify-between gap-3 p-4 text-sm font-medium">{title}<ChevronDown className="size-4 transition-transform group-open:rotate-180"/></summary><div className="border-t border-[var(--vds-color-border)] p-4 text-sm text-[var(--vds-color-muted)]">{children}</div></details> }
export function Dialog({ open, onClose, title, description, children }: { readonly open: boolean; readonly onClose: () => void; readonly title: string; readonly description?: string; readonly children: ReactNode }) { const titleId = useId(), descriptionId = useId(), ref = useFocusTrap<HTMLDivElement>(open); if (!open) return null; return <div className="vds-overlay-enter fixed inset-0 z-[80] grid place-items-center overflow-y-auto bg-[var(--vds-overlay)] p-4" onMouseDown={event => { if (event.currentTarget === event.target) onClose() }}><div ref={ref} role="dialog" aria-modal="true" aria-labelledby={titleId} aria-describedby={description ? descriptionId : undefined} onKeyDown={event => { if (event.key === "Escape") onClose() }} className="vds-surface vds-modal-enter vds-raised my-auto max-h-[calc(100dvh-2rem)] w-full max-w-lg overflow-y-auto rounded-3xl p-5 sm:p-6"><div className="flex items-start gap-3"><div className="mr-auto"><h2 id={titleId} className="text-lg font-semibold">{title}</h2>{description && <p id={descriptionId} className="mt-1 text-sm text-[var(--vds-color-muted)]">{description}</p>}</div><button type="button" onClick={onClose} aria-label="Close dialog" className="vds-focus grid size-11 shrink-0 place-items-center rounded-xl text-[var(--vds-color-muted)]"><X className="size-4"/></button></div><div className="mt-5">{children}</div></div></div> }
export function Drawer({ open, onClose, title, children, side = "right" }: { readonly open: boolean; readonly onClose: () => void; readonly title: string; readonly children: ReactNode; readonly side?: "left" | "right" }) { const titleId = useId(), ref = useFocusTrap<HTMLElement>(open); if (!open) return null; return <div className="vds-overlay-enter fixed inset-0 z-[70] bg-[var(--vds-overlay)]" onMouseDown={event => { if (event.currentTarget === event.target) onClose() }}><aside ref={ref} role="dialog" aria-modal="true" aria-labelledby={titleId} onKeyDown={event => { if (event.key === "Escape") onClose() }} className={`vds-surface vds-drawer-enter absolute inset-y-0 w-full max-w-md overflow-y-auto p-5 sm:p-6 ${side === "right" ? "right-0" : "left-0"}`}><div className="flex items-center gap-3"><h2 id={titleId} className="mr-auto text-lg font-semibold">{title}</h2><button type="button" onClick={onClose} aria-label="Close drawer" className="vds-focus grid size-11 shrink-0 place-items-center rounded-xl"><X className="size-4"/></button></div><div className="mt-5">{children}</div></aside></div> }
export function Popover({ label, children }: { readonly label: ReactNode; readonly children: ReactNode }) { return <details className="group relative inline-block"><summary className="vds-focus inline-flex min-h-11 list-none items-center rounded-xl border border-[var(--vds-color-border)] px-3 py-2 text-sm">{label}</summary><div className="vds-surface vds-dropdown-enter vds-raised absolute right-0 z-[50] mt-2 min-w-56 rounded-xl p-3">{children}</div></details> }
export function Tooltip({ label, children }: { readonly label: string; readonly children: ReactNode }) { const id = useId(); return <span className="group relative inline-flex" aria-describedby={id}>{children}<span id={id} role="tooltip" className="vds-tooltip-enter pointer-events-none absolute bottom-full left-1/2 z-[100] mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded-lg bg-vds-background px-2.5 py-1.5 text-xs text-vds-foreground shadow-xl group-hover:block group-focus-within:block">{label}</span></span> }
