import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { InventoryRepository } from "./repository";
import type { InventoryAuditEvent, InventoryDocument, InventoryProject, InventoryTower, InventoryUnit, PriceRevision } from "./domain";

type Row = Record<string, unknown>;
const strings = (value: unknown) => Array.isArray(value) ? value.map(String) : [];

export class SupabaseInventoryRepository implements InventoryRepository {
  readonly provider = "supabase" as const;
  constructor(private readonly client: SupabaseClient, private readonly organizationId: string, private readonly workspaceId: string) {}
  private scoped(table: string) { return this.client.from(table).select("*").eq("organization_id", this.organizationId).eq("workspace_id", this.workspaceId); }
  async projects(): Promise<readonly InventoryProject[]> {
    const { data, error } = await this.scoped("property_projects").order("updated_at", { ascending: false }); if (error) throw error;
    return (data ?? []).map((row: Row) => ({ id: String(row.id), code: String(row.code), name: String(row.name), developer: String(row.developer), status: String(row.status) as InventoryProject["status"], description: String(row.description ?? ""), address: String(row.address), city: String(row.city), state: String(row.state), country: String(row.country), zipCode: String(row.zip_code), coordinates: row.latitude == null || row.longitude == null ? undefined : { latitude: Number(row.latitude), longitude: Number(row.longitude) }, launchDate: row.launch_date ? String(row.launch_date) : undefined, possessionDate: row.possession_date ? String(row.possession_date) : undefined, projectType: String(row.project_type), coverImage: row.cover_image ? String(row.cover_image) : undefined, gallery: strings(row.gallery), assignedSalesTeam: strings(row.assigned_sales_team), constructionProgress: Number(row.construction_progress ?? 0) }));
  }
  async towers(): Promise<readonly InventoryTower[]> { const { data, error } = await this.scoped("property_towers").order("name"); if (error) throw error; return (data ?? []).map((row: Row) => ({ id: String(row.id), projectId: String(row.project_id), name: String(row.name), floors: Number(row.floors), totalUnits: Number(row.total_units), status: String(row.status), constructionProgress: Number(row.construction_progress ?? 0), notes: row.notes ? String(row.notes) : undefined })); }
  async units(): Promise<readonly InventoryUnit[]> { const { data, error } = await this.scoped("property_units").order("unit_number"); if (error) throw error; return (data ?? []).map((row: Row) => ({ id: String(row.id), projectId: String(row.project_id), towerId: String(row.tower_id), unitNumber: String(row.unit_number), floor: Number(row.floor), bhkType: String(row.bhk_type), bedrooms: Number(row.bedrooms), bathrooms: Number(row.bathrooms), area: Number(row.area), areaUnit: String(row.area_unit) as "sqft" | "sqm", balcony: Boolean(row.balcony), parking: Number(row.parking), facing: row.facing ? String(row.facing) : undefined, view: row.view_name ? String(row.view_name) : undefined, price: Number(row.price), offerPrice: row.offer_price == null ? undefined : Number(row.offer_price), bookingAmount: Number(row.booking_amount), currency: String(row.currency), status: String(row.status) as InventoryUnit["status"], buyerId: row.buyer_id ? String(row.buyer_id) : undefined })); }
  async prices(): Promise<readonly PriceRevision[]> { const { data, error } = await this.scoped("property_price_revisions").order("effective_from", { ascending: false }); if (error) throw error; return (data ?? []).map((row: Row) => ({ id: String(row.id), projectId: String(row.project_id), unitId: row.unit_id ? String(row.unit_id) : undefined, effectiveFrom: String(row.effective_from), basePrice: Number(row.base_price), offerPrice: row.offer_price == null ? undefined : Number(row.offer_price), currency: String(row.currency), discountRule: row.discount_rule ? String(row.discount_rule) : undefined, overrideApprovalId: row.override_approval_id ? String(row.override_approval_id) : undefined })); }
  async documents(): Promise<readonly InventoryDocument[]> { const { data, error } = await this.scoped("property_documents").order("created_at", { ascending: false }); if (error) throw error; return (data ?? []).map((row: Row) => ({ id: String(row.id), projectId: String(row.project_id), title: String(row.title), kind: String(row.kind) as InventoryDocument["kind"], storagePath: row.storage_path ? String(row.storage_path) : undefined, placeholder: Boolean(row.placeholder) })); }
  async audit(): Promise<readonly InventoryAuditEvent[]> { const { data, error } = await this.scoped("property_inventory_audit").order("occurred_at", { ascending: false }).limit(100); if (error) throw error; return (data ?? []).map((row: Row) => ({ id: String(row.id), projectId: String(row.project_id), unitId: row.unit_id ? String(row.unit_id) : undefined, action: String(row.action), actorLabel: String(row.actor_label), occurredAt: String(row.occurred_at) })); }
  async transitionUnit(input: { unitId: string; expectedStatus: string; nextStatus: "available" | "reserved" | "booked"; buyerId?: string; opportunityRequested?: boolean }) { const { error } = await this.client.rpc("transition_property_unit", { p_workspace_id: this.workspaceId, p_unit_id: input.unitId, p_expected_status: input.expectedStatus, p_next_status: input.nextStatus, p_buyer_id: input.buyerId ?? null, p_create_opportunity: input.opportunityRequested ?? false }); if (error) throw error; }
}
