export type MailProviderCode="gmail"|"outlook"|"exchange"|"imap"|"shared_inbox"|"enterprise";
export type MailboxFolder="inbox"|"sent"|"drafts"|"starred"|"important"|"archive"|"spam"|"trash"|"unread";
export interface MailAddress{readonly name:string;readonly email:string}
export interface MailAttachment{readonly id:string;readonly messageId:string;readonly name:string;readonly mimeType:string;readonly size:number;readonly downloadable:boolean;readonly previewable:boolean;readonly virusScanStatus:"not_scanned"}
export interface MailMessage{readonly id:string;readonly threadId:string;readonly sender:MailAddress;readonly to:readonly MailAddress[];readonly cc:readonly MailAddress[];readonly bcc:readonly MailAddress[];readonly subject:string;readonly timestamp:string;readonly snippet:string;readonly plainText:string;readonly html:string;readonly quotedHistory:string;readonly labels:readonly string[];readonly attachments:readonly MailAttachment[]}
export interface MailThread{readonly id:string;readonly messages:readonly MailMessage[]}
export interface MailboxPage{readonly messages:readonly MailMessage[];readonly nextPageToken:string|null;readonly resultSizeEstimate:number}
export interface ComposeMail{readonly to:readonly string[];readonly cc?:readonly string[];readonly bcc?:readonly string[];readonly subject:string;readonly body:string;readonly html?:string;readonly threadId?:string;readonly inReplyTo?:string;readonly attachments?:readonly {name:string;mimeType:string;contentBase64:string}[]}
export interface MailProvider{readonly code:MailProviderCode;status():Promise<"connected"|"not_connected"|"scope_required"|"unavailable">;list(folder:MailboxFolder,query?:string,pageToken?:string):Promise<MailboxPage>;message(id:string):Promise<MailMessage>;thread(id:string):Promise<MailThread>;send(input:ComposeMail):Promise<{id:string;threadId:string}>;saveDraft(input:ComposeMail):Promise<{id:string}>;modify(id:string,input:{addLabels?:readonly string[];removeLabels?:readonly string[]}):Promise<void>;attachment(messageId:string,attachmentId:string):Promise<{data:string;size:number}>}
