export type WhatsAppConnectionState="connected"|"disconnected"|"degraded"|"unavailable";
export type WhatsAppMessageType="text"|"image"|"video"|"audio"|"voice"|"document"|"sticker"|"location"|"contact"|"interactive"|"template"|"reaction"|"unsupported";
export interface WhatsAppMedia {readonly providerMediaId:string|null;readonly mimeType:string|null;readonly fileName:string|null;readonly caption:string|null;readonly sha256:string|null;readonly storedLocally:false}
export interface WhatsAppMessage {readonly id:string;readonly conversationId:string;readonly type:WhatsAppMessageType;readonly direction:"inbound"|"outbound";readonly status:"received"|"draft"|"pending_approval"|"sent"|"delivered"|"read"|"failed"|"unknown";readonly text:string|null;readonly occurredAt:string;readonly read:boolean;readonly media:WhatsAppMedia|null;readonly location:{latitude:number;longitude:number;name:string|null;address:string|null}|null;readonly contacts:readonly {name:string;phones:readonly string[]}[];readonly interactive:{kind:string;title:string|null}|null;readonly template:{name:string|null;language:string|null}|null;readonly reaction:{messageId:string|null;emoji:string|null}|null;readonly unavailableReason:string|null}
export interface WhatsAppConversation {readonly id:string;readonly customer:string;readonly phone:string|null;readonly status:string;readonly unreadCount:number;readonly assignedTo:string|null;readonly pinned:boolean;readonly archived:boolean;readonly labels:readonly string[];readonly priority:"low"|"normal"|"high"|"urgent";readonly lastActivityAt:string;readonly crmReferences:readonly CrmReference[];readonly timelineReferences:readonly string[]}
export interface ConversationPage {readonly conversations:readonly WhatsAppConversation[];readonly count:number;readonly page:number;readonly pageSize:number}
export interface ConversationQuery {readonly search?:string;readonly unreadOnly?:boolean;readonly archived?:boolean;readonly pinned?:boolean;readonly priority?:WhatsAppConversation["priority"];readonly label?:string;readonly page?:number;readonly pageSize?:number}
export interface WhatsAppConversationDetail {readonly conversation:WhatsAppConversation;readonly messages:readonly WhatsAppMessage[]}
export interface WhatsAppTemplate {readonly id:string;readonly name:string;readonly language:string;readonly category:string;readonly status:string;readonly components:readonly {type:string;text:string|null}[]}
export interface WhatsAppProfile {readonly businessAccount:"configured"|"unavailable";readonly phoneNumber:"configured"|"unavailable";readonly displayName:string|null;readonly qualityRating:string|null}
export interface WhatsAppHealth {readonly state:"healthy"|"needs_attention"|"unavailable";readonly connection:WhatsAppConnectionState;readonly webhook:"configured"|"unavailable";readonly latencyMs:number|null;readonly quality:"green"|"yellow"|"red"|"unknown";readonly queue:"available"|"unavailable";readonly rateLimit:"available"|"limited"|"unknown";readonly retry:"idle"|"pending"|"unavailable";readonly version:string;readonly reason?:string}
export type CrmReferenceType="lead"|"customer"|"deal"|"property"|"meeting"|"task"|"timeline";export interface CrmReference{readonly type:CrmReferenceType;readonly id:string;readonly label:string;readonly source:"authoritative"}
export interface WhatsAppIntelligence {readonly state:"unavailable";readonly summary:null;readonly suggestedReply:null;readonly sentiment:null;readonly intent:null;readonly priority:null;readonly nextAction:null;readonly followUp:null;readonly meetingSuggestion:null;readonly leadQualification:null;readonly reason:string}
export interface OutboundText {readonly conversationId:string;readonly to:string;readonly text:string;readonly approvalId:string;readonly executionRequestId:string}
export interface OutboundTemplate {readonly to:string;readonly name:string;readonly language:string;readonly components?:readonly unknown[];readonly approvalId:string;readonly executionRequestId:string}
export interface OutboundMedia {readonly to:string;readonly type:"image"|"video"|"audio"|"document"|"sticker";readonly providerMediaId:string;readonly caption?:string;readonly approvalId:string;readonly executionRequestId:string}
