import type {
  Notification,
  NotificationCategory,
} from "../types/notification";

export const notificationTabs: NotificationCategory[] = [
  "Platform",
  "Applications",
  "Organizations",
  "Security",
  "Billing",
  "AI",
  "Marketing",
  "Support",
];

export const notifications: Notification[] = [
  {
    id: "notification-platform",
    title: "Platform deployment completed",
    description: "AtlasOS core services are reporting normal health.",
    priority: "Normal",
    time: "2 minutes ago",
    source: "Platform Operations",
    status: "Unread",
    action: "View deployment",
    category: "Platform",
  },
  {
    id: "notification-applications",
    title: "Application update available",
    description: "AI Studio 0.8 is ready for controlled rollout.",
    priority: "Low",
    time: "18 minutes ago",
    source: "Application Registry",
    status: "Read",
    action: "Review release",
    category: "Applications",
  },
  {
    id: "notification-organizations",
    title: "Organization provisioning ready",
    description: "Aurora Ventures completed its workspace requirements.",
    priority: "Normal",
    time: "42 minutes ago",
    source: "Identity Platform",
    status: "Unread",
    action: "Open organization",
    category: "Organizations",
  },
  {
    id: "notification-security",
    title: "Access review requires attention",
    description: "Two privileged role assignments await review.",
    priority: "High",
    time: "1 hour ago",
    source: "Security Center",
    status: "Unread",
    action: "Review access",
    category: "Security",
  },
  {
    id: "notification-billing",
    title: "Usage reconciliation completed",
    description: "August metering is ready for finance verification.",
    priority: "Normal",
    time: "2 hours ago",
    source: "Billing Platform",
    status: "Resolved",
    action: "View usage",
    category: "Billing",
  },
  {
    id: "notification-ai",
    title: "AI evaluation threshold reached",
    description: "Sales AI passed the current quality gate.",
    priority: "Normal",
    time: "3 hours ago",
    source: "AI Studio",
    status: "Read",
    action: "View evaluation",
    category: "AI",
  },
  {
    id: "notification-marketing",
    title: "Campaign approval requested",
    description: "The AtlasOS portfolio launch is ready for review.",
    priority: "Normal",
    time: "Yesterday",
    source: "Marketing Studio",
    status: "Unread",
    action: "Review campaign",
    category: "Marketing",
  },
  {
    id: "notification-support",
    title: "Support escalation resolved",
    description: "The workspace access case has been completed.",
    priority: "Low",
    time: "Yesterday",
    source: "Support Desk",
    status: "Resolved",
    action: "View case",
    category: "Support",
  },
];
