import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = { title: "Media Kit", description: "VAYON company overview, brand assets, screenshots, founder information, and press contact.", alternates: { canonical: "/media-kit" }, openGraph: { title: "VAYON Media Kit", description: "Approved company and brand resources.", url: "/media-kit" } };
const logos = [["Master logo", "/assets/brand/logo-master.png"], ["Dark wordmark", "/assets/brand/wordmark-dark.png"], ["Light wordmark", "/assets/brand/wordmark-light.png"]] as const;
const screenshots = [["Executive workspace", "/assets/brand/opengraph-image.png"], ["Demo property", "/vayon/demo/properties/property-1.svg"]] as const;
export default function Page() { return <main className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">Media kit</p><h1 className="mt-4 text-5xl font-semibold">Approved VAYON media resources.</h1><p className="mt-5 max-w-3xl text-vds-muted">Company context, downloadable brand assets, product imagery, founder-information status, and a governed press contact.</p><section className="mt-12"><h2 className="text-2xl font-semibold">Company Overview</h2><p className="mt-3 max-w-3xl leading-7 text-vds-muted">VAYON is a governed AI workforce and connected operating platform for customer-centric organizations.</p></section><AssetGrid title="Brand Assets & Logo Downloads" items={logos}/><AssetGrid title="Screenshots" items={screenshots}/><div className="mt-10 grid gap-4 md:grid-cols-2"><section className="rounded-2xl border border-vds-border bg-vds-surface p-6"><h2 className="text-xl font-semibold">Founder Information</h2><p className="mt-3 text-sm text-vds-muted">Approved founder biography and photography are not yet published. This explicit state prevents unverified attribution.</p></section><section className="rounded-2xl border border-vds-border bg-vds-surface p-6"><h2 className="text-xl font-semibold">Press Contact</h2><p className="mt-3 text-sm text-vds-muted">Use the existing contact workflow for press and analyst requests.</p><Link href="/contact" className="mt-4 inline-block font-semibold text-vds-primary">Contact VAYON →</Link></section></div></main> }
function AssetGrid({title,items}:{title:string;items:readonly (readonly [string,string])[]}){return <section className="mt-10"><h2 className="text-2xl font-semibold">{title}</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{items.map(([label,src])=><article className="overflow-hidden rounded-2xl border border-vds-border bg-vds-surface" key={src}><div className="grid aspect-video place-items-center bg-vds-elevated p-6"><Image src={src} alt={`${label} preview`} width={640} height={360} className="max-h-full w-auto object-contain"/></div><div className="flex items-center justify-between p-4"><span className="text-sm font-medium">{label}</span><a href={src} download className="vds-focus rounded-lg border border-vds-border px-3 py-2 text-xs font-semibold">Download</a></div></article>)}</div></section>}
