"use server";
import { headers } from "next/headers";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { EnterpriseOrganizationService } from "../services/organization.service";
import { idSchema, invitationSchema, profileSchema, roleSchema, transferSchema } from "../validation";
const value=(form:FormData,key:string)=>String(form.get(key)??"").trim();
const refresh=()=>{revalidatePath("/vayon/settings/organization");revalidatePath("/vayon/settings/members");revalidatePath("/vayon/settings/roles");revalidatePath("/vayon/settings/activity")};
function failure(reason:unknown):never{redirect(`/vayon/settings/members?error=${encodeURIComponent(reason instanceof Error?reason.message:String(reason))}`)}
async function origin(){const requestHeaders=await headers();return requestHeaders.get("origin")??process.env.NEXT_PUBLIC_APP_URL??"http://localhost:3000"}
export async function updateOrganizationAction(form:FormData){const parsed=profileSchema.safeParse({name:value(form,"name"),businessEmail:value(form,"businessEmail"),phone:value(form,"phone"),website:value(form,"website"),timezone:value(form,"timezone"),locale:value(form,"locale"),currency:value(form,"currency").toUpperCase(),address:{line1:value(form,"line1"),line2:value(form,"line2"),city:value(form,"city"),region:value(form,"region"),postalCode:value(form,"postalCode"),country:value(form,"country").toUpperCase()},branding:{primary:value(form,"primary"),accent:value(form,"accent")}});if(!parsed.success)redirect(`/vayon/settings/organization?error=${encodeURIComponent(parsed.error.issues[0]?.message??"Invalid organization")}`);await new EnterpriseOrganizationService().updateProfile(parsed.data);const logo=form.get("logo");if(logo instanceof File&&logo.size)await new EnterpriseOrganizationService().uploadLogo(logo);refresh();redirect("/vayon/settings/organization?success=Organization%20updated")}
export async function inviteMemberAction(form:FormData){const parsed=invitationSchema.safeParse({name:value(form,"name"),email:value(form,"email"),role:value(form,"role")});if(!parsed.success)failure(parsed.error.issues[0]?.message);try{await new EnterpriseOrganizationService().invite(parsed.data,await origin());refresh();redirect("/vayon/settings/members?success=Invitation%20sent")}catch(reason){failure(reason)}}
export async function invitationAction(form:FormData){const id=idSchema.safeParse(value(form,"invitationId")),intent=value(form,"intent");if(!id.success||!["resend","cancel"].includes(intent))failure("Invalid invitation request.");try{const service=new EnterpriseOrganizationService();if(intent==="resend")await service.resend(id.data,await origin());else await service.cancelInvitation(id.data);refresh();redirect(`/vayon/settings/members?success=Invitation%20${intent}ed`)}catch(reason){failure(reason)}}
export async function memberAction(form:FormData){const id=idSchema.safeParse(value(form,"memberId")),intent=value(form,"intent");if(!id.success)failure("Invalid member.");try{const service=new EnterpriseOrganizationService();if(intent==="suspend")await service.setMemberStatus(id.data,"suspended");else if(intent==="reactivate")await service.setMemberStatus(id.data,"active");else if(intent==="remove")await service.removeMember(id.data);else if(intent==="role"){const role=roleSchema.parse(value(form,"role"));await service.changeRole(id.data,role)}else failure("Invalid member action.");refresh();redirect("/vayon/settings/members?success=Member%20updated")}catch(reason){failure(reason)}}
export async function transferOwnershipAction(form:FormData){const parsed=transferSchema.safeParse({memberId:value(form,"memberId"),confirmation:value(form,"confirmation")});if(!parsed.success)failure("Type TRANSFER to confirm ownership transfer.");try{await new EnterpriseOrganizationService().transferOwnership(parsed.data.memberId,parsed.data.confirmation);refresh();redirect("/vayon/settings/members?success=Ownership%20transferred")}catch(reason){failure(reason)}}
export async function acceptInvitationAction(){try{await new EnterpriseOrganizationService().acceptInvitation();refresh();redirect("/vayon?invitation=accepted")}catch(reason){redirect(`/accept-invitation?error=${encodeURIComponent(reason instanceof Error?reason.message:String(reason))}`)}}
