import "server-only";
import { createHash, timingSafeEqual } from "node:crypto";
import { googleIdentityScopes } from "@/features/platform/integrations/identity";
import { integrationContext } from "@/features/platform/integrations/services/integration-context";
import { log } from "@/lib/observability/logger";
import { GoogleRepository } from "../repositories/google.repository";
import { TokenCryptoService } from "./token-crypto.service";

interface GoogleIdClaims { iss?:string; aud?:string; exp?:number; nonce?:string; sub?:string; email?:string; email_verified?:boolean }
interface TokenResponse { access_token:string; refresh_token?:string; expires_in:number; scope?:string; id_token?:string }
function config(){const clientId=process.env.GOOGLE_CLIENT_ID,clientSecret=process.env.GOOGLE_CLIENT_SECRET,redirectUri=process.env.GOOGLE_OAUTH_REDIRECT_URI;if(!clientId||!clientSecret||!redirectUri)throw new Error("Google OAuth environment is incomplete.");const redirect=new URL(redirectUri),appUrl=process.env.NEXT_PUBLIC_APP_URL?new URL(process.env.NEXT_PUBLIC_APP_URL):null;if(process.env.NODE_ENV==="production"&&redirect.protocol!=="https:")throw new Error("Google OAuth redirect must use HTTPS in production.");if(appUrl&&redirect.origin!==appUrl.origin)throw new Error("Google OAuth redirect origin is not trusted.");return{clientId,clientSecret,redirectUri:redirect.toString()}}
function claims(idToken:string):GoogleIdClaims{const parts=idToken.split(".");if(parts.length!==3)throw new Error("Google identity token is malformed.");return JSON.parse(Buffer.from(parts[1],"base64url").toString("utf8"))as GoogleIdClaims}
export function safeEqual(left:string,right:string){const a=Buffer.from(left),b=Buffer.from(right);return a.length===b.length&&timingSafeEqual(a,b)}

export class GoogleOAuthService{
  authorizationUrl(input:{state:string;nonce:string;codeChallenge:string;additionalScopes?:readonly string[]}){const c=config(),requested=[...googleIdentityScopes,...(input.additionalScopes??[])],q=new URLSearchParams({client_id:c.clientId,redirect_uri:c.redirectUri,response_type:"code",scope:requested.join(" "),access_type:"offline",prompt:"consent",include_granted_scopes:"true",state:input.state,nonce:input.nonce,code_challenge:input.codeChallenge,code_challenge_method:"S256"});return`https://accounts.google.com/o/oauth2/v2/auth?${q}`}
  async exchange(input:{code:string;codeVerifier:string;nonce:string;requiredScopes?:readonly string[]}){const c=config(),response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code:input.code,code_verifier:input.codeVerifier,client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:c.redirectUri,grant_type:"authorization_code"}),cache:"no-store"});if(!response.ok){log("google.identity.exchange_failed",{status:response.status});throw new Error("Google authorization exchange failed.")}const token=await response.json()as TokenResponse;if(!token.access_token||!token.refresh_token||!token.id_token)throw new Error("Google did not return the required offline identity credentials.");const identity=claims(token.id_token),issuerOk=identity.iss==="https://accounts.google.com"||identity.iss==="accounts.google.com";if(!issuerOk||identity.aud!==c.clientId||!identity.exp||identity.exp*1000<=Date.now()||identity.nonce!==input.nonce||!identity.sub||!identity.email||identity.email_verified!==true)throw new Error("Google identity token validation failed.");const granted=(token.scope??"").split(" ").filter(Boolean),required=[...googleIdentityScopes,...(input.requiredScopes??[])];if(!required.every(scope=>granted.includes(scope)))throw new Error("Google did not grant the required scopes.");const ctx=await integrationContext(),crypto=new TokenCryptoService();await new GoogleRepository(ctx.client,ctx.organizationId,ctx.workspaceId).save({email:identity.email,scopes:granted,access:crypto.encrypt(token.access_token),refresh:crypto.encrypt(token.refresh_token),expiresAt:new Date(Date.now()+token.expires_in*1000).toISOString()});await ctx.client.rpc("record_identity_audit",{p_event_type:"google.connected",p_organization_id:ctx.organizationId,p_workspace_id:ctx.workspaceId,p_metadata:{scope_count:granted.length}});log("google.identity.connected",{workspaceId:ctx.workspaceId,provider:"google",scopeCount:granted.length})}
  async accessToken(forceRefresh=false){const ctx=await integrationContext(),repo=new GoogleRepository(ctx.client,ctx.organizationId,ctx.workspaceId),stored=await repo.credential();if(!stored)throw new Error("Google Workspace is not connected.");const crypto=new TokenCryptoService();if(!forceRefresh&&new Date(stored.expiresAt).getTime()>Date.now()+60_000)return crypto.decrypt(stored.access);const c=config(),response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,refresh_token:crypto.decrypt(stored.refresh),grant_type:"refresh_token"}),cache:"no-store"});if(!response.ok){log("google.identity.refresh_failed",{workspaceId:ctx.workspaceId,status:response.status});throw new Error("Google authorization must be renewed.")}const token=await response.json()as{access_token:string;expires_in:number},expiresAt=new Date(Date.now()+token.expires_in*1000).toISOString();await repo.updateAccess(crypto.encrypt(token.access_token),expiresAt,stored.version);log("google.identity.refreshed",{workspaceId:ctx.workspaceId});return token.access_token}
  async disconnect(){const ctx=await integrationContext(),repo=new GoogleRepository(ctx.client,ctx.organizationId,ctx.workspaceId),stored=await repo.credential();if(!stored)return;const refresh=new TokenCryptoService().decrypt(stored.refresh),response=await fetch("https://oauth2.googleapis.com/revoke",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({token:refresh}),cache:"no-store"});if(!response.ok&&response.status!==400){log("google.identity.revoke_failed",{workspaceId:ctx.workspaceId,status:response.status});throw new Error("Google credential revocation failed.")}await repo.remove(stored.id);log("google.identity.disconnected",{workspaceId:ctx.workspaceId,provider:"google"})}
  static codeChallenge(verifier:string){return createHash("sha256").update(verifier).digest("base64url")}
}
