export type VisitType = "initial" | "follow-up" | "virtual-tour" | "final-inspection";
export type VisitStatus = "scheduled" | "confirmed" | "checked-in" | "completed" | "cancelled" | "no-show" | "rescheduled";
export type VisitPriority = "low" | "medium" | "high" | "urgent";
export interface SiteVisit {
  readonly id:string;readonly customerId?:string;readonly customerLabel:string;readonly leadId?:string;readonly opportunityId?:string;readonly agentId?:string;readonly agentLabel:string;readonly projectId?:string;readonly projectLabel:string;readonly towerId?:string;readonly towerLabel?:string;readonly unitId?:string;readonly unitLabel?:string;readonly startsAt:string;readonly endsAt:string;readonly durationMinutes:number;readonly type:VisitType;readonly status:VisitStatus;readonly notes?:string;readonly priority:VisitPriority;readonly agenda:readonly string[];readonly visitorInstructions?:string;readonly documents:readonly string[];readonly checklist:readonly string[];readonly reminders:readonly string[];readonly arrivalAt?:string;readonly departureAt?:string;readonly version:number;
}
export interface VisitFeedback {readonly id:string;readonly visitId:string;readonly rating:number;readonly agentNotes?:string;readonly interestedUnitIds:readonly string[];readonly budgetUpdate?:number;readonly currency?:string;readonly preferredConfiguration?:string;readonly objections:readonly string[];readonly competitorProjects:readonly string[];readonly probabilityChange?:number;readonly createdAt:string}
export interface VisitAudit {readonly id:string;readonly visitId:string;readonly action:string;readonly actorLabel:string;readonly occurredAt:string}
export interface AgentAvailability {readonly id:string;readonly name:string;readonly available:boolean;readonly visitsToday:number;readonly workload:number;readonly languages:readonly string[];readonly region:string;readonly manager:string;readonly travelTime:"placeholder"}
export interface VisitSnapshot {readonly visits:readonly SiteVisit[];readonly feedback:readonly VisitFeedback[];readonly audit:readonly VisitAudit[];readonly agents:readonly AgentAvailability[];readonly provider:"supabase"|"aurora"}
export interface VisitMetrics {readonly today:number;readonly upcoming:number;readonly completed:number;readonly noShows:number;readonly conversionRate:number;readonly visitToBookingRatio:number;readonly averageVisitsPerDeal:number;readonly averageDuration:number;readonly agentLeaderboard:readonly {name:string;completed:number}[]}
export interface VisitRecommendation {readonly kind:"brief"|"customer-history"|"talking-points"|"similar-inventory"|"follow-up-email"|"whatsapp-draft"|"summary"|"agent-assignment";readonly text:string;readonly rationale:string;readonly recommendationOnly:true;readonly autonomousMessaging:false}
