import { NextRequest,NextResponse } from "next/server";
import { cookies } from "next/headers";
import { GoogleOAuthService,safeEqual } from "@/features/platform/integrations/google/services/google-oauth.service";
import { googleCalendarScopes,googleContactsScopes,googleDriveScopes,googleGmailScopes } from "@/features/platform/integrations/identity";
import { captureException } from "@/lib/observability/logger";

const destination="/vayon/settings/integrations/google";
// Legacy equality guard `state!==expected` is superseded by constant-time safeEqual below.
export async function GET(request:NextRequest){const url=new URL(request.url),code=url.searchParams.get("code"),state=url.searchParams.get("state"),error=url.searchParams.get("error"),store=await cookies(),expected=store.get("google_oauth_state")?.value,nonce=store.get("google_oauth_nonce")?.value,verifier=store.get("google_oauth_verifier")?.value,product=store.get("google_oauth_product")?.value;store.delete("google_oauth_state");store.delete("google_oauth_nonce");store.delete("google_oauth_verifier");store.delete("google_oauth_product");const target=product==="gmail"?"/vayon/email":product==="calendar"?"/vayon/calendar":product==="drive"?"/vayon/documents/drive":product==="contacts"?"/vayon/contacts/google":destination;if(error)return NextResponse.redirect(new URL(`${target}?error=Google%20authorization%20was%20not%20completed`,request.url));if(!code||!state||!expected||!nonce||!verifier||!safeEqual(state,expected))return NextResponse.redirect(new URL(`${target}?error=Invalid%20or%20expired%20OAuth%20request`,request.url));try{await new GoogleOAuthService().exchange({code,codeVerifier:verifier,nonce,requiredScopes:product==="gmail"?googleGmailScopes:product==="calendar"?googleCalendarScopes:product==="drive"?googleDriveScopes:product==="contacts"?googleContactsScopes:undefined});return NextResponse.redirect(new URL(`${target}?success=${product==="gmail"?"Gmail":product==="calendar"?"Google%20Calendar":product==="drive"?"Google%20Drive":product==="contacts"?"Google%20Contacts":"Google%20Workspace"}%20connected`,request.url))}catch(errorValue){captureException(errorValue,{operation:product==="gmail"?"gmail_oauth_callback":"google_identity_callback"});return NextResponse.redirect(new URL(`${target}?error=Google%20connection%20failed`,request.url))}}
