import type { DemoWorkspaceBlueprint } from "../domain/contracts";

const officePhoto="/vayon/demo/office-placeholder.svg";
export const auroraRealtyGroup = Object.freeze({
  version:"1.8.0",
  company:{id:"aurora-realty-group",name:"Aurora Realty Group",legalName:"Aurora Realty Group",description:"A multi-division real estate company blueprint serving residential, commercial, luxury, rental, land, and investment markets.",mission:"Help people and businesses make confident property decisions through trusted expertise, coordinated service, and enduring relationships.",vision:"Build the most trusted regionally connected real estate organization, where every property journey feels informed and personal.",industry:"Real Estate",businessType:"Full-service real estate brokerage and advisory",headquartersOfficeId:"aurora-hq",regionalOfficeIds:["downtown-branch","luxury-division","commercial-division","remote-workforce"],brand:{primary:"#0E7490",accent:"#A78BFA",warmNeutral:"#D6D0C4",logoAsset:"/vayon/demo/aurora-logo.svg",imageryAsset:"/vayon/demo/brand-placeholder.svg",coverAsset:"/vayon/demo/cover-placeholder.svg"},workspace:{id:"aurora-demo-workspace",name:"Aurora Realty Group",slug:"aurora-realty-group",timezone:"Asia/Kolkata",currency:"INR",language:"en-IN",countryCode:"IN",logoPlaceholder:"/vayon/demo/aurora-logo.svg",persistence:"none",status:"blueprint"}},
  departments:[
    {id:"executive",name:"Executive",description:"Company direction, governance, and cross-functional alignment.",responsibilities:["Corporate strategy","Governance","Executive priorities"],managerRoleId:"ceo"},
    {id:"sales",name:"Sales",description:"Lead development, advisory, pipeline stewardship, and transaction growth.",responsibilities:["Lead qualification","Property advisory","Deal progression"],managerRoleId:"sales-director",reportsTo:"executive"},
    {id:"marketing",name:"Marketing",description:"Brand, demand generation, campaigns, and market communication.",responsibilities:["Brand stewardship","Campaign planning","Demand generation"],managerRoleId:"marketing-manager",reportsTo:"executive"},
    {id:"operations",name:"Operations",description:"Service delivery, office coordination, and operational standards.",responsibilities:["Workflow coordination","Office operations","Service quality"],managerRoleId:"operations-manager",reportsTo:"executive"},
    {id:"customer-success",name:"Customer Success",description:"Post-engagement care, retention, and customer advocacy.",responsibilities:["Customer onboarding","Service follow-up","Escalation coordination"],managerRoleId:"customer-success-manager",reportsTo:"operations"},
    {id:"finance",name:"Finance",description:"Financial stewardship, controls, planning, and reporting readiness.",responsibilities:["Financial controls","Planning","Management reporting"],managerRoleId:"finance-manager",reportsTo:"executive"},
    {id:"hr",name:"HR",description:"People operations, talent programs, and workplace policy.",responsibilities:["Talent operations","People policy","Workforce planning"],managerRoleId:"hr-manager",reportsTo:"executive"},
    {id:"legal",name:"Legal",description:"Contract, regulatory, and organizational risk guidance.",responsibilities:["Contract governance","Regulatory readiness","Risk guidance"],managerRoleId:"coo",reportsTo:"executive"},
    {id:"technology",name:"Technology",description:"Business systems, data enablement, and technology operations.",responsibilities:["Platform enablement","Data governance","Technology operations"],managerRoleId:"coo",reportsTo:"executive"},
    {id:"administration",name:"Administration",description:"Shared administrative services and office support.",responsibilities:["Office administration","Records coordination","Shared services"],managerRoleId:"office-administrator",reportsTo:"operations"},
  ],
  roles:[
    {id:"ceo",name:"CEO",departmentId:"executive",purpose:"Sets company direction and governance.",workforceType:"human"},{id:"coo",name:"COO",departmentId:"executive",purpose:"Coordinates company operations and execution.",reportsToRoleId:"ceo",workforceType:"human"},
    {id:"sales-director",name:"Sales Director",departmentId:"sales",purpose:"Owns sales strategy and pipeline performance.",reportsToRoleId:"ceo",workforceType:"human"},{id:"sales-manager",name:"Sales Manager",departmentId:"sales",purpose:"Leads sales teams and pipeline discipline.",reportsToRoleId:"sales-director",workforceType:"human"},{id:"sales-agent",name:"Sales Agent",departmentId:"sales",purpose:"Advises customers and progresses opportunities.",reportsToRoleId:"sales-manager",workforceType:"human"},
    {id:"marketing-manager",name:"Marketing Manager",departmentId:"marketing",purpose:"Leads brand and demand programs.",reportsToRoleId:"ceo",workforceType:"human"},{id:"marketing-executive",name:"Marketing Executive",departmentId:"marketing",purpose:"Coordinates campaigns and content.",reportsToRoleId:"marketing-manager",workforceType:"human"},
    {id:"operations-manager",name:"Operations Manager",departmentId:"operations",purpose:"Owns operating standards and delivery.",reportsToRoleId:"coo",workforceType:"human"},{id:"operations-executive",name:"Operations Executive",departmentId:"operations",purpose:"Coordinates daily operational work.",reportsToRoleId:"operations-manager",workforceType:"human"},
    {id:"customer-success-manager",name:"Customer Success Manager",departmentId:"customer-success",purpose:"Owns customer continuity and advocacy.",reportsToRoleId:"operations-manager",workforceType:"human"},{id:"finance-manager",name:"Finance Manager",departmentId:"finance",purpose:"Owns financial controls and planning.",reportsToRoleId:"ceo",workforceType:"human"},{id:"hr-manager",name:"HR Manager",departmentId:"hr",purpose:"Owns people operations and policy.",reportsToRoleId:"coo",workforceType:"human"},{id:"office-administrator",name:"Office Administrator",departmentId:"administration",purpose:"Coordinates office and shared services.",reportsToRoleId:"operations-manager",workforceType:"human"},
    {id:"future-ai-executive-advisor",name:"Future AI Executive Advisor",departmentId:"executive",purpose:"Reserved advisory role; no execution or inference.",reportsToRoleId:"ceo",workforceType:"future-ai"},{id:"future-ai-sales-advisor",name:"Future AI Sales Advisor",departmentId:"sales",purpose:"Reserved advisory role; no execution or inference.",reportsToRoleId:"sales-director",workforceType:"future-ai"},{id:"future-ai-operations-advisor",name:"Future AI Operations Advisor",departmentId:"operations",purpose:"Reserved advisory role; no execution or inference.",reportsToRoleId:"operations-manager",workforceType:"future-ai"},
  ],
  offices:[
    {id:"aurora-hq",name:"Headquarters",kind:"headquarters",city:"Bengaluru",state:"Karnataka",countryCode:"IN",addressStatus:"placeholder",photoAsset:officePhoto},{id:"downtown-branch",name:"Downtown Branch",kind:"branch",city:"Bengaluru",state:"Karnataka",countryCode:"IN",addressStatus:"placeholder",photoAsset:officePhoto},{id:"luxury-division",name:"Luxury Division",kind:"division",city:"Mumbai",state:"Maharashtra",countryCode:"IN",addressStatus:"placeholder",photoAsset:officePhoto},{id:"commercial-division",name:"Commercial Division",kind:"division",city:"Hyderabad",state:"Telangana",countryCode:"IN",addressStatus:"placeholder",photoAsset:officePhoto},{id:"remote-workforce",name:"Remote Workforce",kind:"remote",city:"Remote",state:"Multi-region",countryCode:"IN",addressStatus:"placeholder",photoAsset:officePhoto},
  ],
  businessUnits:[{id:"residential",name:"Residential",description:"Residential sales and advisory."},{id:"commercial",name:"Commercial",description:"Commercial property advisory."},{id:"luxury",name:"Luxury",description:"Premium residential representation."},{id:"rentals",name:"Rentals",description:"Residential and commercial leasing."},{id:"land",name:"Land",description:"Land acquisition and disposition advisory."},{id:"investment",name:"Investment",description:"Property investment advisory."}],
  assets:[{id:"aurora-logo",kind:"company-logo",path:"/vayon/demo/aurora-logo.svg",placeholder:true,alt:"Aurora Realty Group placeholder logo"},{id:"aurora-office",kind:"office-photo",path:officePhoto,placeholder:true,alt:"Aurora office photography placeholder"},{id:"aurora-brand",kind:"brand-imagery",path:"/vayon/demo/brand-placeholder.svg",placeholder:true,alt:"Aurora brand imagery placeholder"},{id:"aurora-cover",kind:"cover-image",path:"/vayon/demo/cover-placeholder.svg",placeholder:true,alt:"Aurora workspace cover placeholder"}],
  containsBusinessRecords:false,containsAnalytics:false,containsAIOutput:false,
} satisfies DemoWorkspaceBlueprint);
