-- Sprint 50: production Stripe billing projections. Existing subscriptions and invoices remain canonical.
update public.subscription_plans set active=false where code='business';
update public.subscription_plans set name='Starter',description='CRM, leads, deals, Gmail and Calendar for small teams',monthly_price=4999,currency='INR',limits='{"ai_employees":3,"users":3,"ai_requests":1000,"tokens":1000000,"storage_gb":10,"whatsapp_messages":0,"emails":5000,"calendar_events":1000,"api_calls":10000}',features='{"CRM","Leads","Deals","Gmail","Calendar"}',active=true,sort_order=1 where code='starter';
update public.subscription_plans set name='Professional',description='Complete AI workforce and automation for growing teams',monthly_price=14999,currency='INR',limits='{"ai_employees":8,"users":null,"ai_requests":10000,"tokens":10000000,"storage_gb":100,"whatsapp_messages":10000,"emails":50000,"calendar_events":10000,"api_calls":100000}',features='{"CRM","WhatsApp","Calendar","Gmail","Analytics","Automations"}',active=true,sort_order=2 where code='professional';
update public.subscription_plans set name='Enterprise',description='Unlimited commercial platform with custom governance',monthly_price=null,currency='INR',limits='{"ai_employees":null,"users":null,"ai_requests":null,"tokens":null,"storage_gb":null,"whatsapp_messages":null,"emails":null,"calendar_events":null,"api_calls":null}',features='{"Everything enabled","Unlimited users","Unlimited AI employees","Custom governance"}',active=true,sort_order=3 where code='enterprise';

alter table public.subscriptions add column if not exists provider_price_id text;
alter table public.invoices add column if not exists payment_intent_id text;
create unique index if not exists subscriptions_provider_id_idx on public.subscriptions(provider_subscription_id) where provider_subscription_id is not null;
create unique index if not exists invoices_provider_id_idx on public.invoices(provider_invoice_id) where provider_invoice_id is not null;

create table if not exists public.billing_customers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),workspace_id uuid not null references public.workspaces(id),provider text not null default 'stripe',provider_customer_id text not null,livemode boolean not null default false,email text,tax_exempt text,tax_ids jsonb not null default '[]',address jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id),unique(provider,provider_customer_id));
create table if not exists public.subscription_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),workspace_id uuid not null references public.workspaces(id),subscription_id uuid not null references public.subscriptions(id),provider_item_id text not null,provider_price_id text not null,quantity integer not null default 1 check(quantity>0),metered boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(provider_item_id));
create table if not exists public.payment_methods(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),workspace_id uuid not null references public.workspaces(id),billing_customer_id uuid references public.billing_customers(id),provider_payment_method_id text not null,type text not null,brand text,last4 char(4),expiry_month integer,expiry_year integer,is_default boolean not null default false,created_at timestamptz not null default now(),detached_at timestamptz,unique(provider_payment_method_id));
create table if not exists public.billing_events(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id),workspace_id uuid references public.workspaces(id),provider text not null default 'stripe',provider_event_id text not null,event_type text not null,status text not null check(status in('received','processed','ignored','failed')),payload jsonb not null default '{}',error_code text,created_at timestamptz not null default now(),processed_at timestamptz,unique(provider,provider_event_id));
create table if not exists public.usage_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),workspace_id uuid not null references public.workspaces(id),metric text not null check(metric in('ai_requests','tokens','storage_gb','users','whatsapp_messages','emails','calendar_events','api_calls')),quantity numeric(18,3) not null check(quantity>=0),idempotency_key text not null,provider_event_id text,occurred_at timestamptz not null default now(),created_at timestamptz not null default now(),unique(workspace_id,idempotency_key));

alter table public.billing_customers enable row level security;alter table public.subscription_items enable row level security;alter table public.payment_methods enable row level security;alter table public.billing_events enable row level security;alter table public.usage_events enable row level security;
drop policy if exists "subscriptions_admin_read" on public.subscriptions;drop policy if exists "usage_admin_read" on public.organization_usage;drop policy if exists "limits_admin_read" on public.organization_limits;drop policy if exists "invoices_admin_read" on public.invoices;drop policy if exists "billing_contacts_admin_read" on public.billing_contacts;
create policy "subscriptions_billing_read" on public.subscriptions for select to authenticated using(public.is_organization_member(organization_id)and public.current_workspace_role(workspace_id)in('organization_owner','organization_admin','billing_admin','finance','finance_manager','finance_analyst','read_only'));
create policy "usage_billing_read" on public.organization_usage for select to authenticated using(public.is_organization_member(organization_id)and public.current_workspace_role(workspace_id)in('organization_owner','organization_admin','billing_admin','finance','finance_manager','finance_analyst','read_only'));
create policy "limits_billing_read" on public.organization_limits for select to authenticated using(public.is_organization_member(organization_id)and public.current_workspace_role(workspace_id)in('organization_owner','organization_admin','billing_admin','finance','finance_manager','finance_analyst','read_only'));
create policy "invoices_billing_read" on public.invoices for select to authenticated using(public.is_organization_member(organization_id)and public.current_workspace_role(workspace_id)in('organization_owner','organization_admin','billing_admin','finance','finance_manager','finance_analyst','read_only'));
create policy "billing_contacts_billing_read" on public.billing_contacts for select to authenticated using(public.is_organization_member(organization_id)and public.current_workspace_role(workspace_id)in('organization_owner','organization_admin','billing_admin','finance','finance_manager','finance_analyst','read_only'));
create policy "billing_customers_read" on public.billing_customers for select to authenticated using(public.is_organization_member(organization_id) and public.current_workspace_role(workspace_id) in('organization_owner','organization_admin','billing_admin','finance','finance_manager','finance_analyst','read_only'));
create policy "subscription_items_read" on public.subscription_items for select to authenticated using(public.is_organization_member(organization_id) and public.current_workspace_role(workspace_id) in('organization_owner','organization_admin','billing_admin','finance','finance_manager','finance_analyst','read_only'));
create policy "payment_methods_read" on public.payment_methods for select to authenticated using(public.is_organization_member(organization_id) and public.current_workspace_role(workspace_id) in('organization_owner','organization_admin','billing_admin','finance','finance_manager','finance_analyst','read_only'));
create policy "billing_events_read" on public.billing_events for select to authenticated using(public.is_organization_member(organization_id) and public.current_workspace_role(workspace_id) in('organization_owner','organization_admin','billing_admin','finance','finance_manager','finance_analyst','read_only'));
create policy "usage_events_read" on public.usage_events for select to authenticated using(public.is_organization_member(organization_id) and public.current_workspace_role(workspace_id) in('organization_owner','organization_admin','billing_admin','finance','finance_manager','finance_analyst','read_only'));

create or replace function public.record_billing_usage(p_workspace_id uuid,p_metric text,p_quantity numeric,p_idempotency_key text) returns void language plpgsql security definer set search_path=public as $$declare v_org uuid;v_limit numeric;v_used numeric;v_start date=date_trunc('month',now())::date;v_end date=(date_trunc('month',now())+interval '1 month'-interval '1 day')::date;begin if p_quantity<0 or p_metric not in('ai_requests','tokens','storage_gb','users','whatsapp_messages','emails','calendar_events','api_calls')then raise exception'invalid usage event';end if;select organization_id into v_org from workspaces where id=p_workspace_id;if v_org is null then raise exception'workspace not found';end if;select limit_value into v_limit from organization_limits where workspace_id=p_workspace_id and metric=p_metric;select coalesce(quantity,0) into v_used from organization_usage where workspace_id=p_workspace_id and metric=p_metric and period_start=v_start;if v_limit is not null and coalesce(v_used,0)+p_quantity>v_limit then raise exception'subscription limit exceeded for %',p_metric;end if;insert into usage_events(organization_id,workspace_id,metric,quantity,idempotency_key)values(v_org,p_workspace_id,p_metric,p_quantity,p_idempotency_key)on conflict(workspace_id,idempotency_key)do nothing;if found then insert into organization_usage(organization_id,workspace_id,metric,quantity,period_start,period_end)values(v_org,p_workspace_id,p_metric,p_quantity,v_start,v_end)on conflict(workspace_id,metric,period_start)do update set quantity=organization_usage.quantity+excluded.quantity,updated_at=now();end if;end$$;

create or replace function public.process_stripe_billing_event(p_event_id text,p_event_type text,p_payload jsonb) returns void language plpgsql security definer set search_path=public as $$declare v_org uuid;v_workspace uuid;v_customer uuid;v_subscription uuid;begin if current_setting('role',true)<>'service_role'then raise exception'service role required';end if;v_org=nullif(coalesce(p_payload->'metadata'->>'organization_id',p_payload->'subscription_details'->'metadata'->>'organization_id'),'')::uuid;v_workspace=nullif(coalesce(p_payload->'metadata'->>'workspace_id',p_payload->'subscription_details'->'metadata'->>'workspace_id'),'')::uuid;if v_workspace is null and v_org is not null then select id into v_workspace from workspaces where organization_id=v_org and status='active' order by created_at limit 1;end if;insert into billing_events(organization_id,workspace_id,provider_event_id,event_type,status,payload)values(v_org,v_workspace,p_event_id,p_event_type,'received',p_payload)on conflict(provider,provider_event_id)do nothing;if not found then return;end if;
if p_event_type='checkout.session.completed' then insert into billing_customers(organization_id,workspace_id,provider_customer_id,livemode,email)values(v_org,v_workspace,p_payload->>'customer',coalesce((p_payload->>'livemode')::boolean,false),p_payload->'customer_details'->>'email')on conflict(workspace_id)do update set provider_customer_id=excluded.provider_customer_id,email=excluded.email,updated_at=now();
elsif p_event_type='customer.updated' then update billing_customers set email=p_payload->>'email',address=coalesce(p_payload->'address','{}'),tax_exempt=coalesce(p_payload->>'tax_exempt','none'),updated_at=now() where provider_customer_id=p_payload->>'id';
elsif p_event_type like 'customer.subscription.%' then select organization_id,id into v_org,v_workspace from workspaces where id=coalesce(v_workspace,(select workspace_id from billing_customers where provider_customer_id=p_payload->>'customer'));select id into v_subscription from subscriptions where workspace_id=v_workspace and deleted_at is null;update subscriptions set provider='stripe',provider_customer_id=p_payload->>'customer',provider_subscription_id=p_payload->>'id',status=case p_payload->>'status' when'active'then'active' when'trialing'then'trialing' when'past_due'then'past_due' when'canceled'then'cancelled' else status end,cancel_at_period_end=coalesce((p_payload->>'cancel_at_period_end')::boolean,false),trial_ends_at=case when p_payload->>'trial_end'is null then null else to_timestamp((p_payload->>'trial_end')::bigint)end,current_period_ends_at=case when p_payload->>'current_period_end'is null then current_period_ends_at else to_timestamp((p_payload->>'current_period_end')::bigint)end,updated_at=now(),version=version+1 where id=v_subscription;insert into subscription_items(organization_id,workspace_id,subscription_id,provider_item_id,provider_price_id,quantity,metered)select v_org,v_workspace,v_subscription,item->>'id',item->'price'->>'id',greatest(1,coalesce((item->>'quantity')::integer,1)),coalesce((item->'price'->'recurring'->>'usage_type')='metered',false)from jsonb_array_elements(coalesce(p_payload->'items'->'data','[]'))item on conflict(provider_item_id)do update set provider_price_id=excluded.provider_price_id,quantity=excluded.quantity,metered=excluded.metered,updated_at=now();
elsif p_event_type like 'invoice.%' then select workspace_id into v_workspace from billing_customers where provider_customer_id=p_payload->>'customer';select id into v_subscription from subscriptions where workspace_id=v_workspace and deleted_at is null;insert into invoices(organization_id,workspace_id,subscription_id,invoice_number,status,currency,subtotal,tax,issued_at,due_at,paid_at,download_url,provider_invoice_id,payment_intent_id,created_by,metadata)select organization_id,v_workspace,v_subscription,coalesce(p_payload->>'number',p_payload->>'id'),case when p_event_type='invoice.paid'then'paid'when p_event_type='invoice.payment_failed'then'failed'else coalesce(p_payload->>'status','open')end,upper(coalesce(p_payload->>'currency','inr')),coalesce((p_payload->>'subtotal')::numeric/100,0),coalesce((p_payload->'total_tax_amounts'->0->>'amount')::numeric/100,0),to_timestamp((p_payload->>'created')::bigint),case when p_payload->>'due_date'is null then null else to_timestamp((p_payload->>'due_date')::bigint)end,case when p_event_type='invoice.paid'then now()end,p_payload->>'hosted_invoice_url',p_payload->>'id',p_payload->>'payment_intent',created_by,p_payload from subscriptions where id=v_subscription on conflict(provider_invoice_id)do update set status=excluded.status,paid_at=excluded.paid_at,download_url=excluded.download_url,metadata=excluded.metadata,updated_at=now();
elsif p_event_type like 'payment_method.%' then select id,workspace_id into v_customer,v_workspace from billing_customers where provider_customer_id=p_payload->>'customer';if p_event_type='payment_method.attached'then insert into payment_methods(organization_id,workspace_id,billing_customer_id,provider_payment_method_id,type,brand,last4,expiry_month,expiry_year)select organization_id,workspace_id,id,p_payload->>'id',p_payload->>'type',p_payload->'card'->>'brand',p_payload->'card'->>'last4',(p_payload->'card'->>'exp_month')::integer,(p_payload->'card'->>'exp_year')::integer from billing_customers where id=v_customer on conflict(provider_payment_method_id)do update set detached_at=null;else update payment_methods set detached_at=now(),is_default=false where provider_payment_method_id=p_payload->>'id';end if;end if;update billing_events set status='processed',processed_at=now(),organization_id=coalesce(organization_id,v_org),workspace_id=coalesce(workspace_id,v_workspace)where provider_event_id=p_event_id;exception when others then update billing_events set status='failed',error_code=sqlstate,processed_at=now()where provider_event_id=p_event_id;raise;end$$;

revoke all on function public.record_billing_usage(uuid,text,numeric,text),public.process_stripe_billing_event(text,text,jsonb) from public;grant execute on function public.record_billing_usage(uuid,text,numeric,text) to authenticated,service_role;grant execute on function public.process_stripe_billing_event(text,text,jsonb) to service_role;
create or replace function public.reactivate_subscription(p_workspace_id uuid,p_expected_version integer)returns void language plpgsql security definer set search_path=public as $$begin if not can_manage_billing(p_workspace_id)then raise exception'insufficient billing permission';end if;update subscriptions set cancel_at_period_end=false,updated_by=auth.uid(),updated_at=now(),version=version+1 where workspace_id=p_workspace_id and version=p_expected_version and deleted_at is null;if not found then raise exception'subscription changed by another user';end if;end$$;
revoke all on function public.reactivate_subscription(uuid,integer)from public;grant execute on function public.reactivate_subscription(uuid,integer)to authenticated;
