-- Online-safe, idempotent indexes for tenant pagination, queue claiming, approvals, timelines, AI telemetry, and knowledge search.
create index if not exists ai_runtime_outputs_performance_idx on public.ai_runtime_outputs(organization_id,workspace_id,created_at desc)include(latency_ms,input_tokens,output_tokens,cost_estimate);
create index if not exists workflow_instances_performance_idx on public.workflow_instances(organization_id,workspace_id,created_at desc)include(duration_ms,status,retry_count);
create index if not exists workflow_approvals_lookup_idx on public.workflow_automation_approvals(workspace_id,status,requested_at)where status='pending';
create index if not exists workflow_queue_throughput_idx on public.workflow_trigger_events(workspace_id,status,available_at)include(attempts)where status in('pending','processing');
create index if not exists notification_queue_throughput_idx on public.notification_queue(workspace_id,status,next_attempt_at)include(attempts,created_at,delivered_at)where status in('queued','processing','sent');
create index if not exists notification_preferences_lookup_idx on public.notification_preferences(workspace_id,user_id);
create index if not exists knowledge_articles_listing_idx on public.knowledge_articles(organization_id,workspace_id,status,updated_at desc)where deleted_at is null;
create index if not exists knowledge_documents_listing_idx on public.knowledge_documents(organization_id,workspace_id,status,created_at desc)where deleted_at is null;
create index if not exists knowledge_analytics_performance_idx on public.knowledge_analytics(organization_id,workspace_id,created_at desc)include(event_type,latency_ms,success);
create or replace function public.enterprise_performance_snapshot(p_workspace_id uuid)returns table(api_latency_ms numeric,database_latency_ms numeric,workflow_latency_ms numeric,ai_latency_ms numeric,notification_latency_ms numeric,slow_queries bigint,slow_endpoints bigint)language plpgsql stable security definer set search_path=public as $$declare v_started timestamptz:=clock_timestamp();begin if public.current_workspace_role(p_workspace_id)is null then raise exception'workspace access required';end if;return query select(select round(avg(latency_ms))from integration_logs where workspace_id=p_workspace_id and occurred_at>now()-interval'24 hours'),(extract(epoch from(clock_timestamp()-v_started))*1000)::numeric,(select round(avg(duration_ms))from workflow_instances where workspace_id=p_workspace_id and created_at>now()-interval'24 hours'),(select round(avg(latency_ms))from ai_runtime_outputs where workspace_id=p_workspace_id and created_at>now()-interval'24 hours'),(select round(avg(extract(epoch from(coalesce(delivered_at,updated_at)-created_at))*1000))from notification_queue where workspace_id=p_workspace_id and status='sent'and created_at>now()-interval'24 hours'),(select count(*)from integration_logs where workspace_id=p_workspace_id and duration_ms>1000 and occurred_at>now()-interval'24 hours'),(select count(*)from integration_logs where workspace_id=p_workspace_id and duration_ms>500 and occurred_at>now()-interval'24 hours');end$$;
revoke all on function public.enterprise_performance_snapshot(uuid)from public;grant execute on function public.enterprise_performance_snapshot(uuid)to authenticated;
