-- Sprint 82: Creative Studio Beta. Tenant-scoped, draft-only, no publishing or rendering.
create table if not exists public.creative_brand_kits(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,workspace_id uuid not null references public.workspaces(id) on delete cascade,name text not null,logo_path text,secondary_logo_path text,colors text[] not null default '{}',typography text[] not null default '{}',fonts text[] not null default '{}',icons text[] not null default '{}',watermarks text[] not null default '{}',email_signature text,phone text,address text,website text,social_links jsonb not null default '{}',legal_disclaimer text,rera_information text,tone text not null default 'Professional real estate',created_by uuid not null references auth.users(id),updated_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version integer not null default 1,unique(workspace_id,name)
);
create table if not exists public.creative_campaigns(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,workspace_id uuid not null references public.workspaces(id) on delete cascade,project_id uuid not null references public.inventory_projects(id),name text not null check(char_length(name) between 1 and 160),status text not null default 'draft' check(status in('draft','marketing-review','sales-review','management-approval','approved','ready-to-publish')),brief jsonb not null,payload jsonb not null default '{}',selected_variation text check(selected_variation in('Version A','Version B','Version C')),created_by uuid not null references auth.users(id),updated_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version integer not null default 1
);
create table if not exists public.creative_assets(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,workspace_id uuid not null references public.workspaces(id) on delete cascade,campaign_id uuid not null references public.creative_campaigns(id) on delete cascade,project_id uuid not null references public.inventory_projects(id),name text not null,category text not null check(category in('flyer','video','brochure','image','social-post','presentation')),format text not null,platform text not null,language text not null,status text not null default 'draft' check(status in('draft','marketing-review','sales-review','management-approval','approved','ready-to-publish')),prompt text not null,ai_employee text not null,approver uuid references auth.users(id),edits text[] not null default '{}',exports text[] not null default '{}',publishing_history text[] not null default '{}',storyboard jsonb,generated_at timestamptz not null default now(),created_by uuid not null references auth.users(id),version integer not null default 1
);
create table if not exists public.creative_timeline(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,workspace_id uuid not null references public.workspaces(id) on delete cascade,campaign_id uuid references public.creative_campaigns(id) on delete cascade,asset_id uuid references public.creative_assets(id) on delete cascade,event_type text not null,prompt_reference text,ai_employee text,project_id uuid references public.inventory_projects(id),approver uuid references auth.users(id),metadata jsonb not null default '{}',actor_id uuid not null references auth.users(id),occurred_at timestamptz not null default now(),check(campaign_id is not null or asset_id is not null)
);
create index if not exists creative_campaign_recent_idx on public.creative_campaigns(organization_id,workspace_id,updated_at desc);
create index if not exists creative_asset_search_idx on public.creative_assets(organization_id,workspace_id,project_id,platform,language,status,generated_at desc);
create index if not exists creative_timeline_idx on public.creative_timeline(organization_id,workspace_id,occurred_at desc);
alter table public.creative_brand_kits enable row level security;alter table public.creative_campaigns enable row level security;alter table public.creative_assets enable row level security;alter table public.creative_timeline enable row level security;
create or replace function public.creative_studio_member(p_org uuid,p_workspace uuid)returns boolean language sql stable security definer set search_path=public as $$select auth.uid() is not null and public.is_organization_member(p_org) and public.current_workspace_role(p_workspace) is not null and exists(select 1 from public.workspaces where id=p_workspace and organization_id=p_org)$$;
create or replace function public.creative_studio_manage(p_workspace uuid)returns boolean language sql stable security definer set search_path=public as $$select public.current_workspace_role(p_workspace) in('organization_owner','organization_admin','administrator','marketing','sales_manager','project_manager')$$;
create or replace function public.creative_studio_access()returns text language sql stable security definer set search_path=public as $$select case when exists(select 1 from public.feature_flags f join public.feature_flag_assignments a on a.flag_id=f.id and a.deleted_at is null and a.enabled=true join public.workspace_members wm on wm.organization_id=a.assignment_value::uuid and wm.user_id=auth.uid() and wm.status='active' where f.key='creative_studio_beta' and f.status in('enabled','beta') and f.deleted_at is null and a.assignment_type='organization') then 'selected-beta' else 'disabled' end$$;
create policy "creative_brand_read" on public.creative_brand_kits for select to authenticated using(public.creative_studio_member(organization_id,workspace_id));create policy "creative_brand_write" on public.creative_brand_kits for all to authenticated using(public.creative_studio_member(organization_id,workspace_id)and public.creative_studio_manage(workspace_id))with check(public.creative_studio_member(organization_id,workspace_id)and public.creative_studio_manage(workspace_id));
create policy "creative_campaign_read" on public.creative_campaigns for select to authenticated using(public.creative_studio_member(organization_id,workspace_id));create policy "creative_campaign_write" on public.creative_campaigns for all to authenticated using(public.creative_studio_member(organization_id,workspace_id)and public.creative_studio_manage(workspace_id))with check(public.creative_studio_member(organization_id,workspace_id)and public.creative_studio_manage(workspace_id));
create policy "creative_asset_read" on public.creative_assets for select to authenticated using(public.creative_studio_member(organization_id,workspace_id));create policy "creative_asset_write" on public.creative_assets for all to authenticated using(public.creative_studio_member(organization_id,workspace_id)and public.creative_studio_manage(workspace_id))with check(public.creative_studio_member(organization_id,workspace_id)and public.creative_studio_manage(workspace_id));
create policy "creative_timeline_read" on public.creative_timeline for select to authenticated using(public.creative_studio_member(organization_id,workspace_id));create policy "creative_timeline_insert" on public.creative_timeline for insert to authenticated with check(public.creative_studio_member(organization_id,workspace_id)and actor_id=auth.uid());
create or replace function public.create_creative_campaign_draft(p_input jsonb)returns uuid language plpgsql security definer set search_path=public as $$declare w uuid;o uuid;i uuid;begin select wm.workspace_id,wm.organization_id into w,o from public.workspace_members wm where wm.user_id=auth.uid()and wm.status='active'order by wm.created_at limit 1;if w is null or not public.creative_studio_manage(w)then raise exception'insufficient creative studio permission';end if;if not exists(select 1 from public.inventory_projects p where p.id=(p_input->>'projectId')::uuid and p.organization_id=o and p.workspace_id=w)then raise exception'invalid project';end if;insert into public.creative_campaigns(organization_id,workspace_id,project_id,name,status,brief,payload,created_by,updated_by)values(o,w,(p_input->>'projectId')::uuid,left(trim(p_input->>'name'),160),'draft',p_input->'brief',p_input->'payload',auth.uid(),auth.uid())returning id into i;insert into public.creative_timeline(organization_id,workspace_id,campaign_id,event_type,prompt_reference,ai_employee,project_id,metadata,actor_id)values(o,w,i,'campaign.draft_created','Sanitized campaign brief','AI Workforce collaboration',(p_input->>'projectId')::uuid,jsonb_build_object('status','draft','recommendation_only',true,'live_publishing',false),auth.uid());return i;end$$;
create or replace function public.advance_creative_campaign(p_campaign uuid,p_expected_version integer,p_next text)returns void language plpgsql security definer set search_path=public as $$declare c public.creative_campaigns%rowtype;expected text;begin select*into c from public.creative_campaigns where id=p_campaign for update;if not found or not public.creative_studio_manage(c.workspace_id)then raise exception'insufficient creative approval permission';end if;if c.version<>p_expected_version then raise exception'campaign changed';end if;expected=case c.status when'draft'then'marketing-review'when'marketing-review'then'sales-review'when'sales-review'then'management-approval'when'management-approval'then'approved'when'approved'then'ready-to-publish'end;if p_next is distinct from expected then raise exception'invalid approval transition';end if;update public.creative_campaigns set status=p_next,updated_by=auth.uid(),updated_at=now(),version=version+1 where id=c.id;insert into public.creative_timeline(organization_id,workspace_id,campaign_id,event_type,project_id,approver,actor_id,metadata)values(c.organization_id,c.workspace_id,c.id,'campaign.'||p_next,c.project_id,auth.uid(),auth.uid(),jsonb_build_object('previous',c.status,'next',p_next));end$$;
revoke all on function public.creative_studio_access()from public;grant execute on function public.creative_studio_access()to authenticated;revoke all on function public.create_creative_campaign_draft(jsonb)from public;grant execute on function public.create_creative_campaign_draft(jsonb)to authenticated;revoke all on function public.advance_creative_campaign(uuid,integer,text)from public;grant execute on function public.advance_creative_campaign(uuid,integer,text)to authenticated;
