-- Sprint 51: Enterprise Organization & Team Management
alter table public.organizations add column if not exists business_email text;
alter table public.organizations add column if not exists locale text not null default 'en-IN';
alter table public.organizations add column if not exists address jsonb not null default '{}';
alter table public.organizations add column if not exists branding jsonb not null default '{}';
alter table public.organizations add column if not exists version integer not null default 1;
alter table public.invitations add column if not exists resent_at timestamptz;
alter table public.invitations add column if not exists accepted_at timestamptz;
alter table public.invitations add column if not exists cancelled_at timestamptz;
alter table public.invitations drop constraint if exists invitations_organization_id_email_status_key;
create unique index if not exists invitations_one_pending_email_idx on public.invitations(organization_id,lower(email))where status='pending';
alter table public.organization_members add column if not exists updated_at timestamptz not null default now();
alter table public.workspace_members add column if not exists updated_at timestamptz not null default now();

insert into public.roles(code,name,scope)values
('organization_owner','Organization Owner','organization'),('organization_admin','Administrator','organization'),('manager','Manager','workspace'),('sales','Sales','workspace'),('marketing','Marketing','workspace'),('operations','Operations','workspace'),('finance','Finance','workspace'),('support','Support','workspace'),('read_only','Read-only','organization')
on conflict(code)do update set name=excluded.name,scope=excluded.scope;

create table if not exists public.permissions(id uuid primary key default gen_random_uuid(),key text unique not null,name text not null,scope text not null,created_at timestamptz not null default now());
create table if not exists public.role_permissions(role_id uuid not null references public.roles(id)on delete cascade,permission_id uuid not null references public.permissions(id)on delete cascade,created_at timestamptz not null default now(),primary key(role_id,permission_id));
insert into public.permissions(key,name,scope)values('organization.read','Read organization','organization'),('organization.update','Update organization','organization'),('members.read','Read members','organization'),('members.manage','Manage members','organization'),('roles.read','Read roles','organization'),('roles.manage','Manage roles','organization'),('audit.read','Read audit','organization'),('ownership.transfer','Transfer ownership','organization'),('crm.manage','Manage CRM','workspace'),('sales.manage','Manage sales','workspace'),('marketing.manage','Manage marketing','workspace'),('operations.manage','Manage operations','workspace'),('finance.manage','Manage finance','workspace'),('support.manage','Manage support','workspace')on conflict(key)do update set name=excluded.name,scope=excluded.scope;
insert into public.role_permissions(role_id,permission_id)select r.id,p.id from roles r cross join permissions p where(r.code='organization_owner')or(r.code='organization_admin'and p.key<>'ownership.transfer')or(r.code='manager'and p.key in('organization.read','members.read','roles.read','audit.read','crm.manage','sales.manage','marketing.manage','operations.manage'))or(r.code='sales'and p.key in('organization.read','members.read','crm.manage','sales.manage'))or(r.code='marketing'and p.key in('organization.read','members.read','marketing.manage'))or(r.code='operations'and p.key in('organization.read','members.read','operations.manage'))or(r.code='finance'and p.key in('organization.read','members.read','finance.manage'))or(r.code='support'and p.key in('organization.read','members.read','support.manage'))or(r.code='read_only'and p.key in('organization.read','members.read','roles.read','audit.read'))on conflict do nothing;

create table if not exists public.organization_audit_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),workspace_id uuid not null references public.workspaces(id),actor_id uuid not null references auth.users(id),event_type text not null check(event_type in('organization.updated','invitation.sent','invitation.resent','invitation.cancelled','invitation.accepted','member.role_changed','member.suspended','member.reactivated','member.removed','ownership.transferred')),subject_id uuid,metadata jsonb not null default '{}',occurred_at timestamptz not null default now());
create index if not exists organization_audit_tenant_time_idx on public.organization_audit_events(organization_id,workspace_id,occurred_at desc);
alter table public.permissions enable row level security;alter table public.role_permissions enable row level security;alter table public.organization_audit_events enable row level security;
create policy "permissions_authenticated_read" on public.permissions for select to authenticated using(true);
create policy "role_permissions_authenticated_read" on public.role_permissions for select to authenticated using(true);
create policy "organization_audit_member_read" on public.organization_audit_events for select to authenticated using(public.is_organization_member(organization_id)and exists(select 1 from workspace_members wm where wm.workspace_id=organization_audit_events.workspace_id and wm.user_id=auth.uid()and wm.status='active'));
create policy "organization_profiles_peer_read" on public.user_profiles for select to authenticated using(user_id=auth.uid()or exists(select 1 from organization_members mine join organization_members peer on peer.organization_id=mine.organization_id where mine.user_id=auth.uid()and mine.status='active'and peer.user_id=user_profiles.user_id and peer.status in('active','suspended')));

create or replace function public.enterprise_org_context(p_workspace_id uuid,p_owner_only boolean default false)returns uuid language plpgsql stable security definer set search_path=public as $$declare v_org uuid;v_role text;begin select wm.organization_id into v_org from workspace_members wm where wm.workspace_id=p_workspace_id and wm.user_id=auth.uid()and wm.status='active';v_role:=public.current_workspace_role(p_workspace_id);if v_org is null or v_role not in('organization_owner','organization_admin')or(p_owner_only and v_role<>'organization_owner')then raise exception'insufficient organization permission';end if;return v_org;end$$;
create or replace function public.update_enterprise_organization(p_workspace_id uuid,p_input jsonb)returns void language plpgsql security definer set search_path=public as $$declare v_org uuid:=enterprise_org_context(p_workspace_id);begin update organizations set name=trim(p_input->>'name'),business_email=lower(p_input->>'businessEmail'),phone=nullif(trim(p_input->>'phone'),''),website=nullif(trim(p_input->>'website'),''),timezone=p_input->>'timezone',locale=p_input->>'locale',currency=upper(p_input->>'currency'),address=coalesce(p_input->'address','{}'),branding=coalesce(p_input->'branding','{}'),updated_at=now(),version=version+1 where id=v_org;insert into organization_audit_events(organization_id,workspace_id,actor_id,event_type,metadata)values(v_org,p_workspace_id,auth.uid(),'organization.updated',jsonb_build_object('profile_version','updated'));end$$;
create or replace function public.set_enterprise_organization_logo(p_workspace_id uuid,p_logo_path text)returns void language plpgsql security definer set search_path=public as $$declare v_org uuid:=enterprise_org_context(p_workspace_id);begin if p_logo_path not like v_org::text||'/'||p_workspace_id::text||'/company-logo/%'then raise exception'invalid logo path';end if;update organizations set logo_path=p_logo_path,updated_at=now(),version=version+1 where id=v_org;insert into organization_audit_events(organization_id,workspace_id,actor_id,event_type,metadata)values(v_org,p_workspace_id,auth.uid(),'organization.updated','{"field":"logo"}');end$$;
create or replace function public.invite_organization_member(p_workspace_id uuid,p_name text,p_email text,p_role text)returns uuid language plpgsql security definer set search_path=public as $$declare v_org uuid:=enterprise_org_context(p_workspace_id);v_role uuid;v_id uuid;begin select id into v_role from roles where code=p_role and code in('organization_admin','manager','sales','marketing','operations','finance','support','read_only');if v_role is null then raise exception'invalid role';end if;if exists(select 1 from auth.users u join organization_members om on om.user_id=u.id where om.organization_id=v_org and lower(u.email)=lower(p_email)and om.status<>'removed')then raise exception'user is already a member';end if;update invitations set status='cancelled',cancelled_at=now()where organization_id=v_org and lower(email)=lower(p_email)and status='pending';insert into invitations(organization_id,workspace_id,email,name,role_id,status,expires_at,invited_by)values(v_org,p_workspace_id,lower(trim(p_email)),trim(p_name),v_role,'pending',now()+interval'7 days',auth.uid())returning id into v_id;insert into organization_audit_events(organization_id,workspace_id,actor_id,event_type,subject_id,metadata)values(v_org,p_workspace_id,auth.uid(),'invitation.sent',v_id,jsonb_build_object('role',p_role));return v_id;end$$;
create or replace function public.resend_organization_invitation(p_workspace_id uuid,p_invitation_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare v_org uuid:=enterprise_org_context(p_workspace_id);v_email text;begin update invitations set expires_at=now()+interval'7 days',resent_at=now()where id=p_invitation_id and organization_id=v_org and workspace_id=p_workspace_id and status='pending'returning email into v_email;if v_email is null then raise exception'pending invitation not found';end if;insert into organization_audit_events(organization_id,workspace_id,actor_id,event_type,subject_id)values(v_org,p_workspace_id,auth.uid(),'invitation.resent',p_invitation_id);return jsonb_build_object('email',v_email);end$$;
create or replace function public.cancel_organization_invitation(p_workspace_id uuid,p_invitation_id uuid)returns void language plpgsql security definer set search_path=public as $$declare v_org uuid:=enterprise_org_context(p_workspace_id);begin update invitations set status='cancelled',cancelled_at=now()where id=p_invitation_id and organization_id=v_org and workspace_id=p_workspace_id and status='pending';if not found then raise exception'pending invitation not found';end if;insert into organization_audit_events(organization_id,workspace_id,actor_id,event_type,subject_id)values(v_org,p_workspace_id,auth.uid(),'invitation.cancelled',p_invitation_id);end$$;
create or replace function public.accept_organization_invitation()returns uuid language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_email text;v_inv invitations%rowtype;begin if v_user is null then raise exception'authentication required';end if;select lower(email)into v_email from auth.users where id=v_user;select*into v_inv from invitations where lower(email)=v_email and status='pending'and expires_at>now()order by created_at desc limit 1 for update;if not found then raise exception'valid invitation not found';end if;insert into organization_members(organization_id,user_id,role_id,status)values(v_inv.organization_id,v_user,v_inv.role_id,'active')on conflict(organization_id,user_id)do update set role_id=excluded.role_id,status='active',updated_at=now();insert into workspace_members(workspace_id,organization_id,user_id,role_id,status)values(v_inv.workspace_id,v_inv.organization_id,v_user,v_inv.role_id,'active')on conflict(workspace_id,user_id)do update set role_id=excluded.role_id,status='active',updated_at=now();update invitations set status='accepted',accepted_at=now()where id=v_inv.id;insert into organization_audit_events(organization_id,workspace_id,actor_id,event_type,subject_id)values(v_inv.organization_id,v_inv.workspace_id,v_user,'invitation.accepted',v_inv.id);return v_inv.workspace_id;end$$;
create or replace function public.change_organization_member_role(p_workspace_id uuid,p_member_id uuid,p_role text)returns void language plpgsql security definer set search_path=public as $$declare v_org uuid:=enterprise_org_context(p_workspace_id);v_role uuid;v_user uuid;begin select id into v_role from roles where code=p_role and code in('organization_admin','manager','sales','marketing','operations','finance','support','read_only');select user_id into v_user from workspace_members where id=p_member_id and organization_id=v_org and workspace_id=p_workspace_id and status<>'removed';if v_role is null or v_user is null then raise exception'invalid member or role';end if;if exists(select 1 from workspace_members wm join roles r on r.id=wm.role_id where wm.id=p_member_id and r.code='organization_owner')then raise exception'owner role cannot be changed';end if;update workspace_members set role_id=v_role,updated_at=now()where id=p_member_id;update organization_members set role_id=v_role,updated_at=now()where organization_id=v_org and user_id=v_user;insert into organization_audit_events(organization_id,workspace_id,actor_id,event_type,subject_id,metadata)values(v_org,p_workspace_id,auth.uid(),'member.role_changed',v_user,jsonb_build_object('role',p_role));end$$;
create or replace function public.set_organization_member_status(p_workspace_id uuid,p_member_id uuid,p_status text)returns void language plpgsql security definer set search_path=public as $$declare v_org uuid:=enterprise_org_context(p_workspace_id);v_user uuid;begin if p_status not in('active','suspended')then raise exception'invalid status';end if;select wm.user_id into v_user from workspace_members wm join roles r on r.id=wm.role_id where wm.id=p_member_id and wm.organization_id=v_org and wm.workspace_id=p_workspace_id and r.code<>'organization_owner';if v_user is null or v_user=auth.uid()then raise exception'member cannot be changed';end if;update workspace_members set status=p_status,updated_at=now()where id=p_member_id;update organization_members set status=p_status,updated_at=now()where organization_id=v_org and user_id=v_user;insert into organization_audit_events(organization_id,workspace_id,actor_id,event_type,subject_id)values(v_org,p_workspace_id,auth.uid(),case when p_status='active'then'member.reactivated'else'member.suspended'end,v_user);end$$;
create or replace function public.remove_organization_member(p_workspace_id uuid,p_member_id uuid)returns void language plpgsql security definer set search_path=public as $$declare v_org uuid:=enterprise_org_context(p_workspace_id);v_user uuid;begin select wm.user_id into v_user from workspace_members wm join roles r on r.id=wm.role_id where wm.id=p_member_id and wm.organization_id=v_org and wm.workspace_id=p_workspace_id and r.code<>'organization_owner';if v_user is null or v_user=auth.uid()then raise exception'member cannot be removed';end if;update workspace_members set status='removed',updated_at=now()where id=p_member_id;update organization_members set status='removed',updated_at=now()where organization_id=v_org and user_id=v_user;insert into organization_audit_events(organization_id,workspace_id,actor_id,event_type,subject_id)values(v_org,p_workspace_id,auth.uid(),'member.removed',v_user);end$$;
create or replace function public.transfer_organization_ownership(p_workspace_id uuid,p_member_id uuid,p_confirmation text)returns void language plpgsql security definer set search_path=public as $$declare v_org uuid:=enterprise_org_context(p_workspace_id,true);v_target uuid;v_owner_role uuid;v_admin_role uuid;begin if p_confirmation<>'TRANSFER'then raise exception'ownership confirmation required';end if;select user_id into v_target from workspace_members where id=p_member_id and organization_id=v_org and workspace_id=p_workspace_id and status='active';if v_target is null or v_target=auth.uid()then raise exception'invalid ownership target';end if;select id into v_owner_role from roles where code='organization_owner';select id into v_admin_role from roles where code='organization_admin';update organization_members set role_id=v_admin_role,updated_at=now()where organization_id=v_org and user_id=auth.uid();update workspace_members set role_id=v_admin_role,updated_at=now()where workspace_id=p_workspace_id and user_id=auth.uid();update organization_members set role_id=v_owner_role,updated_at=now()where organization_id=v_org and user_id=v_target;update workspace_members set role_id=v_owner_role,updated_at=now()where workspace_id=p_workspace_id and user_id=v_target;insert into organization_audit_events(organization_id,workspace_id,actor_id,event_type,subject_id,metadata)values(v_org,p_workspace_id,auth.uid(),'ownership.transferred',v_target,jsonb_build_object('previous_owner',auth.uid()));end$$;

revoke all on function public.enterprise_org_context(uuid,boolean),public.update_enterprise_organization(uuid,jsonb),public.set_enterprise_organization_logo(uuid,text),public.invite_organization_member(uuid,text,text,text),public.resend_organization_invitation(uuid,uuid),public.cancel_organization_invitation(uuid,uuid),public.accept_organization_invitation(),public.change_organization_member_role(uuid,uuid,text),public.set_organization_member_status(uuid,uuid,text),public.remove_organization_member(uuid,uuid),public.transfer_organization_ownership(uuid,uuid,text)from public;
grant execute on function public.update_enterprise_organization(uuid,jsonb),public.set_enterprise_organization_logo(uuid,text),public.invite_organization_member(uuid,text,text,text),public.resend_organization_invitation(uuid,uuid),public.cancel_organization_invitation(uuid,uuid),public.accept_organization_invitation(),public.change_organization_member_role(uuid,uuid,text),public.set_organization_member_status(uuid,uuid,text),public.remove_organization_member(uuid,uuid),public.transfer_organization_ownership(uuid,uuid,text)to authenticated;
