-- Sprint 82.6: tenant-scoped Growth Studio planning. No publishing, ad buying, messaging, or rendering.
alter table public.creative_campaigns drop constraint if exists creative_campaigns_selected_variation_check;
alter table public.creative_campaigns add constraint creative_campaigns_selected_variation_check check(selected_variation in('Version A','Version B','Version C','Version D','Version E'));

create table if not exists public.creative_campaign_packs(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, workspace_id uuid not null references public.workspaces(id) on delete cascade, campaign_id uuid not null references public.creative_campaigns(id) on delete cascade, project_id uuid not null references public.inventory_projects(id), name text not null check(char_length(name) between 1 and 180), language text not null check(language in('English','Hindi','Arabic','Thai','Japanese','Spanish','German','French')), status text not null default 'draft' check(status in('draft','marketing-review','sales-review','management-approval','approved','ready-to-publish')), formats text[] not null, asset_count integer not null default 0 check(asset_count>=0), created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(campaign_id,language)
);
create table if not exists public.creative_campaign_schedule(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, workspace_id uuid not null references public.workspaces(id) on delete cascade, campaign_id uuid not null references public.creative_campaigns(id) on delete cascade, channel text not null check(channel in('Instagram','Facebook','LinkedIn','Email','WhatsApp','Website','Internal approvals')), scheduled_for timestamptz not null, state text not null default 'draft' check(state in('draft','approval-pending','ready')), publishing_enabled boolean not null default false check(publishing_enabled=false), created_by uuid not null references auth.users(id), created_at timestamptz not null default now()
);
create table if not exists public.creative_growth_reviews(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, workspace_id uuid not null references public.workspaces(id) on delete cascade, campaign_id uuid not null references public.creative_campaigns(id) on delete cascade, brand_compliance_score integer not null check(brand_compliance_score between 0 and 100), creative_quality_score integer not null check(creative_quality_score between 0 and 100), checks jsonb not null, suggestions text[] not null default '{}', recommendation_only boolean not null default true check(recommendation_only=true), created_by uuid not null references auth.users(id), created_at timestamptz not null default now()
);
create index if not exists creative_pack_scope_idx on public.creative_campaign_packs(organization_id,workspace_id,project_id,status,created_at desc);
create index if not exists creative_schedule_scope_idx on public.creative_campaign_schedule(organization_id,workspace_id,scheduled_for);
alter table public.creative_campaign_packs enable row level security; alter table public.creative_campaign_schedule enable row level security; alter table public.creative_growth_reviews enable row level security;
create policy "creative_pack_read" on public.creative_campaign_packs for select to authenticated using(public.creative_studio_member(organization_id,workspace_id));
create policy "creative_pack_write" on public.creative_campaign_packs for all to authenticated using(public.creative_studio_member(organization_id,workspace_id) and public.creative_studio_manage(workspace_id)) with check(public.creative_studio_member(organization_id,workspace_id) and public.creative_studio_manage(workspace_id));
create policy "creative_schedule_read" on public.creative_campaign_schedule for select to authenticated using(public.creative_studio_member(organization_id,workspace_id));
create policy "creative_schedule_write" on public.creative_campaign_schedule for all to authenticated using(public.creative_studio_member(organization_id,workspace_id) and public.creative_studio_manage(workspace_id)) with check(public.creative_studio_member(organization_id,workspace_id) and public.creative_studio_manage(workspace_id) and publishing_enabled=false);
create policy "creative_review_read" on public.creative_growth_reviews for select to authenticated using(public.creative_studio_member(organization_id,workspace_id));
create policy "creative_review_write" on public.creative_growth_reviews for all to authenticated using(public.creative_studio_member(organization_id,workspace_id) and public.creative_studio_manage(workspace_id)) with check(public.creative_studio_member(organization_id,workspace_id) and public.creative_studio_manage(workspace_id) and recommendation_only=true);

create or replace function public.create_growth_campaign_pack(p_campaign_id uuid,p_language text,p_formats text[]) returns uuid language plpgsql security definer set search_path=public as $$declare c public.creative_campaigns%rowtype;i uuid;begin select*into c from public.creative_campaigns where id=p_campaign_id for update;if not found or not public.creative_studio_member(c.organization_id,c.workspace_id) or not public.creative_studio_manage(c.workspace_id) then raise exception'insufficient growth studio permission';end if;if p_language not in('English','Hindi','Arabic','Thai','Japanese','Spanish','German','French')or cardinality(p_formats)<1 or cardinality(p_formats)>40 then raise exception'invalid campaign pack';end if;insert into public.creative_campaign_packs(organization_id,workspace_id,campaign_id,project_id,name,language,status,formats,created_by)values(c.organization_id,c.workspace_id,c.id,c.project_id,c.name||' package',p_language,'draft',p_formats,auth.uid())on conflict(campaign_id,language)do update set formats=excluded.formats,updated_at=now()returning id into i;insert into public.creative_timeline(organization_id,workspace_id,campaign_id,event_type,project_id,metadata,actor_id)values(c.organization_id,c.workspace_id,c.id,'campaign.pack_created',c.project_id,jsonb_build_object('pack_id',i,'language',p_language,'format_count',cardinality(p_formats),'recommendation_only',true,'publishing_enabled',false),auth.uid());return i;end$$;
revoke all on function public.create_growth_campaign_pack(uuid,text,text[])from public;grant execute on function public.create_growth_campaign_pack(uuid,text,text[])to authenticated;
