-- Sprint 83: commercial licensing, expanded AI metering, and Razorpay event storage.
alter table public.usage_events drop constraint if exists usage_events_metric_check;
alter table public.usage_events add constraint usage_events_metric_check check(metric in('ai_requests','tokens','storage_gb','users','whatsapp_messages','emails','calendar_events','api_calls','image_generations','creative_exports','video_projects','conversation_summaries','future_video_generation_credits'));

create table if not exists public.commercial_provider_customers(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,workspace_id uuid not null references public.workspaces(id) on delete cascade,provider text not null check(provider in('stripe','razorpay')),provider_customer_id text not null,livemode boolean not null default false,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id,provider),unique(provider,provider_customer_id)
);
create table if not exists public.workspace_feature_licenses(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,workspace_id uuid not null references public.workspaces(id) on delete cascade,feature text not null check(feature in('creative_studio_beta','growth_studio','ai_workforce','property_matching','communications','inventory','reports')),enabled boolean not null default false,source text not null check(source in('subscription','trial','enterprise-contract','administrator')),starts_at timestamptz not null default now(),ends_at timestamptz,updated_by uuid references auth.users(id),updated_at timestamptz not null default now(),unique(workspace_id,feature),check(ends_at is null or ends_at>starts_at)
);
create table if not exists public.commercial_webhook_events(
 id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id),workspace_id uuid references public.workspaces(id),provider text not null check(provider in('stripe','razorpay')),provider_event_id text not null,event_type text not null,status text not null check(status in('received','processed','ignored','failed')),error_code text,payload jsonb not null default '{}',received_at timestamptz not null default now(),processed_at timestamptz,unique(provider,provider_event_id)
);
create index if not exists commercial_customer_scope_idx on public.commercial_provider_customers(organization_id,workspace_id,provider);
create index if not exists feature_license_scope_idx on public.workspace_feature_licenses(organization_id,workspace_id,feature,enabled);
alter table public.commercial_provider_customers enable row level security;alter table public.workspace_feature_licenses enable row level security;alter table public.commercial_webhook_events enable row level security;
create policy "commercial_customer_read" on public.commercial_provider_customers for select to authenticated using(public.is_organization_member(organization_id)and public.current_workspace_role(workspace_id)in('organization_owner','organization_admin','billing_admin','finance','finance_manager','finance_analyst','read_only'));
create policy "feature_license_read" on public.workspace_feature_licenses for select to authenticated using(public.is_organization_member(organization_id)and public.current_workspace_role(workspace_id)is not null);
create policy "feature_license_manage" on public.workspace_feature_licenses for all to authenticated using(public.is_organization_member(organization_id)and public.current_workspace_role(workspace_id)in('organization_owner','organization_admin','billing_admin'))with check(public.is_organization_member(organization_id)and public.current_workspace_role(workspace_id)in('organization_owner','organization_admin','billing_admin'));
create policy "commercial_events_read" on public.commercial_webhook_events for select to authenticated using(organization_id is not null and public.is_organization_member(organization_id)and public.current_workspace_role(workspace_id)in('organization_owner','organization_admin','billing_admin','finance','finance_manager','finance_analyst','read_only'));

create or replace function public.workspace_feature_licensed(p_workspace_id uuid,p_feature text)returns boolean language sql stable security definer set search_path=public as $$select public.current_workspace_role(p_workspace_id)is not null and exists(select 1 from public.workspace_feature_licenses l where l.workspace_id=p_workspace_id and l.feature=p_feature and l.enabled=true and l.starts_at<=now()and(l.ends_at is null or l.ends_at>now()))$$;
create or replace function public.record_billing_usage(p_workspace_id uuid,p_metric text,p_quantity numeric,p_idempotency_key text)returns void language plpgsql security definer set search_path=public as $$declare v_org uuid;v_limit numeric;v_used numeric;v_start date=date_trunc('month',now())::date;v_end date=(date_trunc('month',now())+interval'1 month'-interval'1 day')::date;begin if p_quantity<0 or p_metric not in('ai_requests','tokens','storage_gb','users','whatsapp_messages','emails','calendar_events','api_calls','image_generations','creative_exports','video_projects','conversation_summaries','future_video_generation_credits')then raise exception'invalid usage event';end if;select organization_id into v_org from public.workspaces where id=p_workspace_id;if v_org is null or public.current_workspace_role(p_workspace_id)is null then raise exception'workspace unavailable';end if;select limit_value into v_limit from public.organization_limits where workspace_id=p_workspace_id and metric=p_metric;select coalesce(quantity,0)into v_used from public.organization_usage where workspace_id=p_workspace_id and metric=p_metric and period_start=v_start;if v_limit is not null and coalesce(v_used,0)+p_quantity>v_limit then raise exception'subscription limit exceeded for %',p_metric;end if;insert into public.usage_events(organization_id,workspace_id,metric,quantity,idempotency_key)values(v_org,p_workspace_id,p_metric,p_quantity,p_idempotency_key)on conflict(workspace_id,idempotency_key)do nothing;if found then insert into public.organization_usage(organization_id,workspace_id,metric,quantity,period_start,period_end)values(v_org,p_workspace_id,p_metric,p_quantity,v_start,v_end)on conflict(workspace_id,metric,period_start)do update set quantity=public.organization_usage.quantity+excluded.quantity,updated_at=now();end if;end$$;
create or replace function public.record_commercial_webhook(p_provider text,p_event_id text,p_event_type text,p_payload jsonb,p_workspace_id uuid default null)returns void language plpgsql security definer set search_path=public as $$declare o uuid;begin if current_setting('role',true)<>'service_role'then raise exception'service role required';end if;if p_provider not in('stripe','razorpay')then raise exception'unsupported billing provider';end if;select organization_id into o from public.workspaces where id=p_workspace_id;insert into public.commercial_webhook_events(organization_id,workspace_id,provider,provider_event_id,event_type,status,payload)values(o,p_workspace_id,p_provider,p_event_id,p_event_type,'received',p_payload)on conflict(provider,provider_event_id)do nothing;end$$;
revoke all on function public.workspace_feature_licensed(uuid,text)from public;grant execute on function public.workspace_feature_licensed(uuid,text)to authenticated;
revoke all on function public.record_commercial_webhook(text,text,text,jsonb,uuid)from public;grant execute on function public.record_commercial_webhook(text,text,text,jsonb,uuid)to service_role;
