export type DemoDepartmentId = "executive"|"sales"|"marketing"|"operations"|"customer-success"|"finance"|"hr"|"legal"|"technology"|"administration";
export type DemoRoleId = "ceo"|"coo"|"sales-director"|"sales-manager"|"sales-agent"|"marketing-manager"|"marketing-executive"|"operations-manager"|"operations-executive"|"customer-success-manager"|"finance-manager"|"hr-manager"|"office-administrator"|"future-ai-executive-advisor"|"future-ai-sales-advisor"|"future-ai-operations-advisor";
export interface DemoCompanyProfile { readonly id:string;readonly name:string;readonly legalName:string;readonly description:string;readonly mission:string;readonly vision:string;readonly industry:string;readonly businessType:string;readonly headquartersOfficeId:string;readonly regionalOfficeIds:readonly string[];readonly brand:DemoBrand;readonly workspace:DemoWorkspaceMetadata }
export interface DemoBrand { readonly primary:string;readonly accent:string;readonly warmNeutral:string;readonly logoAsset:string;readonly imageryAsset:string;readonly coverAsset:string }
export interface DemoWorkspaceMetadata { readonly id:string;readonly name:string;readonly slug:string;readonly timezone:string;readonly currency:string;readonly language:string;readonly countryCode:string;readonly logoPlaceholder:string;readonly persistence:"none";readonly status:"blueprint" }
export interface DemoDepartment { readonly id:DemoDepartmentId;readonly name:string;readonly description:string;readonly responsibilities:readonly string[];readonly managerRoleId:DemoRoleId;readonly reportsTo?:DemoDepartmentId }
export interface DemoRole { readonly id:DemoRoleId;readonly name:string;readonly departmentId:DemoDepartmentId;readonly purpose:string;readonly reportsToRoleId?:DemoRoleId;readonly workforceType:"human"|"future-ai" }
export interface DemoOffice { readonly id:string;readonly name:string;readonly kind:"headquarters"|"branch"|"division"|"remote";readonly city:string;readonly state:string;readonly countryCode:string;readonly addressStatus:"placeholder";readonly photoAsset:string }
export interface DemoBusinessUnit { readonly id:string;readonly name:string;readonly description:string }
export interface DemoWorkspaceAsset { readonly id:string;readonly kind:"company-logo"|"office-photo"|"brand-imagery"|"cover-image";readonly path:string;readonly placeholder:true;readonly alt:string }
export interface DemoWorkspaceBlueprint { readonly version:"1.8.0";readonly company:DemoCompanyProfile;readonly departments:readonly DemoDepartment[];readonly roles:readonly DemoRole[];readonly offices:readonly DemoOffice[];readonly businessUnits:readonly DemoBusinessUnit[];readonly assets:readonly DemoWorkspaceAsset[];readonly containsBusinessRecords:false;readonly containsAnalytics:false;readonly containsAIOutput:false }
