import"server-only";
import{createHash,createPublicKey,timingSafeEqual,verify}from"node:crypto";
import{integrationContext}from"@/features/platform/integrations/services/integration-context";
import{microsoftIdentityScopes}from"@/features/platform/integrations/identity";
import{log}from"@/lib/observability/logger";
import type{StoredMicrosoftCredential}from"../contracts";
import{MicrosoftCookieCredentialVault}from"../storage/cookie-credential.vault";
type TokenResponse={access_token:string;refresh_token?:string;expires_in:number;scope?:string;id_token:string};
type Claims={aud?:string;exp?:number;nonce?:string;sub?:string;tid?:string;iss?:string;preferred_username?:string;email?:string;name?:string};
type Header={kid?:string;alg?:string};
function config(){const clientId=process.env.MICROSOFT_CLIENT_ID,clientSecret=process.env.MICROSOFT_CLIENT_SECRET,redirectUri=process.env.MICROSOFT_OAUTH_REDIRECT_URI;if(!clientId||!clientSecret||!redirectUri)throw new Error("Microsoft OAuth environment is incomplete.");const redirect=new URL(redirectUri),app=process.env.NEXT_PUBLIC_APP_URL?new URL(process.env.NEXT_PUBLIC_APP_URL):null;if(process.env.NODE_ENV==="production"&&redirect.protocol!=="https:")throw new Error("Microsoft OAuth redirect must use HTTPS in production.");if(app&&redirect.origin!==app.origin)throw new Error("Microsoft OAuth redirect origin is not trusted.");return{clientId,clientSecret,redirectUri:redirect.toString()}}
function decode<T>(value:string){return JSON.parse(Buffer.from(value,"base64url").toString("utf8"))as T}
async function validatedClaims(idToken:string,nonce:string,clientId:string):Promise<Claims>{const parts=idToken.split(".");if(parts.length!==3)throw new Error("Microsoft identity token is malformed.");const header=decode<Header>(parts[0]),claims=decode<Claims>(parts[1]);if(header.alg!=="RS256"||!header.kid)throw new Error("Microsoft identity token algorithm is invalid.");const jwksResponse=await fetch("https://login.microsoftonline.com/organizations/discovery/v2.0/keys",{cache:"no-store"});if(!jwksResponse.ok)throw new Error("Microsoft signing keys are unavailable.");const jwks=await jwksResponse.json()as{keys:(Record<string,string>&{kid?:string})[]},key=jwks.keys.find(item=>item.kid===header.kid);if(!key||!verify("RSA-SHA256",Buffer.from(`${parts[0]}.${parts[1]}`),createPublicKey({key:key as import("node:crypto").JsonWebKey,format:"jwk"}),Buffer.from(parts[2],"base64url")))throw new Error("Microsoft identity token signature is invalid.");const issuer=claims.tid?`https://login.microsoftonline.com/${claims.tid}/v2.0`:"";if(claims.aud!==clientId||!claims.exp||claims.exp*1000<=Date.now()||claims.nonce!==nonce||!claims.sub||!claims.tid||claims.iss!==issuer)throw new Error("Microsoft identity token validation failed.");return claims}
export function microsoftSafeEqual(left:string,right:string){const a=Buffer.from(left),b=Buffer.from(right);return a.length===b.length&&timingSafeEqual(a,b)}
export class MicrosoftOAuthService{
  constructor(private vault=new MicrosoftCookieCredentialVault()){}
  authorizationUrl(input:{state:string;nonce:string;codeChallenge:string;additionalScopes?:readonly string[]}){const c=config(),scopes=[...new Set([...microsoftIdentityScopes,...(input.additionalScopes??[])])],query=new URLSearchParams({client_id:c.clientId,response_type:"code",redirect_uri:c.redirectUri,response_mode:"query",scope:scopes.join(" "),state:input.state,nonce:input.nonce,code_challenge:input.codeChallenge,code_challenge_method:"S256",prompt:"select_account"});return`https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?${query}`}
  async exchange(input:{code:string;codeVerifier:string;nonce:string;requiredScopes?:readonly string[]}){const c=config(),requested=[...new Set([...microsoftIdentityScopes,...(input.requiredScopes??[])])],response=await fetch("https://login.microsoftonline.com/organizations/oauth2/v2.0/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,code:input.code,code_verifier:input.codeVerifier,redirect_uri:c.redirectUri,grant_type:"authorization_code",scope:requested.join(" ")}),cache:"no-store"});if(!response.ok){log("microsoft.identity.exchange_failed",{status:response.status});throw new Error("Microsoft authorization exchange failed.")}const token=await response.json()as TokenResponse;if(!token.access_token||!token.refresh_token||!token.id_token)throw new Error("Microsoft did not return required offline credentials.");const claims=await validatedClaims(token.id_token,input.nonce,c.clientId),granted=(token.scope??"").split(" ").filter(Boolean);if(!requested.every(scope=>granted.includes(scope)))throw new Error("Microsoft did not grant required permissions.");const profileResponse=await fetch("https://graph.microsoft.com/v1.0/me?$select=id,displayName,mail,userPrincipalName",{headers:{authorization:`Bearer ${token.access_token}`},cache:"no-store"});if(!profileResponse.ok)throw new Error("Microsoft connection validation failed.");const profile=await profileResponse.json()as{id:string;displayName?:string;mail?:string;userPrincipalName?:string};const ctx=await integrationContext(),existing=await this.vault.load(ctx.workspaceId),credential:StoredMicrosoftCredential={accountId:profile.id,email:profile.mail??profile.userPrincipalName??claims.email??claims.preferred_username??"",displayName:profile.displayName??claims.name??null,tenantId:claims.tid!,organization:null,scopes:[...new Set([...(existing?.scopes??[]),...granted])],accessToken:token.access_token,refreshToken:token.refresh_token,expiresAt:new Date(Date.now()+token.expires_in*1000).toISOString(),version:(existing?.version??0)+1,validatedAt:new Date().toISOString()};if(!credential.email)throw new Error("Microsoft account email is unavailable.");await this.vault.save(ctx.workspaceId,credential);log("microsoft.identity.connected",{workspaceId:ctx.workspaceId,provider:"microsoft",tenantId:credential.tenantId,scopeCount:credential.scopes.length})}
  async credential(){const ctx=await integrationContext();return this.vault.load(ctx.workspaceId)}
  async accessToken(){const ctx=await integrationContext(),stored=await this.vault.load(ctx.workspaceId);if(!stored)throw new Error("Microsoft 365 is not connected.");if(new Date(stored.expiresAt).getTime()>Date.now()+60_000)return stored.accessToken;const c=config(),response=await fetch("https://login.microsoftonline.com/organizations/oauth2/v2.0/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,refresh_token:stored.refreshToken,grant_type:"refresh_token",scope:microsoftIdentityScopes.join(" ")}),cache:"no-store"});if(!response.ok){log("microsoft.identity.refresh_failed",{workspaceId:ctx.workspaceId,status:response.status});throw new Error("Microsoft token refresh failed.")}const token=await response.json()as Omit<TokenResponse,"id_token">;await this.vault.save(ctx.workspaceId,{...stored,accessToken:token.access_token,refreshToken:token.refresh_token??stored.refreshToken,expiresAt:new Date(Date.now()+token.expires_in*1000).toISOString(),version:stored.version+1,validatedAt:new Date().toISOString()});log("microsoft.identity.refreshed",{workspaceId:ctx.workspaceId,version:stored.version+1});return token.access_token}
  async disconnect(){const ctx=await integrationContext();await this.vault.remove();log("microsoft.identity.disconnected",{workspaceId:ctx.workspaceId,provider:"microsoft"})}
  static codeChallenge(verifier:string){return createHash("sha256").update(verifier).digest("base64url")}
}
