import { runLaunchReadinessAuditAction } from "../actions";
import { Button, ButtonLink } from "@/features/platform/design-system";
import type { AuditCheck, LaunchReadinessSnapshot, TechnicalDebt } from "../contracts";

const card = "rounded-2xl border border-vds-border bg-vds-surface p-5";

export function LaunchReadinessDashboard({ data }: { data: LaunchReadinessSnapshot }) {
  return <main className="space-y-7 p-6 lg:p-8">
    <header className="flex flex-wrap items-end justify-between gap-4">
      <div><p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">Enterprise launch audit</p><h1 className="mt-2 text-3xl font-semibold">Production Readiness</h1><p className="mt-2 text-sm text-vds-muted">Evidence from deployment, security, performance, providers, application modules, journeys, accessibility, browsers, and SEO.</p></div>
      <div className="flex gap-2"><form action={runLaunchReadinessAuditAction}><Button type="submit">Run and record audit</Button></form><ButtonLink href="/api/launch-readiness/report" variant="outline">Export launch checklist</ButtonLink></div>
    </header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className={card}><p className="text-xs text-vds-muted">Production Score</p><p className="mt-2 text-4xl font-semibold">{data.score}/100</p></article><article className={card}><p className="text-xs text-vds-muted">Status</p><p className="mt-2 text-xl font-semibold capitalize">{data.state.replaceAll("_", " ")}</p></article><article className={card}><p className="text-xs text-vds-muted">Outstanding blockers</p><p className="mt-2 text-3xl font-semibold">{data.blockers.length}</p></article><article className={card}><p className="text-xs text-vds-muted">Audit history</p><p className="mt-2 text-3xl font-semibold">{data.history.length}</p></article></section>
    <CheckSection title="Application audit" checks={data.modules}/><CheckSection title="User journey audit" checks={data.journey}/><CheckSection title="Deployment, performance, security, accessibility & SEO" checks={data.checks.filter(x => !["Application", "User journey", "Cross-browser"].includes(x.category))}/><CheckSection title="Cross-browser compatibility report" checks={data.browsers}/>
    <section><h2 className="text-xl font-semibold">Provider health</h2><div className="mt-3 grid gap-3 md:grid-cols-3">{data.providerHealth.map(x => <article className={card} key={x.component}><div className="flex justify-between gap-3"><h3 className="capitalize">{x.component}</h3><span className="text-xs uppercase">{x.state}</span></div><p className="mt-2 text-xs text-vds-muted">{x.diagnostic}</p></article>)}</div></section>
    <Debt debt={data.debt}/><section className={card}><h2 className="font-semibold">Readiness history & regression trends</h2><div className="mt-3 space-y-2">{data.history.map(item => <p className="text-sm" key={item.createdAt}>{new Date(item.createdAt).toLocaleString()} · {item.score}/100 · {item.state.replaceAll("_", " ")}</p>)}{!data.history.length && <p className="text-sm text-vds-muted">No prior recorded audit exists. Run the audit to establish the readiness baseline.</p>}</div></section>
  </main>;
}

function CheckSection({ title, checks }: { title: string; checks: readonly AuditCheck[] }) { return <section><h2 className="text-xl font-semibold">{title}</h2><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{checks.map(x => <article className={card} key={x.id}><div className="flex justify-between gap-3"><h3 className="font-medium">{x.label}</h3><span className="text-xs uppercase">{x.status.replaceAll("_", " ")}</span></div><p className="mt-2 text-xs text-vds-muted">{x.evidence}</p></article>)}</div></section>; }
function Debt({ debt }: { debt: readonly TechnicalDebt[] }) { return <section><h2 className="text-xl font-semibold">Technical debt</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{(["critical", "high", "medium", "low"] as const).map(severity => <article className={card} key={severity}><h3 className="capitalize">{severity} · {debt.filter(x => x.severity === severity).length}</h3>{debt.filter(x => x.severity === severity).slice(0, 6).map(x => <div className="mt-3 text-sm" key={x.id}><p className="font-medium">{x.finding}</p><p className="mt-1 text-xs text-vds-muted">{x.recommendation}</p></div>)}</article>)}</div></section>; }
