export type AnalyticsEventName="organization_created"|"workspace_completed"|"onboarding_completed"|"first_ai_interaction"|"subscription_initiated"|"ai_workforce_used"|"crm_used"|"knowledge_used"|"workflow_used"|"notifications_used"|"email_used"|"executive_dashboard_used"|"marketing_ai_used"|"sales_ai_used"|"whatsapp_ai_used";
export interface AnalyticsEvent{readonly name:AnalyticsEventName;readonly path:string;readonly durationMs?:number;readonly metadata?:Readonly<Record<string,string|number|boolean>>}
export interface AnalyticsMetric{readonly label:string;readonly value:number|null;readonly unit:"count"|"percent"|"milliseconds"|"currency"|"tokens";readonly source:string;readonly available:boolean;readonly reason?:string}
export interface AnalyticsSection{readonly title:string;readonly metrics:readonly AnalyticsMetric[]}
export interface EnterpriseAnalyticsSnapshot{readonly acquisition:AnalyticsSection;readonly funnel:AnalyticsSection;readonly adoption:AnalyticsSection;readonly success:AnalyticsSection;readonly ai:AnalyticsSection;readonly roi:AnalyticsSection;readonly conversion:AnalyticsSection;readonly performance:AnalyticsSection;readonly health:{readonly state:"healthy"|"degraded"|"unavailable";readonly trackingFailures:number;readonly missingEvents:readonly string[]};readonly generatedAt:string}
export interface ConversionAnalyticsRepository{snapshot():Promise<EnterpriseAnalyticsSnapshot>;record(event:AnalyticsEvent):Promise<void>}
export interface HeatmapProvider{readonly id:"microsoft-clarity"|"hotjar"|"posthog-session-replay"|string;readonly enabled:boolean;initialize(consent:ConsentState):Promise<void>;identifyWorkspace?(workspaceId:string):Promise<void>;stop():Promise<void>}
export interface ExperimentVariant{readonly id:string;readonly weight:number}export interface Experiment{readonly id:string;readonly surface:"landing-page"|"cta"|"pricing"|"industry-page";readonly variants:readonly ExperimentVariant[];readonly active:boolean}
export interface ExperimentProvider{assign(experiment:Experiment,anonymousId:string):ExperimentVariant;expose(experimentId:string,variantId:string):Promise<void>}
export interface ConsentState{readonly necessary:true;readonly analytics:boolean;readonly marketing:boolean;readonly heatmaps:boolean;readonly updatedAt:string;readonly version:"1"}
